{
 "title": "Node Dashboard",
 "tags": [ "RLEC" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(node_up,cluster)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_up{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(node_up{cluster=\"$cluster\",node=\"$node\"}, cnm_version)"
    }
   },
   {
    "name": "aggregation",
    "label": "interval aggregation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Node $node : Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Database Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(redis_used_memory{cluster=\"$cluster\", node=\"$node\"}) by (bdb))"
      }
     ]
    },
    {
     "title": "Master Shard Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(redis_used_memory{cluster=\"$cluster\", node=\"$node\", role=\"master\"})"
      }
     ]
    },
    {
     "title": "Replica Shard Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(redis_used_memory{cluster=\"$cluster\", node=\"$node\", role=\"slave\"})"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_cpu_system{node=\"$node\",cluster=\"$cluster\"} + node_cpu_user{node=\"$node\",cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Free Memory",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_available_memory{cluster=\"$cluster\",node=\"$node\"}"
      }
     ]
    },
    {
     "title": "Version",
     "type": "text",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
     "options": {
      "content": "<br>\n<center>\n  <b style=\"font-size: 20pt\">$version<b>\n</center>\n"
     },
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "Node $node : CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage on Node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percentunit", "label": "percents" }
   ],
   "targets": [
    {
     "expr": " node_cpu_user{cluster=\"$cluster\", node=\"$node\"} + node_cpu_system{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "user+system"
    },
    {
     "expr": "1- node_cpu_idle{cluster=\"$cluster\", node=\"$node\"} - node_cpu_system{cluster=\"$cluster\", node=\"$node\"} - node_cpu_user{cluster=\"$cluster\", node=\"$node\"} unless node_cpu_nice{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "other"
    },
    {
     "expr": "dmcproxy_process_cpu_usage_percent{cluster=\"$cluster\", node=\"$node\"}/100",
     "legendFormat": "dmcproxy (100% = 1 core)"
    },
    {
     "expr": "sum(redis_process_cpu_usage_percent{cluster=\"$cluster\", node=\"$node\"}/100)",
     "legendFormat": "shards (100% = 1 core)"
    }
   ]
  },
  {
   "title": "Node Traffic",
   "type": "graph",
   "description": "display the egress and ingress traffic on the node's NIC",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "Bps", "label": "Egress bytes/sec " }
   ],
   "targets": [
    {
     "expr": "node_ingress_bytes{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "Ingress for node {{node}}"
    },
    {
     "expr": "node_egress_bytes{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "egress for node {{node}}"
    }
   ]
  },
  {
   "title": "Fragmentation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(redis_allocator_active{node=\"$node\",cluster=\"$cluster\"} / redis_allocator_allocated{node=\"$node\",cluster=\"$cluster\"}) - 1",
     "legendFormat": "active / allocated (defraggable)"
    },
    {
     "expr": "avg(redis_allocator_resident{node=\"$node\",cluster=\"$cluster\"} / redis_allocator_active{node=\"$node\",cluster=\"$cluster\"}) - 1",
     "legendFormat": "resident / active (purgable)"
    },
    {
     "expr": "sum(redis_allocator_active{node=\"$node\",cluster=\"$cluster\"} - redis_allocator_allocated{node=\"$node\",cluster=\"$cluster\"})",
     "legendFormat": "active - allocated (defraggable)"
    },
    {
     "expr": "sum(redis_allocator_resident{node=\"$node\",cluster=\"$cluster\"} - redis_allocator_active{node=\"$node\",cluster=\"$cluster\"})",
     "legendFormat": "resident - active (purgable)"
    },
    {
     "expr": "avg(redis_active_defrag_running{node=\"$node\",cluster=\"$cluster\"})/100",
     "legendFormat": "active defrag running"
    },
    {
     "expr": "sum(redis_process_resident_memory_bytes{node=\"$node\",cluster=\"$cluster\"}) - sum(redis_allocator_resident{node=\"$node\",cluster=\"$cluster\"})",
     "legendFormat": "process rss - allocator rss"
    },
    {
     "expr": "sum(redis_process_resident_memory_bytes{node=\"$node\",cluster=\"$cluster\"}) / sum(redis_allocator_resident{node=\"$node\",cluster=\"$cluster\"})",
     "legendFormat": "process rss / allocator rss"
    }
   ]
  },
  {
   "title": "Top 10 Shards by Used Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, redis_used_ram{cluster=\"$cluster\", node=\"$node\"} or redis_used_memory{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "redis:{{redis}}, bdb:{{bdb}},  role:{{role}}"
    },
    {
     "expr": "dmcproxy_process_resident_memory_bytes{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "dmcproxy"
    }
   ]
  }
 ]
}