{
 "title": "Synchronization Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(node_up,cluster)" } },
   { "name": "region", "label": "region" },
   { "name": "bdb_name", "label": "database", "query": { "query": "query_result(bdb_up)" } },
   { "name": "db", "label": "database", "query": { "query": "label_values(bdb_up,bdb_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Synchronization Status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bdb_crdt_syncer_status{cluster=\"$cluster\"}",
     "legendFormat": "{{bdb_name}}-{{src_id}}"
    }
   ]
  },
  {
   "title": "Synchronization Ingress Lag",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "bdb_crdt_syncer_local_ingress_lag_time{cluster=\"$cluster\"}",
     "legendFormat": "{{bdb_name}}"
    }
   ]
  },
  {
   "title": "Synchronization Merge Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_crdt_merge_reqs{vcluster=\"$cluster\", role=\"slave\"} * on(bdb) group_left(bdb_name) bdb_up{}",
     "legendFormat": "{{cluster}}: {{bdb_name}}"
    }
   ]
  },
  {
   "title": "Synchronization Backlog",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_crdt_backlog_histlen{role=\"master\"} * on(bdb) group_left(bdb_name) bdb_up{}",
     "legendFormat": "{{bdb_name}}-{{crdt_replica_id}}"
    }
   ]
  },
  { "title": "database: $db", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "db" },
  {
   "title": "Synchronization Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bdb_crdt_syncer_status{cluster=\"$cluster\", bdb=\"$bdb_name\"}",
     "legendFormat": "{{bdb_name}}-{{src_id}}"
    }
   ]
  },
  {
   "title": "Synchronization Ingress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bdb_crdt_syncer_ingress_bytes{cluster=\"$cluster\", bdb=\"$bdb_name\"}",
     "legendFormat": "{{bdb_name}}"
    }
   ]
  },
  {
   "title": "Synchronization Egress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bdb_crdt_syncer_egress_bytes{cluster=\"$cluster\", bdb=\"$bdb_name\"}",
     "legendFormat": "{{bdb_name}}"
    }
   ]
  },
  {
   "title": "Synchronization Backlog",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_crdt_backlog_histlen{cluster=\"$cluster\", role=\"master\", bdb=\"$bdb_name\"} * on(bdb) group_left(bdb_name) bdb_up{}",
     "legendFormat": "{{bdb_name}}-{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "Synchronization Max Pending Writes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bdb_crdt_syncer_pending_local_writes_max{cluster=\"$cluster\", bdb=\"$bdb_name\"}",
     "legendFormat": "{{bdb_name}}-{{src_id}}"
    }
   ]
  },
  {
   "title": "Synchronization Ingress (Decompressed)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bdb_crdt_syncer_ingress_bytes_decompressed{cluster=\"$cluster\", crdt_replica_id=\"1\", bdb=\"$bdb_name\"}",
     "legendFormat": "{{bdb_name}}"
    }
   ]
  },
  {
   "title": "Synchronization Egress (Decompressed)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bdb_crdt_syncer_egress_bytes_decompressed{cluster=\"$cluster\", bdb=\"$bdb_name\"}",
     "legendFormat": "{{bdb_name}}"
    }
   ]
  },
  {
   "title": "Synchronization Raw Database Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_crdt_raw_dbsize{cluster=\"$cluster\", role=\"master\", bdb=\"$bdb_name\"} * on(bdb) group_left(bdb_name) bdb_up{cluster=\"$cluster\"}",
     "legendFormat": "{{bdb_name}}-{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "Synchronization Lag",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_crdt_peer_lag{cluster=\"$cluster\", bdb=\"$bdb_name\"} * on(bdb) group_left(bdb_name) bdb_up{cluster=\"$cluster\"}",
     "legendFormat": "{{bdb_name}}-{{dst_id}}"
    }
   ]
  },
  {
   "title": "Ingress Synchronization Lag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "bdb_crdt_syncer_local_ingress_lag_time{cluster=\"$cluster\", bdb=\"$bdb_name\"}",
     "legendFormat": "{{bdb_name}}"
    }
   ]
  },
  {
   "title": "Synchronization Merge Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_crdt_merge_reqs{cluster=\"$cluster\", role=\"slave\", bdb=\"$bdb_name\"} * on(bdb) group_left(bdb_name) bdb_up{cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}-{{bdb_name}}"
    }
   ]
  },
  {
   "title": "Synchronization Pending GC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_crdt_gc_collected{cluster=\"$cluster\", role=\"master\", bdb=\"$bdb_name\"} * on(bdb) group_left(bdb_name) bdb_up{cluster=\"$cluster\"}",
     "legendFormat": "{{bdb_name}}-{{crdt_replica_id}}"
    }
   ]
  }
 ]
}