{
 "title": "Shard Dashboard",
 "tags": [ "RLEC" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(node_up,cluster)" } },
   {
    "name": "bdb",
    "label": "database",
    "query": {
     "query": "bdb_conns{cluster=\"$cluster\"}"
    }
   },
   {
    "name": "status",
    "query": {
     "query": "label_values(redis_up{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"}, status)"
    }
   },
   {
    "name": "newStatus",
    "query": {
     "query": "label_values(bdb_up{bdb=\"$bdb\", cluster=\"$cluster\"}, status)"
    }
   },
   {
    "name": "shard",
    "label": "shard",
    "query": {
     "query": "label_values(redis_up{cluster=\"$cluster\", bdb=\"$bdb\"}, redis)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$bdb : shard $shard : Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "<br>\n<center>\n<b style=\"font-size: 20pt\">$newStatus<b>\n</center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(redis_process_cpu_usage_percent{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(redis_used_memory{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"})"
    }
   ]
  },
  {
   "title": "Key Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_db0_keys{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"}"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(redis_connected_clients{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"})"
    }
   ]
  },
  {
   "title": "Forwarding",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_forwarding_state{cluster=\"$cluster\", bdb=\"$bdb\", redis=\"$shard\"})"
    }
   ]
  },
  {
   "title": "$bdb : shard $shard : Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Max Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "redis_maxmemory{cluster=\"$cluster\", bdb=\"$bdb\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "redis_allocator_allocated{cluster=\"$cluster\", bdb=\"$bdb\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "redis_allocator_allocated{cluster=\"$cluster\", bdb=\"$bdb\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "redis_allocator_allocated{cluster=\"$cluster\", bdb=\"$bdb\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "Fragmentation Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "redis_mem_fragmentation_ratio{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "AOF Buffer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "redis_mem_aof_buffer{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "Memory less Eviction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "redis_mem_not_counted_for_evict{cluster=\"$cluster\", bdb=\"$bdb\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "Replication Backlog",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "redis_mem_replication_backlog{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "$bdb : shard $shard : CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Process CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_process_cpu_system_seconds_total{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "System CPU"
    },
    {
     "expr": "redis_process_cpu_user_seconds_total{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "User CPU"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "redis_process_cpu_usage_percent{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Main Thread",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_process_main_thread_cpu_system_seconds_total{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "Main Thread - System"
    },
    {
     "expr": "redis_process_main_thread_cpu_user_seconds_total{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "Main Thread - User"
    }
   ]
  },
  {
   "title": "$bdb : shard $shard : Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "redis_total_connections_received{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "Total"
    },
    {}
   ]
  },
  {
   "title": "Commands Processed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_connected_clients{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "Connected Clients"
    },
    {
     "expr": "redis_blocked_clients{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "Blocked Clients"
    }
   ]
  },
  {
   "title": "Ingress/Egress",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "Bps", "label": "Ingress" }
   ],
   "targets": [
    {
     "expr": "redis_total_net_output_bytes{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "Egress"
    },
    {
     "expr": "redis_total_net_input_bytes{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "Ingress"
    }
   ]
  },
  {
   "title": "$bdb : shard $shard : Keys",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Keys per Shard",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_no_of_keys{cluster=\"$cluster\", bdb=\"$bdb\"} or redis_db0_keys{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "shard:{{redis}}, role: {{role}}, node:{{node}}, slots:{{slots}}"
    }
   ]
  },
  {
   "title": "Total Keys",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_db0_keys{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "shard: {{redis}}"
    }
   ]
  },
  {
   "title": "Evicted Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_evicted_keys{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "shard: {{redis}}"
    }
   ]
  },
  {
   "title": "Expired Keys",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_expired_keys{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "shard: {{redis}}"
    }
   ]
  },
  {
   "title": "$bdb : shard $shard : Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Fragmentation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(redis_mem_fragmentation_ratio{bdb=\"$bdb\",cluster=\"$cluster\", redis=\"$shard\"}) / count(redis_mem_fragmentation_ratio{bdb=\"$bdb\",cluster=\"$cluster\", redis=\"$shard\"})",
     "legendFormat": "redis_mem_fragmentation_ratio"
    },
    {
     "expr": "sum(redis_allocator_active{bdb=\"$bdb\",cluster=\"$cluster\", redis=\"$shard\"}) / sum(redis_allocator_allocated{bdb=\"$bdb\",cluster=\"$cluster\", redis=\"$shard\"})",
     "legendFormat": "Shard allocator fragmentation"
    },
    {
     "expr": "sum(redis_allocator_resident{bdb=\"$bdb\",cluster=\"$cluster\", redis=\"$shard\"}) / sum(redis_allocator_active{bdb=\"$bdb\",cluster=\"$cluster\", redis=\"$shard\"})",
     "legendFormat": "shard allocator rss"
    }
   ]
  },
  {
   "title": "Shard RSS Fragmentation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 48 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "redis_mem_fragmentation_ratio{cluster=\"$cluster\", bdb=\"$bdb\", redis=\"$shard\"} ",
     "legendFormat": "shard:{{redis}} role:{{role}}"
    }
   ]
  },
  {
   "title": "Shard Allocation Fragmentation (#)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "redis_allocator_active{bdb=\"$bdb\",cluster=\"$cluster\", redis=\"$shard\"} - redis_allocator_allocated{bdb=\"$bdb\",cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "shard:{{redis}} role:{{role}}"
    }
   ]
  },
  {
   "title": "Shard Allocation Fragmentation (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 48 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "redis_allocator_active{bdb=\"$bdb\",cluster=\"$cluster\", redis=\"$shard\"} / redis_allocator_allocated{bdb=\"$bdb\",cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "shard:{{redis}} role:{{role}}"
    }
   ]
  },
  {
   "title": "$bdb : shard $shard : ROF Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Used Memory(ROF) for $bdb",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bdb_used_ram{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "bdb_used_ram"
      },
      {
       "expr": "bdb_ram_limit{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "limit (when low, near used)"
      }
     ]
    },
    {
     "title": "DB ram hit ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(bdb_big_fetch_ram{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_write_ram{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_del_ram{bdb=\"$bdb\", cluster=\"$cluster\"}) / (bdb_big_fetch_flash{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_write_flash{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_del_flash{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_fetch_ram{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_write_ram{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_del_ram{bdb=\"$bdb\", cluster=\"$cluster\"}) > 0",
       "legendFormat": "DB ram hit ratio"
      },
      {
       "expr": "bdb_big_fetch_ram{bdb=\"$bdb\", cluster=\"$cluster\"}  / (bdb_big_fetch_flash{bdb=\"$bdb\", cluster=\"$cluster\"}  + bdb_big_fetch_ram{bdb=\"$bdb\", cluster=\"$cluster\"} ) > 0",
       "legendFormat": "read hit ratio"
      },
      {
       "expr": "bdb_big_write_ram{bdb=\"$bdb\", cluster=\"$cluster\"}  / (bdb_big_write_flash{bdb=\"$bdb\", cluster=\"$cluster\"}  + bdb_big_write_ram{bdb=\"$bdb\", cluster=\"$cluster\"} ) > 0",
       "legendFormat": "write hit ratio"
      },
      {
       "expr": "bdb_big_del_ram{bdb=\"$bdb\", cluster=\"$cluster\"}  / (bdb_big_del_flash{bdb=\"$bdb\", cluster=\"$cluster\"}  + bdb_big_del_ram{bdb=\"$bdb\", cluster=\"$cluster\"} ) > 0",
       "legendFormat": "del hit ratio"
      }
     ]
    },
    {
     "title": "RAM:Flash access ratio",
     "type": "graph",
     "description": "Positive is RAM, Negative is Flash",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "avg(delta(redis_big_io_ratio_redis{cluster=\"$cluster\",bdb=\"$bdb\",role=\"master\"}[1m]))/60",
       "legendFormat": "RAM Ops for Redis"
      },
      {
       "expr": "avg(delta(redis_big_io_ratio_flash{cluster=\"$cluster\",bdb=\"$bdb\",role=\"master\"}[1m]) * -1)/60",
       "legendFormat": "Flash Ops for Redis"
      },
      {
       "expr": "avg(delta(redis_big_user_io_ratio_redis{cluster=\"$cluster\",bdb=\"$bdb\",role=\"master\"}[1m]))/60",
       "legendFormat": "User RAM Ops for Redis"
      },
      {
       "expr": "avg(delta(redis_big_user_io_ratio_flash{cluster=\"$cluster\",bdb=\"$bdb\",role=\"master\"}[1m]) * -1)/60",
       "legendFormat": "User Flash Ops for Redis"
      }
     ]
    },
    {
     "title": "RAM:Flash access ratio",
     "type": "graph",
     "description": "Positive is RAM, Negative is Flash",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "delta(redis_big_io_ratio_redis{cluster=\"$cluster\",bdb=\"$bdb\"}[1m])/60",
       "legendFormat": "RAM Ops for Redis {{redis}}"
      },
      {
       "expr": "delta(redis_big_io_ratio_flash{cluster=\"$cluster\",bdb=\"$bdb\"}[1m]) / -60",
       "legendFormat": "Flash Ops for Redis {{redis}}"
      }
     ]
    },
    {
     "title": "Flash IO Banwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bdb_bigstore_io_read_bytes{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Reads"
      },
      {
       "expr": "bdb_bigstore_io_write_bytes{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Flash IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_bigstore_io_reads{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Reads"
      },
      {
       "expr": "bdb_bigstore_io_writes{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Writes"
      },
      {
       "expr": "bdb_bigstore_io_dels{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Deletes"
      }
     ]
    },
    {
     "title": "BDB sum redis wait busy key / $aggregation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(redis_wait_busy_key{bdb=\"$bdb\",cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB sum redis blocking reads / $aggregation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(redis_blocking_reads{bdb=\"$bdb\",cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB used flash",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bdb_used_bigstore{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "used"
      },
      {
       "expr": "bdb_used_bigstore{bdb=\"$bdb\",cluster=\"$cluster\"} * bdb_disk_frag_ratio{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "actual"
      },
      {
       "expr": "bdb_disk_frag_ratio{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "frag ratio"
      }
     ]
    },
    {
     "title": "BDB postponed clients",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 99 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_big_postponed_clients{cluster=\"$cluster\",bdb=\"$bdb\"}",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB blocked clients",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 99 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_big_blocked_clients{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "Number of blocked clients"
      }
     ]
    },
    {
     "title": "BDB ram overhead",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 99 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "bdb_ram_overhead{cluster=\"$cluster\",bdb=\"$bdb\"}  / bdb_ram_limit{cluster=\"$cluster\",bdb=\"$bdb\"}",
       "legendFormat": "Total Ratio"
      },
      {
       "expr": "redis_ram_overhead{cluster=\"$cluster\",bdb=\"$bdb\"} / redis_max_ram{cluster=\"$cluster\",bdb=\"$bdb\"}",
       "legendFormat": "redis: {{redis}} role:{{role}}"
      }
     ]
    },
    {
     "title": "BDB sum redis blocking writes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 107 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redis_blocking_writes{bdb=\"$bdb\",cluster=\"$cluster\"}[1m]))",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB sum redis big inst avg read io queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 107 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redis_big_inst_avg_read_io_queue{bdb=\"$bdb\",cluster=\"$cluster\"})",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB sum redis big inst avg write io queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 107 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redis_big_inst_avg_write_io_queue{bdb=\"$bdb\",cluster=\"$cluster\"})",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB objects(values) in FLASH",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 115 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_bigstore_objs_flash{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "objects in flash (sum of all master shards)"
      },
      {
       "expr": "bdb_bigstore_objs_ram{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "objects in ram (sum of all master shards)"
      }
     ]
    },
    {
     "title": "BDB % values in RAM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 115 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "bdb_bigstore_objs_ram{bdb=\"$bdb\",cluster=\"$cluster\"} / bdb_no_of_keys{bdb=\"$bdb\",cluster=\"$cluster\"} ",
       "legendFormat": "BDB % values in RAM (masters)"
      },
      {
       "expr": "avg((max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster)) / on (redis,bdb,cluster) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"})",
       "legendFormat": "average master shard % values in RAM"
      },
      {
       "expr": "avg((max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (redis,bdb,cluster)) / on (redis,bdb,cluster) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"})",
       "legendFormat": "average slave shard % values in RAM"
      },
      {
       "expr": "topk(1, min((max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster)) / on (redis,bdb,cluster) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (redis) * -1) *-1",
       "legendFormat": "lowest master shard % values in RAM - redsi:{{redis}}"
      },
      {
       "expr": "topk(1, min((max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (redis,bdb,cluster)) / on (redis,bdb,cluster) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (redis) * -1) *-1",
       "legendFormat": "lowest slave shard % values in RAM - redsi:{{redis}}"
      }
     ]
    },
    {
     "title": "Shard objects(values) in RAM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 115 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (redis,bdb,cluster))",
       "legendFormat": "average number of values in ram per slave shard"
      },
      {
       "expr": "avg(max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster))",
       "legendFormat": "average number of values in ram per master shard"
      },
      {
       "expr": "topk(1, min(max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (redis,bdb,cluster) < on(cluster,bdb,redis) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} ) by (bdb, redis) * -1) * -1",
       "legendFormat": "lowest number of values in ram per slave shard - redis:{{redis}}"
      },
      {
       "expr": "topk(1, min(max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster) < on(cluster,bdb,redis) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (bdb, redis) * -1) * -1",
       "legendFormat": "lowest number of values in ram per master shard  - redis:{{redis}}"
      }
     ]
    },
    {
     "title": "BDB dirty RAM evictions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 123 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_big_ram_dirty_evictions{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB clean RAM evictions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 123 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_big_ram_clean_evictions{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "RocksDB",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 123 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(redis_rocks_comp_started{bdb=\"$bdb\", cluster=\"$cluster\"}[1m]))",
       "legendFormat": "compactions"
      },
      {
       "expr": "sum(delta(redis_rocks_flush_started{bdb=\"$bdb\", cluster=\"$cluster\"}[1m]))",
       "legendFormat": "flushes"
      },
      {
       "expr": "sum(delta(redis_rocks_flush_writes_slowdown{bdb=\"$bdb\", cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "slowdowns / $aggregation"
      },
      {
       "expr": "sum(delta(redis_rocks_flush_writes_stop{bdb=\"$bdb\", cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "stalls / $aggregation"
      }
     ]
    }
   ]
  }
 ]
}