{
 "title": "Cluster Nodes",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(bdb_up,cluster)" } },
   { "name": "node", "label": "node", "query": { "query": "label_values(node_up,node)" } }
  ]
 },
 "panels": [
  { "title": "Node: $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Max System CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_cpu_system_max{node=\"$node\"}",
     "legendFormat": "{{cluster}} : {{node}}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_available_memory{node=\"$node\"}",
     "legendFormat": " {{cluster}} : {{node}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "node_total_req{node=\"$node\"}",
     "legendFormat": "{{cluster}} : {{node}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "node_avg_latency{node=\"$node\"}",
     "legendFormat": "{{cluster}} : {{node}}"
    }
   ]
  }
 ]
}