{
 "title": "Cluster Node Memory",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(node_up,cluster)" } },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_up{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "aggregation",
    "label": "interval aggregation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Available Memory on Node $node",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_available_memory{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "available"
    },
    {
     "expr": "node_available_memory_no_overbooking{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "w/o overbooking"
    }
   ]
  },
  {
   "title": "Provisional Memory on Node $node",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_provisional_memory{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "available"
    },
    {
     "expr": "node_provisional_memory_no_overbooking{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "w/o overbooking"
    }
   ]
  },
  {
   "title": "Persistence Storage on Node $node",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_persistent_storage_avail{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "available"
    },
    {
     "expr": "node_persistent_storage_free{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Top 10 Shards by Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, redis_used_ram{cluster=\"$cluster\", node=\"$node\"} or redis_used_memory{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "redis:{{redis}}, bdb:{{bdb}},  role:{{role}}"
    },
    {
     "expr": "dmcproxy_process_resident_memory_bytes{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "dmcproxy"
    }
   ]
  }
 ]
}