site_name: Redis Enterprise Observability
site_description: Production-ready monitoring dashboards and alerting for Redis Enterprise
site_url: https://redis-field-engineering.github.io/redis-enterprise-observability/
repo_url: https://github.com/redis-field-engineering/redis-enterprise-observability
repo_name: redis-field-engineering/redis-enterprise-observability

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - awesome-pages
  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/overview.md
    - Quick Start: getting-started/quick-start.md
    - Prerequisites: getting-started/prerequisites.md
  - Platforms:
    - Grafana:
      - Overview: platforms/grafana/index.md
      - Installation: platforms/grafana/installation.md
      - Dashboards: platforms/grafana/dashboards.md
      - Infinity Plugin: platforms/grafana/infinity-plugin.md
    - Prometheus:
      - Overview: platforms/prometheus/index.md
      - Configuration: platforms/prometheus/configuration.md
      - Alert Rules: platforms/prometheus/alerts.md
    - Dynatrace: platforms/dynatrace/index.md
    - New Relic: platforms/newrelic/index.md
    - Splunk: platforms/splunk/index.md
    - Kibana: platforms/kibana/index.md
  - Dashboards:
    - Catalog: dashboards/catalog.md
    - Importing: dashboards/importing.md
    - Customizing: dashboards/customizing.md
  - Guides:
    - Monitor Redis Cloud: guides/redis-cloud.md
    - Setup Alerting: guides/alerting.md
    - Troubleshooting: guides/troubleshooting.md
  - Reference:
    - Metrics: reference/metrics.md
    - API Endpoints: reference/api.md
    - Compatibility: reference/compatibility.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/redis-field-engineering/redis-enterprise-observability
    - icon: fontawesome/brands/slack
      link: https://redis.slack.com/archives/C03NJNWS6E5