{
 "title": "Cluster Dashboard v2",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(endpoint_client_connections,cluster)"
    }
   },
   {
    "name": "status",
    "query": {
     "query": "label_values(bdb_status{bdb=\"$bdb\", cluster=\"$cluster\"}, status)"
    }
   },
   {
    "name": "newStatus",
    "query": {
     "query": "label_values(bdb_up{bdb=\"$bdb\", cluster=\"$cluster\"}, status)"
    }
   },
   {
    "name": "aggregation",
    "label": "aggregation interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "db",
    "query": {
     "query": "label_values(redis_server_up,db)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_server_up{cluster=\"$cluster\", role=\"master\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_server_used_memory{cluster=\"$cluster\", role=\"master\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_server_total_connections_received{cluster=\"$cluster\", role=\"master\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$db",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "db",
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(redis_server_used_memory{cluster=\"$cluster\", db=\"$db\", role=\"master\"}/redis_server_max_process_mem{cluster=\"$cluster\", db=\"$db\", role=\"master\"})"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B + $C) / 2", "type": "math" }
   ]
  },
  {
   "title": "Total Operations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(irate(endpoint_total_req[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Expiration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_server_expired_keys{cluster=\"$cluster\", db=\"$db\", role=\"master\"})"
    }
   ]
  },
  {
   "title": "Key Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_server_db0_keys{cluster=\"$cluster\", db=\"$db\", role=\"master\"})"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_server_connected_clients{cluster=\"$cluster\", db=\"$db\", role=\"master\"})"
    }
   ]
  }
 ]
}