{
 "title": "Systems & Security v2",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(endpoint_client_connections,cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Client Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "endpoint_client_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed Password Authenticaion",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint_failed_user_password_authentication",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LDAP Failed Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint_failed_ldap_authentication",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful CBA Authentications",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint_successful_cba_authentication",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful LDAP Authentication",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint_successful_ldap_authentication",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Password Successes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint_successful_user_password_authentication",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Expired Client Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint_client_connection_expired",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Establishment Failures",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint_client_establishment_failures",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LDAP Client Disconnections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint_disconnected_ldap_client",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed CBA Authentication",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint_failed_cba_authentication",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed LDAP Authentication",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint_failed_ldap_authentication",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Password Failures",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint_failed_user_password_authentication",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Certificates & Systems", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Certificate Expiration",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "x509_cert_expires_in_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node Hardware Information",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    { "expr": "node_dmi_info", "legendFormat": "__auto" }
   ]
  }
 ]
}