{
 "title": "Active-Active Lag",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "crdt_guid", "query": { "query": "label_values(crdt_guid)" } },
   { "name": "crdt_replica_id", "query": { "query": "label_values(crdt_replica_id)" } }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DBs Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(\n  redis_server_crdt_oom_latch{crdt_guid=\"$crdt_guid\"}\n) by (cluster, db, crdt_replica_id)\n* on (cluster, db) group_left(db_name, db_port, db_version)\n  db_config\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncer status",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "database_syncer_current_status{crdt_guid=\"$crdt_guid\",crdt_replica_id=~\"$crdt_replica_id\"}",
     "legendFormat": "Syncer {{src_id}} -> {{crdt_replica_id}}"
    }
   ]
  },
  { "title": "Lag Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Source -> Target lag in time per shard",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "database_syncer_dst_lag{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"}",
     "legendFormat": "R{{source_id}}:({{hash_slots}}) -> R{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "Source -> Target lag in time (Last)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (source_id, crdt_replica_id) (database_syncer_dst_lag{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"})",
     "legendFormat": "R{{source_id}} -> R{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "Total lag in bytes per shard",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "((database_syncer_dst_repl_offset{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"} and database_syncer_src_repl_offset{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"} < database_syncer_dst_repl_offset{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"}) or database_syncer_dst_repl_offset{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"}) - database_syncer_src_repl_offset{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"}",
     "legendFormat": "R{{source_id}}: ({{hash_slots}}) -> R{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "Total lag in bytes (Last)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (crdt_replica_id, source_id) (((database_syncer_dst_repl_offset{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"} and database_syncer_dst_repl_offset{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"} < database_syncer_src_repl_offset{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"}) or database_syncer_src_repl_offset{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"}) - database_syncer_dst_repl_offset{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"})",
     "legendFormat": "R{{source_id}} -> R{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "Peer backlog status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(redis_server_crdt_backlog_master_offset{crdt_guid=\"$crdt_guid\"} - on(crdt_replica_id, redis) group_right redis_server_crdt_peer_offset{crdt_guid=\"$crdt_guid\", dst_id=~\"$crdt_replica_id\"}) / on(crdt_replica_id, redis) group_left redis_server_crdt_backlog_size{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "R{{crdt_replica_id}}:shard {{redis}}:({{slots}}) -> R{{dst_id}}"
    }
   ]
  },
  {
   "title": "Source -> Syncer lag in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "((database_syncer_syncer_repl_offset{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"} and database_syncer_src_repl_offset{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"} < database_syncer_syncer_repl_offset{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"}) or database_syncer_src_repl_offset{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"}) - database_syncer_syncer_repl_offset{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"}",
     "legendFormat": "R{{source_id}}:({{hash_slots}}) -> R{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "Syncer -> Target lag in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "database_syncer_syncer_repl_offset{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"} - database_syncer_dst_repl_offset{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"}",
     "legendFormat": "R{{source_id}}:({{hash_slots}}) -> R{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "Target pipeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "targets": [
    {
     "expr": "database_syncer_total_requests{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"} - database_syncer_total_responses{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"}",
     "legendFormat": "R{{source_id}}:({{hash_slots}}) -> R{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "Total ingress bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "database_syncer_ingress_bytes{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"}",
     "legendFormat": "R{{src_id}} -> R{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "Total ingress bytes decompressed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "database_syncer_ingress_bytes_decompressed{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"}",
     "legendFormat": "R{{src_id}} -> R{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "Ingress bytes per shard",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(database_syncer_ingress_bytes{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"}[$__interval])",
     "legendFormat": "R{{source_id}}:({{hash_slots}}) -> R{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "Ingress bytes decompressed per shard",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(database_syncer_ingress_bytes_decompressed{crdt_guid=\"$crdt_guid\", crdt_replica_id=~\"$crdt_replica_id\"}[$__interval])",
     "legendFormat": "R{{source_id}}:({{hash_slots}}) -> R{{crdt_replica_id}}"
    }
   ]
  }
 ]
}