{
 "title": "Cluster Node Latency",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_metrics_up,cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_metrics{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(node_config{cluster=\"$cluster\",node=\"$node\"}, cnm_version)"
    }
   },
   {
    "name": "aggregation",
    "label": "interval aggregation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Read/Write Latency on Node $node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "percents" }
   ],
   "targets": [
    {
     "expr": "bdb_avg_read_latency{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "read"
    },
    {
     "expr": " bdb_avg_write_latency{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Listener Latency",
   "type": "timeseries",
   "description": "display the egress and ingress traffic on the node's NIC",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s", "label": "Egress bytes/sec " }
   ],
   "targets": [
    {
     "expr": "listener_acc_read_latency{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "listener read latency node {{node}}"
    },
    {
     "expr": "listener_acc_write_latency{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "listener write latency for node {{node}}"
    },
    {
     "expr": "listener_acc_other_latency{cluster=\"$cluster\", node=\"$node\"} ",
     "legendFormat": "listener other latency for node {{node}}"
    }
   ]
  },
  {
   "title": "Cache Hits/Misses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bdb_read_hits{node=\"$node\",cluster=\"$cluster\"}",
     "legendFormat": "active / allocated (defraggable)"
    },
    {
     "expr": "bdb_read_misses{node=\"$node\",cluster=\"$cluster\"}",
     "legendFormat": "resident / active (purgable)"
    },
    {
     "expr": "bdb_write_hits{node=\"$node\",cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bdb_write_misses{node=\"$node\",cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Expired/Evicted Objects",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "bdb_expired_objects{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "expired"
    },
    {
     "expr": "bdb_evicted_objects{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "evicted"
    }
   ]
  }
 ]
}