{
 "title": "Proxy Threads",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(namedprocess_namegroup_cpu_seconds_total, cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\"},node)"
    }
   },
   {
    "name": "aggregation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Node $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Proxy CPU Usage (avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Proxy Worker Threads",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(namedprocess_namegroup_thread_cpu_seconds_total{threadname=~\"worker-.*\", mode=\"system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node)(namedprocess_namegroup_open_filedesc{cluster=\"$cluster\",node=\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Threads - Workers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_thread_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\", mode=\"system\", threadname=~\"worker.*\"}[$aggregation])",
     "legendFormat": "{{threadname}}-system"
    },
    {
     "expr": "rate(namedprocess_namegroup_thread_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\", mode=\"user\", threadname=~\"worker.*\"}[$aggregation])",
     "legendFormat": "{{threadname}}-{{mode}}"
    }
   ]
  },
  {
   "title": "Proxy Threads - Core",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_thread_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\", mode=\"system\", threadname!~\"cli.*|worker.*|listener.*\"}[$aggregation])",
     "legendFormat": "{{threadname}}-{{mode}}"
    },
    {
     "expr": "rate(namedprocess_namegroup_thread_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\", mode=\"user\", threadname!~\"cli.*|worker.*|listener.*\"}[$aggregation])",
     "legendFormat": "{{threadname}}-{{mode}}"
    }
   ]
  }
 ]
}