{
 "title": "Node Dashboard (Classic)",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "label_values(node_up,cluster)" },
   {
    "name": "node",
    "query": "label_values(node_up{cluster=\"$cluster\"}, node)"
   },
   {
    "name": "version",
    "query": "label_values(node_up{cluster=\"$cluster\",node=\"$node\"}, cnm_version)"
   },
   {
    "name": "aggregation",
    "label": "interval aggregation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "# Databases",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(redis_used_memory{cluster=\"$cluster\", node=\"$node\"}) by (bdb))"
    }
   ]
  },
  {
   "title": "# Master Shards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_used_memory{cluster=\"$cluster\", node=\"$node\", role=\"master\"})"
    }
   ]
  },
  {
   "title": "# Slave Shards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_used_memory{cluster=\"$cluster\", node=\"$node\", role=\"slave\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_cpu_system{node=\"$node\",cluster=\"$cluster\"} + node_cpu_user{node=\"$node\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_available_memory{cluster=\"$cluster\",node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Node version",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": {
    "content": "<b style=\"font-size: 20pt\">$version<b>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Usage on node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit", "label": "percents" }
   ],
   "targets": [
    {
     "expr": " node_cpu_user{cluster=\"$cluster\", node=\"$node\"} + node_cpu_system{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "user+system"
    },
    {
     "expr": "1- node_cpu_idle{cluster=\"$cluster\", node=\"$node\"} - node_cpu_system{cluster=\"$cluster\", node=\"$node\"} - node_cpu_user{cluster=\"$cluster\", node=\"$node\"} unless node_cpu_nice{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "other"
    },
    {
     "expr": "node_cpu_steal{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "steal"
    },
    {
     "expr": "node_cpu_nice{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "nice"
    },
    {
     "expr": "node_cpu_irqs{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "irqs"
    },
    {
     "expr": "dmcproxy_process_cpu_usage_percent{cluster=\"$cluster\", node=\"$node\"}/100",
     "legendFormat": "dmcproxy (100% = 1 core)"
    },
    {
     "expr": " node_cpu_iowait{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(redis_process_cpu_usage_percent{cluster=\"$cluster\", node=\"$node\"}/100)",
     "legendFormat": "shards (100% = 1 core)"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node $node In/Out Traffic",
   "type": "graph",
   "description": "display the egress and ingress traffic on the node's NIC",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps", "label": "Egress bytes/sec " }
   ],
   "targets": [
    {
     "expr": "node_ingress_bytes{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "Ingress for node {{node}}"
    },
    {
     "expr": "node_egress_bytes{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "egress for node {{node}}"
    }
   ]
  },
  {
   "title": "Node $node req/sec",
   "type": "graph",
   "description": "display the egress and ingress traffic on the node's NIC",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Egress bytes/sec " }
   ],
   "targets": [
    {
     "expr": "node_total_req{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "Total requests for node {{node}}"
    }
   ]
  },
  {
   "title": "Listener",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 10 listeners Egress/Ingrees",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10, listener_egress_bytes{node=\"$node\", cluster=\"$cluster\"})",
     "legendFormat": "Egress listener {{proxy}} for {{bdb}}"
    },
    {
     "expr": "topk(10, listener_ingress_bytes{node=\"$node\", cluster=\"$cluster\"})",
     "legendFormat": "Ingress listener {{proxy}} for {{bdb}}"
    }
   ]
  },
  {
   "title": "Avg listener latency for node:$node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, listener_acc_latency{node=\"$node\", cluster=\"$cluster\"} / listener_total_started_res{node=\"$node\", cluster=\"$cluster\"})",
     "legendFormat": "listener {{proxy}}  bdb {{bdb}}"
    }
   ]
  },
  {
   "title": "BIGSTORE IOPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 10 shards by used ram",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, redis_used_ram{cluster=\"$cluster\", node=\"$node\"} or redis_used_memory{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "redis:{{redis}}, bdb:{{bdb}},  role:{{role}}"
    },
    {
     "expr": "dmcproxy_process_resident_memory_bytes{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "proxy"
    }
   ]
  },
  {
   "title": "Size of shards on node (Ability for sorting like by size)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_used_memory{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "redis:{{redis}}, bdb:{{bdb}},  role:{{role}}"
    }
   ]
  },
  {
   "title": "Listeners",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 10 active listeners by connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, listener_conns{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "listener {{proxy}} for  bdb {{bdb}}"
    }
   ]
  },
  {
   "title": "Top 10 active listeners by requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(10, listener_total_req{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "listener {{proxy}} for  bdb {{bdb}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "#Shards per database",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(redis_used_memory{cluster=\"$cluster\", node=\"$node\"}) by (bdb)",
     "legendFormat": "bdb:{{bdb}}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_available_memory{cluster=\"$cluster\",node=\"$node\"}",
     "legendFormat": "available memory"
    }
   ]
  },
  {
   "title": "Total shard memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(redis_used_memory{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "total shards memory"
    },
    {
     "expr": "sum(redis_used_ram{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "total shards ram"
    }
   ]
  },
  {
   "title": "Fragmentation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(redis_allocator_active{node=\"$node\",cluster=\"$cluster\"} / redis_allocator_allocated{node=\"$node\",cluster=\"$cluster\"}) - 1",
     "legendFormat": "active / allocated (defraggable)"
    },
    {
     "expr": "avg(redis_allocator_resident{node=\"$node\",cluster=\"$cluster\"} / redis_allocator_active{node=\"$node\",cluster=\"$cluster\"}) - 1",
     "legendFormat": "resident / active (purgable)"
    },
    {
     "expr": "sum(redis_allocator_active{node=\"$node\",cluster=\"$cluster\"} - redis_allocator_allocated{node=\"$node\",cluster=\"$cluster\"})",
     "legendFormat": "active - allocated (defraggable)"
    },
    {
     "expr": "sum(redis_allocator_resident{node=\"$node\",cluster=\"$cluster\"} - redis_allocator_active{node=\"$node\",cluster=\"$cluster\"})",
     "legendFormat": "resident - active (purgable)"
    },
    {
     "expr": "avg(redis_active_defrag_running{node=\"$node\",cluster=\"$cluster\"})/100",
     "legendFormat": "active defrag running"
    },
    {
     "expr": "sum(redis_process_resident_memory_bytes{node=\"$node\",cluster=\"$cluster\"}) - sum(redis_allocator_resident{node=\"$node\",cluster=\"$cluster\"})",
     "legendFormat": "process rss - allocator rss"
    },
    {
     "expr": "sum(redis_process_resident_memory_bytes{node=\"$node\",cluster=\"$cluster\"}) / sum(redis_allocator_resident{node=\"$node\",cluster=\"$cluster\"})",
     "legendFormat": "process rss / allocator rss"
    }
   ]
  },
  {
   "title": "CPU Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Shard's CPU on Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(delta(redis_process_cpu_system_seconds_total{node=\"$node\",cluster=\"$cluster\"}[60s]) + delta(redis_process_cpu_user_seconds_total{node=\"$node\",cluster=\"$cluster\"}[60s]))/60*100",
     "legendFormat": "shard: {{redis}} role: {{role}} bdb: {{bdb}}"
    }
   ]
  },
  {
   "title": "Proxy CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(dmcproxy_process_cpu_user_seconds_total{cluster=\"$cluster\", node=\"$node\"}[$aggregation])",
     "legendFormat": "CPU User"
    },
    {
     "expr": "rate(dmcproxy_process_cpu_system_seconds_total{cluster=\"$cluster\", node=\"$node\"}[$aggregation])",
     "legendFormat": "CPU System"
    }
   ]
  },
  {
   "title": "Fork memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_rdb_last_cow_size{node=\"$node\",cluster=\"$cluster\"}",
     "legendFormat": "shard last RDB cow - redis: {{redis}}"
    },
    {
     "expr": "redis_aof_last_cow_size{node=\"$node\",cluster=\"$cluster\"}",
     "legendFormat": "shard last AOF cow - redis: {{redis}}"
    },
    {
     "expr": "redis_mem_aof_buffer{node=\"$node\",cluster=\"$cluster\"}",
     "legendFormat": "shard aofrw buffers - redis: {{redis}}"
    },
    {
     "expr": "redis_mem_clients_slaves{node=\"$node\",cluster=\"$cluster\"}",
     "legendFormat": "shard salve buffers - redis: {{redis}}"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "redis_rdb_bgsave_in_progress{cluster=\"$cluster\", node=\"$node\"} !=0",
     "legendFormat": "BGSAVE {{redis}} bdb {{bdb}}"
    },
    {
     "expr": "redis_aof_rewrite_in_progress{cluster=\"$cluster\", node=\"$node\"}!=0",
     "legendFormat": "AOFRW {{redis}} bdb {{bdb}}"
    }
   ]
  },
  {
   "title": "Shard AOF Rewrites / $aggregation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(redis_aof_rewrites{cluster=\"$cluster\", node=\"$node\"}[$aggregation]) !=0",
     "legendFormat": "Redis {{redis}} bdb {{bdb}}"
    }
   ]
  },
  {
   "title": "Delayed fsync - (events / $aggregation)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(delta(redis_aof_delayed_fsync{node=\"$node\",cluster=\"$cluster\"}[$aggregation]))",
     "legendFormat": "delayed fsync"
    }
   ]
  },
  {
   "title": "ROF metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Node BIGSTORE throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 98 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_flash_write_throughput{cluster=\"$cluster\", node=\"$node\"}",
       "legendFormat": "node_flash_write_throughput on node:{{node}}"
      },
      {
       "expr": "node_flash_read_throughput{cluster=\"$cluster\", node=\"$node\"}",
       "legendFormat": "node_flash_read_throughput on node:{{node}}"
      }
     ]
    },
    {
     "title": "Node BIGSTORE IOPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 98 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_flash_read_iops{cluster=\"$cluster\", node=\"$node\"}",
       "legendFormat": "node_flash_read_iops on node:{{node}}"
      },
      {
       "expr": "node_flash_write_iops{cluster=\"$cluster\", node=\"$node\"}",
       "legendFormat": "node_flash_write_iops on node:{{node}}"
      }
     ]
    },
    {
     "title": "Node BIGSTORE wait time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 98 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "node_flash_write_time{cluster=\"$cluster\", node=\"$node\"} / 1000",
       "legendFormat": "node_flash_write_time on node:{{node}}"
      },
      {
       "expr": " node_flash_read_time {cluster=\"$cluster\", node=\"$node\"} / 1000",
       "legendFormat": "node_flash_read_time  on node:{{node}}"
      }
     ]
    },
    {
     "title": "Node BIGSTORE KV",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 98 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_bigstore_kv_ops{cluster=\"$cluster\", node=\"$node\"}",
       "legendFormat": "node_bigstore_kv_ops on node:{{node}}"
      }
     ]
    },
    {
     "title": "Node used flash",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 105 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(redis_used_disk{cluster=\"$cluster\", node=\"$node\"})",
       "legendFormat": "total used flash"
      },
      {
       "expr": "sum(redis_disk_allocation{cluster=\"$cluster\", node=\"$node\"})",
       "legendFormat": "total flash allocation"
      }
     ]
    }
   ]
  }
 ]
}