{
 "title": "Active-Active",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(bdb_up,cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "CRDT Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bdb_crdt_syncer_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CRDT Ingress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "bdb_crdt_syncer_ingress_bytes", "legendFormat": "{{bdb_name}}" }
   ]
  },
  {
   "title": "CRDT Egress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "bdb_crdt_syncer_egress_bytes", "legendFormat": "{{bdb_name}}" }
   ]
  },
  {
   "title": "CRDT Raw DB Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_crdt_raw_dbsize{role=\"master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CRDT Lag Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_crdt_peer_lag", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CRDT Ingress (Decompressed)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bdb_crdt_syncer_ingress_bytes_decompressed{crdt_replica_id=\"1\"}",
     "legendFormat": "{{bdb_name}}"
    }
   ]
  },
  {
   "title": "CRDT Egress (Decompressed)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bdb_crdt_syncer_egress_bytes_decompressed",
     "legendFormat": "{{bdb_name}}"
    }
   ]
  },
  {
   "title": "CRDT Max Pending Writes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bdb_crdt_syncer_pending_local_writes_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CRDT Backlog",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_crdt_backlog_histlen{role=\"master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Sync Lag Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "bdb_crdt_syncer_local_ingress_lag_time",
     "legendFormat": "{{bdb_name}}"
    }
   ]
  },
  {
   "title": "Ingress Sync Lag Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_crdt_merge_reqs{role=\"slave\"}",
     "legendFormat": "{{bdb_name}}"
    }
   ]
  },
  {
   "title": "CRDT Pending GC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_crdt_gc_collected{role=\"master\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}