{
 "title": "Active-Active v2",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(endpoint_client_connections,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "database_syncer_current_status{syncer_type=\"crdt\", source_id=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "database_syncer_ingress_bytes{cluster=\"$cluster\"}",
     "legendFormat": "{{crdt_guid}}"
    }
   ]
  },
  {
   "title": "Raw DB Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "database_syncer_rdb_size{shard_index=\"1\",source_id=\"1\",syncer_type=\"crdt\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lag Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "database_syncer_dst_lag{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress (Decompressed)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "database_syncer_ingress_bytes_decompressed{cluster=\"$cluster\"}",
     "legendFormat": "{{crdt_guid}}"
    }
   ]
  },
  {
   "title": "Pending Writes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "database_syncer_flush_counter{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Source Offset",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "database_syncer_src_repl_offset",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Sync Lag Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "database_syncer_lag_ms{cluster=\"$cluster\", source_id=\"1\"}",
     "legendFormat": "{{bdb_name}}"
    }
   ]
  },
  {
   "title": "Destination Offset",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "database_syncer_dst_repl_offset",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}