{
 "title": "Workflow Cluster Proxy Network",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(bdb_conns,cluster)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_conns{cluster=\"$cluster\"},node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node: $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Proxy CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dmcproxy_process_cpu_usage_percent{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dmcproxy_process_open_fds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Proxy Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dmcproxy_process_resident_memory_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Listener Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "listener_conns{cluster=\"$cluster\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Listener Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "listener_read_req{cluster=\"$cluster\"}",
     "legendFormat": "{{endpoint}} - read"
    },
    { "expr": "listener_write_req", "legendFormat": "{{endpoint}} - write" },
    { "expr": "listener_other_req", "legendFormat": "{{endpoint}} - other" }
   ]
  },
  {
   "title": "Listener Responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "listener_read_res{cluster=\"$cluster\"}",
     "legendFormat": "{{endpoint}} - read"
    },
    { "expr": "listener_write_res", "legendFormat": "{{endpoint}} - write" },
    { "expr": "listener_other_res", "legendFormat": "{{endpoint}} - other" }
   ]
  }
 ]
}