{
 "title": "Workflow Cluster Proxy Threads",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "node", "query": { "query": "label_values(node_up,node)" } },
   {
    "name": "aggregation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "DMC Proxy Threads - Workers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_thread_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\", mode=\"system\", threadname=~\"worker.*\"}[$aggregation])",
     "legendFormat": "{{threadname}}-{{mode}}"
    },
    {
     "expr": "rate(namedprocess_namegroup_thread_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\", mode=\"user\", threadname=~\"worker.*\"}[$aggregation])",
     "legendFormat": "{{threadname}}-{{mode}}"
    }
   ]
  },
  {
   "title": "DMC Proxy Threads - Core",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_thread_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\", mode=\"system\", threadname!~\"cli.*|worker.*|listener.*\"}[$aggregation])",
     "legendFormat": "{{threadname}}-{{mode}}"
    }
   ]
  },
  {
   "title": "DMC Proxy Threads - Listener",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_thread_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\", mode=\"system\", threadname=~\"listener*\"}[$aggregation])",
     "legendFormat": "{{threadname}} - {{mode}}"
    },
    {
     "expr": "rate(namedprocess_namegroup_thread_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\", threadname=~\"listener*\", mode=\"user\"}[$aggregation])",
     "legendFormat": "{{threadname}} - {{mode}}"
    }
   ]
  },
  {
   "title": "DMC Proxy Threads - CLI Session",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_thread_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\", threadname=~\"cli_session.*\", mode=\"system\"}[$aggregation])",
     "legendFormat": "{{threadname}} - {{mode}}"
    }
   ]
  }
 ]
}