{
 "title": "RediSearch QPS dashboard 2",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "db",
    "label": "database id",
    "query": {
     "query": "label_values({cluster=\"$cluster\"}, db)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of indexes",
   "type": "stat",
   "description": "Number of indexes in each shard. Expected to be equal across all shards",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_server_search_number_of_indexes{cluster=\"$cluster\", db=\"$db\"}",
     "legendFormat": "redis:{{redis}}"
    }
   ]
  },
  {
   "title": "Fields count",
   "type": "timeseries",
   "description": "The total number of <field> across all indexes in the db.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "max(redis_server_search_fields_text_Text{cluster=\"$cluster\", db=\"$db\"}) or vector(0)",
     "legendFormat": "TEXT"
    },
    {
     "expr": "max(redis_server_search_fields_tag_Tag{cluster=\"$cluster\", db=\"$db\"}) or vector(0)",
     "legendFormat": "TAG"
    },
    {
     "expr": "max(redis_server_search_fields_numeric_Numeric{cluster=\"$cluster\", db=\"$db\"}) or vector(0)",
     "legendFormat": "NUMERIC"
    },
    {
     "expr": "max(redis_server_search_fields_geo_Geo{cluster=\"$cluster\", db=\"$db\"}) or vector(0)",
     "legendFormat": "GEO"
    },
    {
     "expr": "max(redis_server_search_fields_geoshape_Geoshape{cluster=\"$cluster\", db=\"$db\"}) or vector(0)",
     "legendFormat": "GEOSHAPE"
    },
    {
     "expr": "max(redis_server_search_fields_vector_Vector{cluster=\"$cluster\", db=\"$db\"}) or vector(0)",
     "legendFormat": "VECTOR"
    }
   ]
  },
  { "title": "Current state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Active indexes",
   "type": "timeseries",
   "description": "The total number of indexes running a background indexing and/or background query processing operation.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "redis_server_search_number_of_active_indexes{cluster=\"$cluster\", db=\"$db\"}",
     "legendFormat": "redis:{{redis}}"
    }
   ]
  },
  {
   "title": "Active indexes running queries",
   "type": "timeseries",
   "description": "Total count of indexes currently running a background query process. ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "redis_server_search_number_of_active_indexes_running_queries{cluster=\"$cluster\", db=\"$db\"}",
     "legendFormat": "redis:{{redis}}"
    }
   ]
  },
  {
   "title": "Active indexes indexing",
   "type": "timeseries",
   "description": "Total count of indexes currently undergoing a background indexing process.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "redis_server_search_number_of_active_indexes_indexing{cluster=\"$cluster\", db=\"$db\"}",
     "legendFormat": "redis:{{redis}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total Indexes memory",
   "type": "timeseries",
   "description": "The memory allocated by all indexes in the bdb",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(sum by(db) (redis_server_search_used_memory_indexes{cluster=\"$cluster\", db=\"$db\"})) / (1024 * 1024)",
     "legendFormat": "bdb:{{db}}"
    },
    {
     "expr": "redis_server_search_used_memory_indexes{cluster=\"$cluster\", db=\"$db\"} / (1024 * 1024)",
     "legendFormat": "redis:{{redis}}"
    }
   ]
  },
  {
   "title": "Max memory index",
   "type": "timeseries",
   "description": "The memory usage of the index with the largest memory usage in the shard",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "redis_server_search_largest_memory_index{cluster=\"$cluster\", db=\"$db\"} / (1024 * 1024)",
     "legendFormat": "redis:{{redis}}"
    }
   ]
  },
  {
   "title": "Average memory per index",
   "type": "timeseries",
   "description": "The average memory usage of the indexes in the db",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(redis_server_search_used_memory_indexes{cluster=\"$cluster\", db=\"$db\"} / redis_server_search_number_of_indexes{cluster=\"$cluster\", db=\"$db\"}) / (1024 * 1024)",
     "legendFormat": "redis:{{redis}}"
    }
   ]
  },
  { "title": "Indexing performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Total indexing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "redis_server_search_total_indexing_time{cluster=\"$cluster\", db=\"$db\"}",
     "legendFormat": "redis:{{redis}}"
    }
   ]
  },
  {
   "title": "Indexing time rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(redis_server_search_total_indexing_time{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])",
     "legendFormat": "redis:{{redis}}"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Active queries",
   "type": "timeseries",
   "description": "The total number of background queries currently being executed.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by(db) (redis_server_search_total_active_queries{cluster=\"$cluster\", db=\"$db\"})",
     "legendFormat": "db:{{db}}"
    },
    {
     "expr": "(redis_server_search_total_active_queries{cluster=\"$cluster\", db=\"$db\"})",
     "legendFormat": "redis:{{redis}}"
    }
   ]
  },
  {
   "title": "Processed queries server latency",
   "type": "timeseries",
   "description": "Processed Queries Latency (When using cursors, not counting reading from existing cursors)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum by(db) (rate(redis_server_search_total_query_execution_time_ms{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])) / sum by(db) (rate(redis_server_search_total_queries_processed{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])))",
     "legendFormat": "db:{{db}}"
    },
    {
     "expr": "((rate(redis_server_search_total_query_execution_time_ms{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])) / (rate(redis_server_search_total_queries_processed{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])))",
     "legendFormat": "redis:{{redis}}"
    }
   ]
  },
  {
   "title": "Query commands server latency",
   "type": "timeseries",
   "description": "Query Commands Latency (including FT.SEARCH, FT.AGGREGATE, and FT.CURSOR READ).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum by(db) (rate(redis_server_search_total_query_execution_time_ms{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])) / sum by(db) (rate(redis_server_search_total_query_commands{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])))",
     "legendFormat": "db:{{db}}"
    },
    {
     "expr": "((rate(redis_server_search_total_query_execution_time_ms{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])) /(rate(redis_server_search_total_query_commands{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])))",
     "legendFormat": "redis:{{redis}}"
    }
   ]
  },
  {
   "title": "QPS (processed queries)",
   "type": "timeseries",
   "description": "server throughput for processed query (When using cursors, not counting reading from existing cursors)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum by(db) (rate(redis_server_search_total_queries_processed{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]))",
     "legendFormat": "db:{{db}}"
    },
    {
     "expr": "(rate(redis_server_search_total_queries_processed{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]))",
     "legendFormat": "redis:{{redis}}"
    }
   ]
  },
  {
   "title": "QPS (query commands)",
   "type": "timeseries",
   "description": "server throughput for all query commands (including FT.SEARCH, FT.AGGREGATE, and FT.CURSOR READ).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum by(db) (rate(redis_server_search_total_query_commands{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]))",
     "legendFormat": "db:{{db}}"
    },
    {
     "expr": "(rate(redis_server_search_total_query_commands{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]))",
     "legendFormat": "redis:{{redis}}"
    }
   ]
  },
  { "title": "Cursors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Total cursors",
   "type": "timeseries",
   "description": "The total number of user and internal cursors, either holding pending results or actively executing FT.CURSOR READ.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(db) (redis_server_search_global_total{cluster=\"$cluster\", db=\"$db\"})",
     "legendFormat": "db:{{db}}"
    },
    {
     "expr": "redis_server_search_global_total{cluster=\"$cluster\", db=\"$db\"}",
     "legendFormat": "redis:{{redis}}"
    }
   ]
  },
  {
   "title": "Idle cursors",
   "type": "timeseries",
   "description": "The total number of user and internal cursors currently holding pending results.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_server_search_global_idle{cluster=\"$cluster\", db=\"$db\"}",
     "legendFormat": "redis:{{redis}}"
    },
    {
     "expr": "sum by(db) (redis_server_search_global_total{cluster=\"$cluster\", db=\"$db\"})",
     "legendFormat": "db:{{db}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Indexing failures",
   "type": "timeseries",
   "description": "The total number of indexing failures recorded across all indexes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "redis_server_search_errors_indexing_failures{cluster=\"$cluster\", db=\"$db\"}",
     "legendFormat": "redis:{{redis}}"
    },
    {
     "expr": "sum by(db) (redis_server_search_errors_indexing_failures{cluster=\"$cluster\", db=\"$db\"})",
     "legendFormat": "db:{{db}}"
    }
   ]
  },
  {
   "title": "Max indexing failures",
   "type": "timeseries",
   "description": "The number of failures in the index with the maximum number of failures per shard.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "redis_server_search_errors_for_index_with_max_failures{cluster=\"$cluster\", db=\"$db\"}",
     "legendFormat": "redis:{{redis}}"
    }
   ]
  },
  {
   "title": "Per field Indexing failures",
   "type": "timeseries",
   "description": "The total number of indexing failures caused by attempts to index a <field> field in the db.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "sum by(db) (redis_server_search_fields_text_IndexErrors{cluster=\"$cluster\", db=\"$db\"})",
     "legendFormat": "TEXT"
    },
    {
     "expr": "sum by(db) (redis_server_search_fields_tag_IndexErrors{cluster=\"$cluster\", db=\"$db\"})",
     "legendFormat": "TAG"
    },
    {
     "expr": "sum by(db) (redis_server_search_fields_numeric_IndexErrors{cluster=\"$cluster\", db=\"$db\"})",
     "legendFormat": "NUMERIC"
    },
    {
     "expr": "sum by(db) (redis_server_search_fields_geo_IndexErrors{cluster=\"$cluster\", db=\"$db\"})",
     "legendFormat": "GEO"
    },
    {
     "expr": "sum by(db) (redis_server_search_fields_geoshape_IndexErrors{cluster=\"$cluster\", db=\"$db\"})",
     "legendFormat": "GEOSHAPE"
    },
    {
     "expr": "sum by(db) (redis_server_search_fields_vector_IndexErrors{cluster=\"$cluster\", db=\"$db\"})",
     "legendFormat": "VECTOR"
    }
   ]
  },
  { "title": "Garbage collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Total memory collected",
   "type": "timeseries",
   "description": "The total amount of memory freed by the garbage collectors from indexes.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "redis_server_search_bytes_collected{cluster=\"$cluster\", db=\"$db\"} / (1024*1024)",
     "legendFormat": "redis:{{redis}}"
    },
    {
     "expr": "(sum by(db) (redis_server_search_bytes_collected{cluster=\"$cluster\", db=\"$db\"}))/ (1024*1024)",
     "legendFormat": "db:{{db}}"
    }
   ]
  },
  {
   "title": "Average memory collected / cycle ",
   "type": "timeseries",
   "description": "The average amount of memory reclaimed by the garbage collector during each cycle.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(redis_server_search_bytes_collected{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) / rate(redis_server_search_total_cycles{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])\n",
     "legendFormat": "redis:{{redis}}"
    }
   ]
  },
  {
   "title": "Average gc cycle duration",
   "type": "timeseries",
   "description": "The average cycle duration of all GC's in each shard",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(redis_server_search_total_ms_run{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) / rate(redis_server_search_total_cycles{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])\n",
     "legendFormat": "redis:{{redis}}"
    }
   ]
  },
  {
   "title": "Total marked deleted docs",
   "type": "timeseries",
   "description": "The number of documents marked as deleted whose memory has not yet been freed by the garbage collector.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_server_search_total_docs_not_collected_by_gc{cluster=\"$cluster\", db=\"$db\"}",
     "legendFormat": "redis:{{redis}}"
    },
    {
     "expr": "sum by(db) (redis_server_search_total_docs_not_collected_by_gc{cluster=\"$cluster\", db=\"$db\"})",
     "legendFormat": "db:{{db}}"
    }
   ]
  },
  {
   "title": "Total marked deleted vectors",
   "type": "timeseries",
   "description": "The number of vectors marked as deleted in the vector indexes that have not yet been cleaned.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_server_search_marked_deleted_vectors{cluster=\"$cluster\", db=\"$db\"}",
     "legendFormat": "redis:{{redis}}"
    },
    {
     "expr": "sum by(db) (redis_server_search_marked_deleted_vectors{cluster=\"$cluster\", db=\"$db\"})",
     "legendFormat": "db:{{db}}"
    }
   ]
  },
  { "title": "Fields Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Sortable fields count",
   "type": "timeseries",
   "description": "The total number of <field> with sortable attributes across all indexes in the db.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "max(redis_server_search_fields_text_Sortable{cluster=\"$cluster\", db=\"$db\"}) or vector(0)\n",
     "legendFormat": "TEXT"
    },
    {
     "expr": "max(redis_server_search_fields_tag_Sortable{cluster=\"$cluster\", db=\"$db\"}) or vector(0)",
     "legendFormat": "TAG"
    },
    {
     "expr": "max(redis_server_search_fields_numeric_Sortable{cluster=\"$cluster\", db=\"$db\"}) or vector(0)",
     "legendFormat": "NUMERIC"
    },
    {
     "expr": "max(redis_server_search_fields_geo_Sortable{cluster=\"$cluster\", db=\"$db\"}) or vector(0)",
     "legendFormat": "GEO"
    },
    {
     "expr": "max(redis_server_search_fields_geoshape_Sortable{cluster=\"$cluster\", db=\"$db\"}) or vector(0)",
     "legendFormat": "GEOSHAPE"
    }
   ]
  },
  {
   "title": "NoIndex fields count",
   "type": "timeseries",
   "description": "The total number of <field> with NoIndex attribute, i.e used for sorting only but not indexed, across all indexes in the db.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "max(redis_server_search_fields_text_NoIndex{cluster=\"$cluster\", db=\"$db\"}) or vector(0)\n",
     "legendFormat": "TEXT"
    },
    {
     "expr": "max(redis_server_search_fields_tag_NoIndex{cluster=\"$cluster\", db=\"$db\"}) or vector(0)",
     "legendFormat": "TAG"
    },
    {
     "expr": "max(redis_server_search_fields_numeric_NoIndex{cluster=\"$cluster\", db=\"$db\"}) or vector(0)",
     "legendFormat": "NUMERIC"
    },
    {
     "expr": "max(redis_server_search_fields_geo_NoIndex{cluster=\"$cluster\", db=\"$db\"}) or vector(0)",
     "legendFormat": "GEO"
    },
    {
     "expr": "max(redis_server_search_fields_geoshape_NoIndex{cluster=\"$cluster\", db=\"$db\"}) or vector(0)",
     "legendFormat": "GEOSHAPE"
    }
   ]
  },
  {
   "title": "Vector indexes count",
   "type": "timeseries",
   "description": "The total number of vector indexes of each algorithm across all indexes in the db.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "max(redis_server_search_fields_vector_HNSW{cluster=\"$cluster\", db=\"$db\"}) or vector(0)",
     "legendFormat": "HNSW"
    },
    {
     "expr": "max(redis_server_search_fields_vector_Flat{cluster=\"$cluster\", db=\"$db\"}) or vector(0)",
     "legendFormat": "FLAT"
    }
   ]
  },
  {
   "title": "Case sensitive fields count",
   "type": "timeseries",
   "description": "The total number of <field> with CASESENSITIVE attribute. Currently, only applicable for TAG fields.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 111 },
   "targets": [
    {
     "expr": "max(redis_server_search_fields_tag_NoIndex{cluster=\"$cluster\", db=\"$db\"}) or vector(0)",
     "legendFormat": "TAG"
    }
   ]
  }
 ]
}