{
 "title": "Active-Active",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(redis_up,cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "CRDT Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (database_syncer_current_status{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CRDT Ingress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(database_syncer_ingress_bytes{syncer_type=\"crdt\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "CRDT Egress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "bdb_crdt_syncer_egress_bytes", "legendFormat": "{{cluster}}" }
   ]
  },
  {
   "title": "CRDT Raw DB Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_server_crdt_raw_dbsize{role=\"master\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CRDT Lag Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_server_crdt_peer_lag{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CRDT Ingress (Decompressed)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(database_syncer_ingress_bytes_decompressed{cluster=\"$cluster\"}[1m])",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "CRDT Egress (Decompressed)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bdb_crdt_syncer_egress_bytes_decompressed",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "CRDT Max Pending Writes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bdb_crdt_syncer_pending_local_writes_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CRDT Backlog",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_server_crdt_backlog_histlen{role=\"master\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Sync Lag Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(cluster) (database_syncer_lag_ms{syncer_type=\"crdt\", cluster=\"$cluster\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Ingress Sync Lag Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "redis_server_crdt_merge_reqs{role=\"slave\", cluster=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "CRDT Pending GC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_server_crdt_gc_collected{role=\"master\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}