{
 "title": "Database Status Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(redis_server_up,cluster)"
    }
   },
   {
    "name": "db",
    "label": "db",
    "query": {
     "query": "label_values(endpoint_client_connections{cluster=\"$cluster\"},db)"
    }
   },
   {
    "name": "aggregation",
    "label": "aggregation interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(irate(endpoint_read_requests_latency_histogram_sum{db=\"$db\"}[1m]))/sum(irate(endpoint_read_requests{db=\"$db\"}[1m])))/1000000",
     "legendFormat": "Read"
    },
    {
     "expr": "(sum(irate(endpoint_write_requests_latency_histogram_sum{db=\"$db\"}[1m]))/sum(irate(endpoint_write_requests{db=\"$db\"}[1m])))/1000000",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster,db)(redis_server_used_memory{role=\"master\", db=\"$db\", cluster=\"$cluster\"}) / (avg by(cluster,db)(db_memory_limit_bytes{db=\"$db\", cluster=\"$cluster\"}) / max by(cluster,db)(db_replication_factor{db=\"$db\", cluster=\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Operations",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (db, cluster) (irate(endpoint_read_requests{db=\"$db\", cluster=\"$cluster\"}[1m]) + irate(endpoint_write_requests{db=\"$db\", cluster=\"$cluster\"}[1m]) + irate(endpoint_other_requests{db=\"$db\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by (db, cluster) (irate(endpoint_read_requests{db=\"$db\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (db, cluster) (irate(endpoint_write_requests{db=\"$db\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum by(db, cluster) (irate(endpoint_other_requests{db=\"$db\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "Key Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(sum by (db, cluster) (redis_server_db_keys{role=\"master\", db=\"$db\", cluster=\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Expired Keys",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (db, cluster) (irate(redis_server_expired_keys{role=\"master\", cluster=\"$cluster\", db=\"$db\"}[1m]))",
     "legendFormat": "Expired Keys"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(sum by (db, cluster) (endpoint_client_connections{cluster=\"$cluster\", db=\"$db\"} - endpoint_client_disconnections{cluster=\"$cluster\", db=\"$db\"}))"
    }
   ]
  },
  {
   "title": "Total Misses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (db, cluster) (irate(redis_server_keyspace_read_misses{role=\"master\", cluster=\"$cluster\", db=\"$db\"}[1m]))) + (sum by (db, cluster) (irate(redis_server_keyspace_write_misses{role=\"master\", cluster=\"$cluster\", db=\"$db\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(db, cluster) (irate(namedprocess_namegroup_thread_cpu_seconds_total{mode=\"system\", threadname=~\"redis-server.*\", cluster=\"$cluster\", db=\"$db\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(db, cluster) (irate(namedprocess_namegroup_thread_cpu_seconds_total{mode=\"user\", threadname=~\"redis-server.*\", db=\"$db\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}