{
 "title": "Node Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_metrics_up,cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_metrics_up{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(node_config{cluster=\"$cluster\",node=\"$node\"}, cnm_version)"
    }
   },
   {
    "name": "aggregation",
    "label": "interval aggregation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Node $node : Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Database Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(redis_server_used_memory{cluster=\"$cluster\", node=\"$node\"}) by (bdb))"
    }
   ]
  },
  {
   "title": "Master Shard Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_server_used_memory{cluster=\"$cluster\", node=\"$node\", role=\"master\"})"
    }
   ]
  },
  {
   "title": "Replica Shard Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_server_used_memory{cluster=\"$cluster\", node=\"$node\", role=\"slave\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by(node) (irate(node_cpu_seconds_total{mode=\"system\", cluster=\"$cluster\", node=\"$node\"}[1m]))) + (avg by(node) (irate(node_cpu_seconds_total{mode=\"user\", cluster=\"$cluster\", node=\"$node\"}[1m])))"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_available_memory_bytes{cluster=\"$cluster\",node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": {
    "content": "<br>\n<center>\n  <b style=\"font-size: 20pt\">$version<b>\n</center>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node $node : CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage on Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit", "label": "percents" }
   ],
   "targets": [
    {
     "expr": "(avg by(node) (irate(node_cpu_seconds_total{mode=\"system\", cluster=\"$cluster\", node=\"$node\"}[1m]))) + (avg by(node) (irate(node_cpu_seconds_total{mode=\"user\", cluster=\"$cluster\", node=\"$node\"}[1m])))",
     "legendFormat": "user+system"
    },
    {
     "expr": "1- (avg by(node)(irate(node_cpu_seconds_total{mode=\"idle\",cluster=\"$cluster\", node=\"$node\"}[1m]))) - (avg by(node)(irate(node_cpu_seconds_total{mode=\"system\",cluster=\"$cluster\", node=\"$node\"}[1m]))) - (avg by(node)(irate(node_cpu_seconds_total{mode=\"user\",cluster=\"$cluster\", node=\"$node\"}[1m]))) unless (avg by(node)(irate(node_cpu_seconds_total{mode=\"nice\",cluster=\"$cluster\", node=\"$node\"}[1m])))",
     "legendFormat": "other"
    },
    {
     "expr": "avg by(node)(irate(dmcproxy_process_cpu_user_seconds_total{cluster=\"$cluster\", node=\"$node\"}[1m]))",
     "legendFormat": "dmcproxy (100% = 1 core)"
    },
    {
     "expr": "avg by(node)(irate(node_cpu_seconds_total{mode=~\"system|user\", cluster=\"$cluster\", node=\"$node\"}[1m]))",
     "legendFormat": "shards (100% = 1 core)"
    }
   ]
  },
  {
   "title": "Node Traffic",
   "type": "timeseries",
   "description": "display the egress and ingress traffic on the node's NIC",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps", "label": "Egress bytes/sec " }
   ],
   "targets": [
    {
     "expr": "sum by(node)(irate(node_network_receive_bytes_total{cluster=\"$cluster\", node=\"$node\"}[1m]))",
     "legendFormat": "Ingress for node {{node}}"
    },
    {
     "expr": "sum by(node)(irate(node_network_transmit_bytes_total{cluster=\"$cluster\", node=\"$node\"}[1m]))",
     "legendFormat": "egress for node {{node}}"
    }
   ]
  },
  {
   "title": "Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(redis_server_allocator_active{node=\"$node\",cluster=\"$cluster\"} / redis_server_allocator_allocated{node=\"$node\",cluster=\"$cluster\"}) - 1",
     "legendFormat": "active / allocated (defraggable)"
    },
    {
     "expr": "avg(redis_server_allocator_resident{node=\"$node\",cluster=\"$cluster\"} / redis_server_allocator_active{node=\"$node\",cluster=\"$cluster\"}) - 1",
     "legendFormat": "resident / active (purgable)"
    },
    {
     "expr": "sum(redis_server_allocator_active{node=\"$node\",cluster=\"$cluster\"} - redis_server_allocator_allocated{node=\"$node\",cluster=\"$cluster\"})",
     "legendFormat": "active - allocated (defraggable)"
    },
    {
     "expr": "sum(redis_server_allocator_resident{node=\"$node\",cluster=\"$cluster\"} - redis_server_allocator_active{node=\"$node\",cluster=\"$cluster\"})",
     "legendFormat": "resident - active (purgable)"
    },
    {
     "expr": "avg(redis_server_active_defrag_running{node=\"$node\",cluster=\"$cluster\"})/100",
     "legendFormat": "active defrag running"
    },
    {
     "expr": "sum(namedprocess_namegroup_memory_bytes{memtype=\"resident\", node=\"$node\",cluster=\"$cluster\"}) - sum(redis_server_allocator_resident{node=\"$node\",cluster=\"$cluster\"})",
     "legendFormat": "process rss - allocator rss"
    },
    {
     "expr": "sum(namedprocess_namegroup_memory_bytes{memtype=\"resident\", node=\"$node\",cluster=\"$cluster\"}) / sum(redis_server_allocator_resident{node=\"$node\",cluster=\"$cluster\"})",
     "legendFormat": "process rss / allocator rss"
    }
   ]
  },
  {
   "title": "Top 10 Shards by Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, redis_server_used_memory{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "redis:{{redis}}, bdb:{{bdb}},  role:{{role}}"
    },
    {
     "expr": "dmcproxy_process_resident_memory_bytes{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "dmcproxy"
    }
   ]
  }
 ]
}