{
 "title": "Database Dashboard v2",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(endpoint_client_connections,cluster)"
    }
   },
   {
    "name": "db",
    "label": "database",
    "query": {
     "query": "label_values(endpoint_client_connections{cluster=\"$cluster\"},db)"
    }
   },
   {
    "name": "status",
    "query": {
     "query": "label_values(bdb_status{bdb=\"$bdb\", cluster=\"$cluster\"}, status)"
    }
   },
   {
    "name": "newStatus",
    "query": {
     "query": "label_values(bdb_up{bdb=\"$bdb\", cluster=\"$cluster\"}, status)"
    }
   },
   {
    "name": "aggregation",
    "label": "aggregation interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(endpoint_read_requests_latency_histogram_bucket{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])) by (le))",
     "legendFormat": "Read"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(endpoint_write_requests_latency_histogram_bucket{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])) by (le))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(redis_server_used_memory{cluster=\"$cluster\", db=\"$db\"}/redis_server_maxmemory{cluster=\"$cluster\", db=\"$db\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Operations",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A + $B + $C", "type": "math" }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "rate(endpoint_read_requests{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(endpoint_write_requests{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])",
     "legendFormat": "write"
    },
    {
     "expr": "rate(endpoint_other_requests{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "Key Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(redis_server_db0_keys{cluster=\"$cluster\", db=\"$db\"})"
    }
   ]
  },
  {
   "title": "Expired Keys",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(redis_server_expired_keys{cluster=\"$cluster\", db=\"$db\"})",
     "legendFormat": "Expired Keys"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint_client_connections{cluster=\"$cluster\", db=\"$db\"}"
    }
   ]
  },
  {
   "title": "Total Misses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_server_keyspace_read_misses{cluster=\"$cluster\", db=\"$db\"} + redis_server_keyspace_write_misses{cluster=\"$cluster\", db=\"$db\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (db) (irate(namedprocess_namegroup_thread_cpu_seconds_total{mode=\"system\", role=\"master\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (db) (irate(namedprocess_namegroup_thread_cpu_seconds_total{mode=\"user\", role=\"master\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}