{
 "title": "Node Dashboard v2",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(endpoint_client_connections,cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_cpu_seconds_total{cluster=\"$cluster\"},node)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(node_config{cluster=\"$cluster\", node=\"$node\"},rs_version)"
    }
   },
   {
    "name": "aggregation",
    "label": "interval aggregation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Node $node : Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Database Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(redis_server_used_memory{cluster=\"$cluster\", node=\"$node\"}) by (db))"
    }
   ]
  },
  {
   "title": "Master Shard Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_server_used_memory{cluster=\"$cluster\", node=\"$node\", role=\"master\"})"
    }
   ]
  },
  {
   "title": "Replica Shard Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_server_used_memory{cluster=\"$cluster\", node=\"$node\", role=\"slave\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=~\"user|system\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_available_memory_bytes{cluster=\"$cluster\",node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": {
    "content": "<br>\n<center>\n  <b style=\"font-size: 20pt\">$version<b>\n</center>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node $node : CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage on Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit", "label": "percents" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\", cluster=\"$cluster\", node=\"$node\"}[1m])) + sum(irate(node_cpu_seconds_total{mode=\"system\", cluster=\"$cluster\", node=\"$node\"}[1m]))",
     "legendFormat": "user+system"
    }
   ]
  },
  {
   "title": "Node Traffic",
   "type": "timeseries",
   "description": "display the egress and ingress traffic on the node's NIC",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps", "label": "Egress bytes/sec " }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{node=\"$node\", device!=\"lo\", exporter=\"host\"}[1m])",
     "legendFormat": "ingress for node {{node}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{node=\"$node\", device!=\"lo\", exporter=\"host\"}[1m])",
     "legendFormat": "egress for node {{node}}"
    }
   ]
  },
  {
   "title": "Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_server_allocator_active{cluster=\"$cluster\", role=\"master\"} / redis_server_allocator_allocated{cluster=\"$cluster\", role=\"master\"}-1",
     "legendFormat": "active / allocated (defraggable)"
    },
    {
     "expr": "redis_server_allocator_resident{cluster=\"$cluster\", role=\"master\"} / redis_server_allocator_active{cluster=\"$cluster\", role=\"master\"} - 1",
     "legendFormat": "resident / active (purgable)"
    },
    {
     "expr": "sum(redis_server_allocator_active{cluster=\"$cluster\", role=\"master\"} - redis_server_allocator_allocated{cluster=\"$cluster\", role=\"master\"})",
     "legendFormat": "active - allocated (defraggable)"
    }
   ]
  },
  {
   "title": "Top 10 Shards by Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, redis_server_used_memory{cluster=\"$cluster\"})",
     "legendFormat": "redis:{{redis}}, bdb:{{bdb}},  role:{{role}}"
    }
   ]
  }
 ]
}