{
 "title": "Shard Dashboard v2",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(endpoint_client_connections,cluster)"
    }
   },
   {
    "name": "db",
    "label": "database",
    "query": {
     "query": "label_values(endpoint_client_connections{cluster=\"$cluster\"},db)"
    }
   },
   {
    "name": "status",
    "query": {
     "query": "label_values(redis_up{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"}, status)"
    }
   },
   {
    "name": "newStatus",
    "query": {
     "query": "label_values(redis_server_up{db=\"$db\", cluster=\"$cluster\"},status)"
    }
   },
   {
    "name": "shard",
    "label": "shard",
    "query": {
     "query": "label_values(redis_server_up{cluster=\"$cluster\", db=\"$db\"},redis)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$db : shard $shard : Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "<br>\n<center>\n<b style=\"font-size: 20pt\">$newStatus<b>\n</center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\", mode=\"system\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(redis_server_used_memory{cluster=\"$cluster\",  db=\"$db\", redis=\"$shard\"})"
    }
   ]
  },
  {
   "title": "Key Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_server_db0_keys{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(redis_server_connected_clients{db=\"$db\", cluster=\"$cluster\", redis=\"$shard\"})"
    }
   ]
  },
  {
   "title": "Forwarding",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_server_forwarding_state{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"})"
    }
   ]
  },
  {
   "title": "$db : shard $shard : Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Max Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_server_maxmemory{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_server_allocator_allocated{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "Client Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_server_mem_clients_normal{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "Replica Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_server_mem_clients_slaves{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "Fragmentation Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_server_mem_fragmentation_ratio{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "AOF Buffer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "redis_server_mem_aof_buffer{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "Memory less Eviction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_server_mem_not_counted_for_evict{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "Replication Backlog",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_server_mem_replication_backlog{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
     "legendFormat": "shard {{redis}}"
    }
   ]
  },
  {
   "title": "$db : shard $shard : CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Process CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}[1m])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\", mode=~\"system|user\"}[1m])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Main Thread",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_thread_cpu_seconds_total{cluster=\"$cluster\", redis=\"$shard\", threadname=~\"redis-server.*\"}[1m])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "$db : shard $shard : Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_server_connected_clients{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
     "legendFormat": "Total"
    },
    {}
   ]
  },
  {
   "title": "Commands Processed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_server_total_commands_processed{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
     "legendFormat": "Connected Clients"
    },
    {
     "expr": "redis_blocked_clients{bdb=\"$bdb\", cluster=\"$cluster\", redis=\"$shard\"}",
     "legendFormat": "Blocked Clients"
    }
   ]
  },
  {
   "title": "Ingress/Egress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "redis_server_total_net_output_bytes{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
     "legendFormat": "Egress"
    },
    {
     "expr": "redis_server_total_net_input_bytes{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
     "legendFormat": "Ingress"
    }
   ]
  },
  {
   "title": "$db : shard $shard : Keys",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Keys per Shard",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "redis_server_db0_keys{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
       "legendFormat": "shard:{{redis}}, role: {{role}}, node:{{node}}, slots:{{slots}}"
      }
     ]
    },
    {
     "title": "Total Keys",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "redis_server_db0_keys{cluster=\"$cluster\", redis=\"$shard\"}",
       "legendFormat": "shard: {{redis}}"
      }
     ]
    },
    {
     "title": "Evicted Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "redis_server_evicted_keys{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
       "legendFormat": "shard: {{redis}}"
      }
     ]
    },
    {
     "title": "Expired Keys",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "redis_server_expired_keys{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
       "legendFormat": "shard: {{redis}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$db : shard $shard : Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(redis_server_mem_fragmentation_ratio{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}) / count(redis_server_mem_fragmentation_ratio{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"})",
     "legendFormat": "redis_mem_fragmentation_ratio"
    },
    {
     "expr": "sum(redis_server_allocator_active{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}) / sum(redis_server_allocator_allocated{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"})",
     "legendFormat": "Shard allocator fragmentation"
    },
    {
     "expr": "sum(redis_server_allocator_resident{cluster=\"$cluster\",db=\"$db\", redis=\"$shard\"}) / sum(redis_server_allocator_active{cluster=\"$cluster\",db=\"$db\", redis=\"$shard\"})",
     "legendFormat": "shard allocator rss"
    }
   ]
  },
  {
   "title": "Shard RSS Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "redis_server_mem_fragmentation_ratio{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"} ",
     "legendFormat": "shard:{{redis}} role:{{role}}"
    }
   ]
  },
  {
   "title": "Shard Allocation Fragmentation (#)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_server_allocator_active{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"} - redis_server_allocator_allocated{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
     "legendFormat": "shard:{{redis}} role:{{role}}"
    }
   ]
  },
  {
   "title": "Shard Allocation Fragmentation (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "redis_server_allocator_active{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"} / redis_server_allocator_allocated{cluster=\"$cluster\", db=\"$db\", redis=\"$shard\"}",
     "legendFormat": "shard:{{redis}} role:{{role}}"
    }
   ]
  },
  {
   "title": "$db : shard $shard : ROF Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Used Memory(ROF) for $bdb",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "bdb_used_ram{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "bdb_used_ram"
      },
      {
       "expr": "bdb_ram_limit{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "limit (when low, near used)"
      }
     ]
    },
    {
     "title": "DB ram hit ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(bdb_big_fetch_ram{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_write_ram{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_del_ram{bdb=\"$bdb\", cluster=\"$cluster\"}) / (bdb_big_fetch_flash{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_write_flash{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_del_flash{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_fetch_ram{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_write_ram{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_del_ram{bdb=\"$bdb\", cluster=\"$cluster\"}) > 0",
       "legendFormat": "DB ram hit ratio"
      },
      {
       "expr": "bdb_big_fetch_ram{bdb=\"$bdb\", cluster=\"$cluster\"}  / (bdb_big_fetch_flash{bdb=\"$bdb\", cluster=\"$cluster\"}  + bdb_big_fetch_ram{bdb=\"$bdb\", cluster=\"$cluster\"} ) > 0",
       "legendFormat": "read hit ratio"
      },
      {
       "expr": "bdb_big_write_ram{bdb=\"$bdb\", cluster=\"$cluster\"}  / (bdb_big_write_flash{bdb=\"$bdb\", cluster=\"$cluster\"}  + bdb_big_write_ram{bdb=\"$bdb\", cluster=\"$cluster\"} ) > 0",
       "legendFormat": "write hit ratio"
      },
      {
       "expr": "bdb_big_del_ram{bdb=\"$bdb\", cluster=\"$cluster\"}  / (bdb_big_del_flash{bdb=\"$bdb\", cluster=\"$cluster\"}  + bdb_big_del_ram{bdb=\"$bdb\", cluster=\"$cluster\"} ) > 0",
       "legendFormat": "del hit ratio"
      }
     ]
    },
    {
     "title": "RAM:Flash access ratio",
     "type": "timeseries",
     "description": "Positive is RAM, Negative is Flash",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg(delta(redis_big_io_ratio_redis{cluster=\"$cluster\",bdb=\"$bdb\",role=\"master\"}[1m]))/60",
       "legendFormat": "RAM Ops for Redis"
      },
      {
       "expr": "avg(delta(redis_big_io_ratio_flash{cluster=\"$cluster\",bdb=\"$bdb\",role=\"master\"}[1m]) * -1)/60",
       "legendFormat": "Flash Ops for Redis"
      },
      {
       "expr": "avg(delta(redis_big_user_io_ratio_redis{cluster=\"$cluster\",bdb=\"$bdb\",role=\"master\"}[1m]))/60",
       "legendFormat": "User RAM Ops for Redis"
      },
      {
       "expr": "avg(delta(redis_big_user_io_ratio_flash{cluster=\"$cluster\",bdb=\"$bdb\",role=\"master\"}[1m]) * -1)/60",
       "legendFormat": "User Flash Ops for Redis"
      }
     ]
    },
    {
     "title": "RAM:Flash access ratio",
     "type": "timeseries",
     "description": "Positive is RAM, Negative is Flash",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "delta(redis_big_io_ratio_redis{cluster=\"$cluster\",bdb=\"$bdb\"}[1m])/60",
       "legendFormat": "RAM Ops for Redis {{redis}}"
      },
      {
       "expr": "delta(redis_big_io_ratio_flash{cluster=\"$cluster\",bdb=\"$bdb\"}[1m]) / -60",
       "legendFormat": "Flash Ops for Redis {{redis}}"
      }
     ]
    },
    {
     "title": "Flash IO Banwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "bdb_bigstore_io_read_bytes{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Reads"
      },
      {
       "expr": "bdb_bigstore_io_write_bytes{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Flash IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "bdb_bigstore_io_reads{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Reads"
      },
      {
       "expr": "bdb_bigstore_io_writes{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Writes"
      },
      {
       "expr": "bdb_bigstore_io_dels{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Deletes"
      }
     ]
    },
    {
     "title": "BDB sum redis wait busy key / $aggregation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(delta(redis_wait_busy_key{bdb=\"$bdb\",cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB sum redis blocking reads / $aggregation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(delta(redis_blocking_reads{bdb=\"$bdb\",cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB used flash",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "bdb_used_bigstore{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "used"
      },
      {
       "expr": "bdb_used_bigstore{bdb=\"$bdb\",cluster=\"$cluster\"} * bdb_disk_frag_ratio{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "actual"
      },
      {
       "expr": "bdb_disk_frag_ratio{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "frag ratio"
      }
     ]
    },
    {
     "title": "BDB postponed clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "bdb_big_postponed_clients{cluster=\"$cluster\",bdb=\"$bdb\"}",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB blocked clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "bdb_big_blocked_clients{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "Number of blocked clients"
      }
     ]
    },
    {
     "title": "BDB ram overhead",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "bdb_ram_overhead{cluster=\"$cluster\",bdb=\"$bdb\"}  / bdb_ram_limit{cluster=\"$cluster\",bdb=\"$bdb\"}",
       "legendFormat": "Total Ratio"
      },
      {
       "expr": "redis_ram_overhead{cluster=\"$cluster\",bdb=\"$bdb\"} / redis_max_ram{cluster=\"$cluster\",bdb=\"$bdb\"}",
       "legendFormat": "redis: {{redis}} role:{{role}}"
      }
     ]
    },
    {
     "title": "BDB sum redis blocking writes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(redis_blocking_writes{bdb=\"$bdb\",cluster=\"$cluster\"}[1m]))",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB sum redis big inst avg read io queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(redis_big_inst_avg_read_io_queue{bdb=\"$bdb\",cluster=\"$cluster\"})",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB sum redis big inst avg write io queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(redis_big_inst_avg_write_io_queue{bdb=\"$bdb\",cluster=\"$cluster\"})",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB objects(values) in FLASH",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "bdb_bigstore_objs_flash{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "objects in flash (sum of all master shards)"
      },
      {
       "expr": "bdb_bigstore_objs_ram{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "objects in ram (sum of all master shards)"
      }
     ]
    },
    {
     "title": "BDB % values in RAM",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "bdb_bigstore_objs_ram{bdb=\"$bdb\",cluster=\"$cluster\"} / bdb_no_of_keys{bdb=\"$bdb\",cluster=\"$cluster\"} ",
       "legendFormat": "BDB % values in RAM (masters)"
      },
      {
       "expr": "avg((max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster)) / on (redis,bdb,cluster) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"})",
       "legendFormat": "average master shard % values in RAM"
      },
      {
       "expr": "avg((max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (redis,bdb,cluster)) / on (redis,bdb,cluster) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"})",
       "legendFormat": "average slave shard % values in RAM"
      },
      {
       "expr": "topk(1, min((max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster)) / on (redis,bdb,cluster) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (redis) * -1) *-1",
       "legendFormat": "lowest master shard % values in RAM - redsi:{{redis}}"
      },
      {
       "expr": "topk(1, min((max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (redis,bdb,cluster)) / on (redis,bdb,cluster) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (redis) * -1) *-1",
       "legendFormat": "lowest slave shard % values in RAM - redsi:{{redis}}"
      }
     ]
    },
    {
     "title": "Shard objects(values) in RAM",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (redis,bdb,cluster))",
       "legendFormat": "average number of values in ram per slave shard"
      },
      {
       "expr": "avg(max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster))",
       "legendFormat": "average number of values in ram per master shard"
      },
      {
       "expr": "topk(1, min(max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (redis,bdb,cluster) < on(cluster,bdb,redis) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} ) by (bdb, redis) * -1) * -1",
       "legendFormat": "lowest number of values in ram per slave shard - redis:{{redis}}"
      },
      {
       "expr": "topk(1, min(max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster) < on(cluster,bdb,redis) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (bdb, redis) * -1) * -1",
       "legendFormat": "lowest number of values in ram per master shard  - redis:{{redis}}"
      }
     ]
    },
    {
     "title": "BDB dirty RAM evictions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "bdb_big_ram_dirty_evictions{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB clean RAM evictions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "bdb_big_ram_clean_evictions{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "RocksDB",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(delta(redis_rocks_comp_started{bdb=\"$bdb\", cluster=\"$cluster\"}[1m]))",
       "legendFormat": "compactions"
      },
      {
       "expr": "sum(delta(redis_rocks_flush_started{bdb=\"$bdb\", cluster=\"$cluster\"}[1m]))",
       "legendFormat": "flushes"
      },
      {
       "expr": "sum(delta(redis_rocks_flush_writes_slowdown{bdb=\"$bdb\", cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "slowdowns / $aggregation"
      },
      {
       "expr": "sum(delta(redis_rocks_flush_writes_stop{bdb=\"$bdb\", cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "stalls / $aggregation"
      }
     ]
    }
   ]
  }
 ]
}