= Redis Enterprise Developer Observability - Demonstration
:revnumber: 1.0
:docinfo1:

== About the demo

The demo was created so that it would encapsulate all the elements necessary to demonstrate dashboards using Redis.
It consists of a docker compose file, in addition to a grafana configuration and base grafana database as well as a prometheus configuration file.

The setup script 'setup.sh' will install containers for the different elements and configure their networking, after which it cleans up any temporary files.
Once the script has executed successfully the Grafana instance will be available at localhost:3000 and Prometheus at localhost:9090.
These are the default ports so it is important that neither Grafana nor Prometheus is already running on the machine.

=== Viewing the demo

Grafana's default credentials are admin/admin. You will be asked to change the password after you have logged in successfully.
If you are planning on keeping this environment for any ongoing testing it is recommended that you change the password.

=== Loading some data

The demo includes a small script which can create data and load it into Redis in order to drive activity.
It is a python script, 'import/import.py', and as such it would require the Redis python client to be installed.



