{
 "title": "Database Status - Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(node_up,cluster)" } },
   { "name": "subscription", "query": { "query": "" } },
   {
    "name": "bdb",
    "label": "database",
    "query": {
     "query": "bdb_conns{cluster=\"$cluster\"}"
    }
   },
   {
    "name": "status",
    "query": {
     "query": "label_values(bdb_status{bdb=\"$bdb\", cluster=\"$cluster\"}, status)"
    }
   },
   {
    "name": "newStatus",
    "query": {
     "query": "label_values(bdb_up{bdb=\"$bdb\", cluster=\"$cluster\"}, status)"
    }
   },
   {
    "name": "aggregation",
    "label": "aggregation interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "databaseId", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "bdb_avg_read_latency{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "bdb_avg_write_latency{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bdb_used_memory{cluster=\"$cluster\", bdb=\"$bdb\"}/bdb_memory_limit{cluster=\"$cluster\",bdb=\"$bdb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Operations",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bdb_total_req{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "bdb_read_req{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "read"
    },
    {
     "expr": "bdb_write_req{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "write"
    },
    {
     "expr": "bdb_other_req{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "Key Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(bdb_no_of_keys{bdb=\"$bdb\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Expired Keys",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bdb_expired_objects{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "Expired Keys"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(bdb_conns{bdb=\"$bdb\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Misses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bdb_read_misses + bdb_write_misses{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bdb_main_thread_cpu_system{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bdb_main_thread_cpu_user{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}