= Redis Datadog Prometheus

You can monitor your Redis Enteprise and Redis Cloud deployments using Datadog. This repository contains configuration and dashboards to get you up and running quickly.

== Table of Contents

* link:#Requirements[Requirements]
* link:#Usage[Usage]
* link:#Troubleshooting[Troubleshooting]
* link:#Support[Support]
* link:#License[License]

== Requirements

To monitor your Redis Enterprise/Cloud deployments with Datadog, you will need:

* A https://www.datadoghq.com/[Datadog account]
* A Redis Cloud account with a https://docs.redis.com/latest/rc/subscriptions/create-flexible-subscription/[Flexible/Annual subscription] *or* a self-managed Redis Enterprise software deployment.
* A https://docs.datadoghq.com/agent/[Datadog agent] running in an environment that can connect to your Redis cluster's Prometheus endpoint. For Redis Cloud deployments, this means that the environment running your Datadog agent must be https://docs.redis.com/latest/rc/security/vpc-peering/[VPC-peered with your Redis Cloud subscription].

Additionally, you will need the following configuration details:

* A https://docs.datadoghq.com/account_management/api-app-keys/[Datadog API key] associated with your Datadog account
* The host and port of the Prometheus endpoint exposed by your Redis deployment. See below for details on how to get this endpoint.

=== Prometheus endpoint

Your Redis Enterprise/Cloud deployment's Prometheus endpoint is accessible on port 8070.

If you're running *Redis Enterprise*, you can connect to Prometheus at the fully-qualified domain name (FQDN) of your cluster on port 8070. For example, if your cluster's FQDN is `redis.cluster.example.com`, then Prometheus is available over HTTPS at `redis.cluster.example.com:8070`.

On *Redis Cloud*, you first need to get the domain name of your deployment. Find the https://docs.redis.com/latest/rc/databases/view-edit-database/[private endpoint] for one of the databases associated with your Redis Cloud subscription. The private endpoint will look something like this: `redis-12345.internal.c67890.us-central1-1.gcp.cloud.rlrcp.com:121212`. Drop the first segment of the domain name (e.g., `redis-12345`) and change the port to 8070. In this example, the Prometheus endpoint is at `internal.c67890.us-central1-1.gcp.cloud.rlrcp.com:8070`.

== Usage

First, https://docs.datadoghq.com/agent/[install the Datadog agent] in your environment of choice.

Optionally, ensure that you can issue HTTP requests against your Redis Enterprise/Cloud Prometheus endpoint. You can test this using `curl`:

`curl -k https://internal.c28486.us-central1-mz.gcp.cloud.rlrcp.com:8070`

Second, install the Datadog integration onto the machine or container. NB: depending on version the binary might be called 'datadog-agent' and not simply 'agent'.

`agent integration install -r -t datadog-redis_enterprise==1.0.0`

Next, configure the Datadog agent's Redis Software extension to read from this endpoint. You can find a sample Datadog Redis Software configuration file in this repository at link:/datadog/src/conf.yml[src/conf.yaml.example].

All Datadog integrations have their configurations stored underneath this directory: `/etc/datadog-agent/conf.d`.

We recommend that you delete the 'redisdb' folder found in this folder, and then copy the example file found in 'redis_enterprise.d' to 'conf.yaml' and edit this file.

Under `instances`, describe one Prometheus endpoint for each Redis Enterprise cluster and/or Redis Cloud subscription that you want to monitor. For example, the configuration for monitoring two separate Redis Cloud subscriptions might look like this:

[source, yaml]
----
instances:
    ## @param openmetrics_endpoint - string - required
    ## Insert Description here for rdse OpenMetrics endpoint or link to docs
    #
  - openmetrics_endpoint: https://internal.c123.us-central1-mz.gcp.cloud.rlrcp.com:8070

    ## @param tls_verify - boolean - optional - default: false
    ## Instructs the check to validate the TLS certificate of services.
    #
    tls_verify: false

    ## @param openmetrics_endpoint - string - required
    ## Insert Description here for rdse OpenMetrics endpoint or link to docs
    #
  - openmetrics_endpoint: https://internal.c456.us-central1-mz.gcp.cloud.rlrcp.com:8070

    ## @param tls_verify - boolean - optional - default: false
    ## Instructs the check to validate the TLS certificate of services.
    #
    tls_verify: false

----

When you've finished editing the configuration file restart the agent.

If the Datadog agent is running and able to collect metrics, you'll see these metrics in the Datadog console within a few minutes. These metrics will be prefixed with `rdse`, or, in the event you have chosen the Redis Cloud integration, with `rdsc`.

The integration installs three dashboards; an overview dashboard, a node dashboard, and a database dashboard

Use the dropdowns at the top of each dashboard for filter by cluster and database.

== Troubleshooting

Review the Datadog UI for troubleshooting the Datadog agent. Locate the 'Infrastructure' heading in the menu and click on 'Host Map'.
The host map will display all hosts; select the one onto which you installed the integration, there should be an 'rdse' section, or 'rdsc' if this is a cloud installation.

You can also consult the Datadog agent logs at `/var/log/datadog`.

== Support

This integration is supported by Redis, Inc. on a good faith effort basis. To report bugs, request features, or receive assistance, please https://github.com/{project-owner}/{project-name}/issues[file an issue].

== License

This code in this repository is licensed under the MIT License. Copyright (C) 2023 Redis, Inc.
