{
 "title": "Database Status - Extended Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(node_up,cluster)" } },
   {
    "name": "db",
    "query": {
     "query": "label_values(redis_server_up{cluster=\"$cluster\"}, db)"
    }
   },
   {
    "name": "aggregation",
    "label": "aggregation interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(endpoint_read_requests_latency_histogram_sum{cluster=\"$cluster\", db=\"$db\"}[1m]) / irate(endpoint_read_requests{cluster=\"$cluster\", db=\"$db\"}[1m])/1000000",
     "legendFormat": "Read"
    },
    {
     "expr": "irate(endpoint_write_requests_latency_histogram_sum{cluster=\"$cluster\", db=\"$db\"}[1m]) / irate(endpoint_write_requests{cluster=\"$cluster\", db=\"$db\"}[1m])/1000000",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster,db)(redis_server_used_memory{role=\"master\", db=\"$db\", cluster=\"$cluster\"}) / (avg by(cluster,db)(db_memory_limit_bytes{db=\"$db\", cluster=\"$cluster\"}) / max by(cluster,db)(db_replication_factor{db=\"$db\", cluster=\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Operations",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(db) (irate(endpoint_read_requests{cluster=\"$cluster\",db=\"$db\"}[1m]) + irate(endpoint_write_requests{cluster=\"$cluster\",db=\"$db\"}[1m]) + irate(endpoint_other_requests{cluster=\"$cluster\",db=\"$db\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "irate(endpoint_read_requests{cluster=\"$cluster\", db=\"$db\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "irate(endpoint_write_requests{cluster=\"$cluster\", db=\"$db\"}[1m])",
     "legendFormat": "write"
    },
    {
     "expr": "irate(endpoint_other_requests{cluster=\"$cluster\", db=\"$db\"}[1m])",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(endpoint_client_connections{cluster=\"$cluster\",db=\"$db\"} - endpoint_client_disconnections{cluster=\"$cluster\",db=\"$db\"})"
    }
   ]
  },
  {
   "title": "System CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(namedprocess_namegroup_cpu_seconds_total{mode=\"system\", db=\"$db\", cluster=\"$cluster\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 } },
  {
   "title": "Key Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(redis_server_db_keys{db=\"$db\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "User CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(namedprocess_namegroup_cpu_seconds_total{mode=\"user\", db=\"$db\", cluster=\"$cluster\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Expired Keys",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(redis_server_expired_keys{role=\"master\", cluster=\"$cluster\", db=\"$db\"}[1m])",
     "legendFormat": "Expired Keys"
    }
   ]
  },
  {
   "title": "Total Misses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(redis_server_keyspace_read_misses{role=\"master\", cluster=\"$cluster\", db=\"$db\"}[1m]) + irate(redis_server_keyspace_write_misses{role=\"master\", cluster=\"$cluster\", db=\"$db\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}