{
 "title": "Cluster Dashboard",
 "tags": [ "RLEC" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "label_values(node_up,cluster)" },
   {
    "name": "node",
    "query": "label_values(node_up{cluster=\"$cluster\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "# Databases",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (bdb_conns{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_connected_clients{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "# Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_up{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "alertlist",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(ALERTS{cluster=\"$cluster\", alertstate=\"firing\"})"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "bdb_used_memory{cluster=\"$cluster\"}/bdb_memory_limit{cluster=\"$cluster\"}",
     "legendFormat": "{{bdb_name}}"
    }
   ]
  },
  {
   "title": "Grow over 1min (Over 100MiB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(delta(bdb_used_memory{cluster=\"$cluster\"}[1m])) by (bdb) * on(bdb) group_left(bdb_name) bdb_up{} > 100 * 1024*1024",
     "legendFormat": " {{bdb_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Requests by database",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(bdb_total_req{cluster=\"$cluster\"}) by (bdb) > 0) * on(bdb) group_left(bdb_name) bdb_up{}",
     "legendFormat": "{{bdb_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage for node $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "repeat": "node",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - node_cpu_idle{cluster=\"$cluster\", node=\"$node\"}*100"
    }
   ]
  },
  {
   "title": "Top 10 Requests Per Listener",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, listener_total_req{cluster=\"$cluster\"}) * on(bdb) group_left(bdb_name) bdb_up{}",
     "legendFormat": "listener {{proxy}} for {{bdb_name}}"
    }
   ]
  },
  {
   "title": "Used Memory By redis for Node $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "repeat": "node",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "redis_used_memory{node=\"$node\", cluster=\"$cluster\"} * on(bdb) group_left(bdb_name) bdb_up{}",
     "legendFormat": "database: {{bdb_name}} shard: {{redis}}"
    }
   ]
  },
  {
   "title": "List of Databases",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "bdb_used_memory{cluster=\"$cluster\"} * on(bdb) group_left(bdb_name) bdb_up{}",
     "legendFormat": "database {{bdb_name}}"
    }
   ]
  },
  {
   "title": "Used Memory by database over 30MB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "bdb_used_memory{cluster=\"$cluster\"} * on(bdb) group_left(bdb_name) bdb_up{} > 30 * 1024 * 1024",
     "legendFormat": "database: {{bdb_name}} "
    }
   ]
  },
  {
   "title": "Top 10 Used conns by database",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10, bdb_conns{cluster=\"$cluster\"}) * on(bdb) group_left(bdb_name) bdb_up{}",
     "legendFormat": "Conns for BDB: {{bdb_name}} "
    },
    {
     "expr": "topk(10, listener_conns{bdb=\"$bdb\", cluster=\"$cluster\"})",
     "legendFormat": "listener #{{listener}}"
    }
   ]
  },
  {
   "title": "Top databases by latency in cluster",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10,bdb_avg_latency{cluster=\"$cluster\"}) * on(bdb) group_left(bdb_name) bdb_up{}",
     "legendFormat": "Latency for database: {{bdb_name}} "
    }
   ]
  }
 ]
}