{
 "title": "Proxy Resources",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(node_up, cluster)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_up{cluster=\"$cluster\"}, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DMC:$node memory consumption",
   "type": "graph",
   "description": "dmcproxy process RAM consumption",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dmcproxy_process_resident_memory_bytes{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "proxy:{{node}} memory consumption"
    }
   ]
  },
  {
   "title": "Number of client connections to Proxy:$node",
   "type": "graph",
   "description": "Number of client connections across all dmc:$node endpoints",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (listener_conns{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "Number of client connections to proxy:{{node}}"
    }
   ]
  },
  {
   "title": "Endpoints total ingress/egress",
   "type": "graph",
   "description": "Traffic consumption of all endpoints dmc:$node is listening on",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/sec " }
   ],
   "targets": [
    {
     "expr": "sum by (node) (listener_ingress_bytes{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "dmc:{{node}} endpoints ingress"
    }
   ]
  },
  {
   "title": "Node $node ingress/egress",
   "type": "graph",
   "description": "Traffic consumption of node:$node in general",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/sec " }
   ],
   "targets": [
    {
     "expr": "node_ingress_bytes{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "node:{{node}} ingress"
    },
    {
     "expr": "- node_egress_bytes{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "node:{{node}} egress"
    }
   ]
  },
  {
   "title": "Number of databases in cluster",
   "type": "timeseries",
   "description": "Total number of BDBs in this cluster (not just those that dmc:$node has an endpoint for)",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "count(count(redis_used_memory{cluster=\"$cluster\", node=\"$node\"}) by (bdb))",
     "legendFormat": "Number of databases in cluster"
    }
   ]
  },
  {
   "title": "Proxy:$node number of endpoints",
   "type": "timeseries",
   "description": "Number of endpoints dmc:$node is listening on",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "count(listener_conns{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "Number of endpoints"
    }
   ]
  },
  {
   "title": "Proxy:$node CPU usage",
   "type": "graph",
   "description": "dmcproxy process' CPU consumption",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit", "label": "percents" }
   ],
   "targets": [
    {
     "expr": "dmcproxy_process_cpu_usage_percent{cluster=\"$cluster\", node=\"$node\"}/100",
     "legendFormat": "proxy:{{node}}"
    }
   ]
  },
  {
   "title": "Proxy:$node thread utilization",
   "type": "graph",
   "description": "Individual dmcproxy threads' utilization",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (threadname) (rate(namedprocess_namegroup_thread_cpu_seconds_total{cluster=\"$cluster\",groupname=\"dmcproxy\",node=\"$node\"}[1m])) ",
     "legendFormat": "{{threadname}}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "graph",
   "description": "dmc:$node's request rate",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, node) (listener_total_req{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "proxy:{{node}} request rate"
    }
   ]
  },
  {
   "title": "Response rate",
   "type": "graph",
   "description": "dmc:$node's response rate",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, node) (listener_total_res{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "proxy:{{node}} response rate"
    }
   ]
  },
  {
   "title": "Read request and response rate",
   "type": "graph",
   "description": "dmc:$node's read request and response rate",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, node) (listener_read_req{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "proxy:{{node}} read request rate"
    },
    {
     "expr": "sum by (cluster, node) (listener_read_res{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "proxy:{{node}} read response rate"
    }
   ]
  },
  {
   "title": "Write request and response rate",
   "type": "graph",
   "description": "dmc:$node's write request and response rate",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, node) (listener_write_req{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "proxy:{{node}} write request rate"
    },
    {
     "expr": "sum by (cluster, node) (listener_write_res{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "proxy:{{node}} write response rate"
    }
   ]
  },
  {
   "title": "GET request rate",
   "type": "graph",
   "description": "dmc:$node's GET request rate",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, node) (listener_cmd_get{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "proxy:{{node}} GET request rate"
    }
   ]
  },
  {
   "title": "SET request rate",
   "type": "graph",
   "description": "dmc:$node's SET request rate",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, node) (listener_cmd_set{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "proxy:{{node}} SET request rate"
    }
   ]
  }
 ]
}