{
 "title": "Database Dashboard (Classic)",
 "tags": [ "RLEC" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "label_values(node_up,cluster)" },
   {
    "name": "bdb",
    "label": "BDB Id",
    "query": "label_values(bdb_conns{cluster=\"$cluster\"}, bdb)"
   },
   {
    "name": "status",
    "query": "label_values(bdb_status{bdb=\"$bdb\", cluster=\"$cluster\"}, status)"
   },
   {
    "name": "newStatus",
    "query": "label_values(bdb_up{bdb=\"$bdb\", cluster=\"$cluster\"}, status)"
   },
   {
    "name": "aggregation",
    "label": "aggregation interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status for BDB:$bdb",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "<b style=\"font-size: 20pt\">$status<b>\n<b style=\"font-size: 20pt\">$newStatus<b>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "BDB:$bdb used memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(bdb_used_memory{bdb=\"$bdb\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "BDB:$bdb #Keys",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(bdb_no_of_keys{bdb=\"$bdb\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "BDB:$bdb #Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(bdb_conns{bdb=\"$bdb\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "BDB:$bdb #Listeners",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(listener_total_req{bdb=\"$bdb\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "BDB:$bdb #Shards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_no_of_keys{cluster=\"$cluster\", bdb=\"$bdb\"}) or count(redis_used_memory{cluster=\"$cluster\", bdb=\"$bdb\"})"
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg latency for BDB:$bdb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "bdb_avg_latency{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "bdb_avg_latency"
    },
    {
     "expr": "bdb_avg_write_latency{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "bdb_avg_write_latency"
    },
    {
     "expr": "bdb_avg_read_latency{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "bdb_avg_read_latency"
    },
    {
     "expr": "bdb_avg_other_latency{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "bdb_avg_other_latency"
    },
    {
     "expr": "max_over_time(bdb_avg_latency_max{bdb=\"$bdb\", cluster=\"$cluster\"}[$aggregation])",
     "legendFormat": "bdb_avg_latency (max over $aggregation)"
    }
   ]
  },
  {
   "title": "Avg listener latency for BDB:$bdb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "listener_acc_latency{bdb=~\"$bdb.*\", cluster=\"$cluster\"} / listener_total_started_res{bdb=~\"$bdb.*\", cluster=\"$cluster\"}",
     "legendFormat": "listener {{proxy}}  node {{node}}"
    }
   ]
  },
  {
   "title": "Used Memory for BDB:$bdb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bdb_used_memory{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "used_memory"
    },
    {
     "expr": "bdb_memory_limit{bdb=\"$bdb\", cluster=\"$cluster\"} < bdb_used_memory{bdb=\"$bdb\", cluster=\"$cluster\"} * 1.5",
     "legendFormat": "limit (when low, near used)"
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "BDB:$bdb Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bdb_conns{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "listener_conns{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "endpoint {{proxy}} node: {{node}}"
    }
   ]
  },
  {
   "title": "Requests[total,read,write,other] for bdb:$bdb",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "bdb_total_req{cluster=\"$cluster\",bdb=\"$bdb\"}",
     "legendFormat": "total requests"
    },
    {
     "expr": "bdb_other_req{cluster=\"$cluster\",bdb=\"$bdb\"}",
     "legendFormat": "other requests"
    },
    {
     "expr": "bdb_read_req{cluster=\"$cluster\",bdb=\"$bdb\"}",
     "legendFormat": "read requests"
    },
    {
     "expr": "bdb_write_req{cluster=\"$cluster\",bdb=\"$bdb\"}",
     "legendFormat": "write requests"
    },
    {
     "expr": "max_over_time(bdb_total_req_max{cluster=\"$cluster\",bdb=\"$bdb\"}[$aggregation])\n",
     "legendFormat": "total requests (max over $aggregation)"
    }
   ]
  },
  {
   "title": "BDB:$bdb Ingress/Egress",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "Bps", "label": "Ingress" }
   ],
   "targets": [
    {
     "expr": "bdb_egress_bytes{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "Egress"
    },
    {
     "expr": "bdb_ingress_bytes{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "Ingress"
    }
   ]
  },
  {
   "title": "BDB CPU utilization for bdb:$bdb",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "bdb_main_thread_cpu_system{bdb=\"$bdb\",cluster=\"$cluster\"} + bdb_main_thread_cpu_user{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "main threads (masters)"
    },
    {
     "expr": "bdb_shard_cpu_system{bdb=\"$bdb\",cluster=\"$cluster\"} + bdb_shard_cpu_user{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "all threads (masters)"
    },
    {
     "expr": "bdb_fork_cpu_system{bdb=\"$bdb\",cluster=\"$cluster\"} + bdb_fork_cpu_user{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "all forks (masters)"
    },
    {
     "expr": "bdb_main_thread_cpu_system_max{bdb=\"$bdb\",cluster=\"$cluster\"} + bdb_main_thread_cpu_user_max{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "main threads max (masters)"
    },
    {
     "expr": "bdb_shard_cpu_system_max{bdb=\"$bdb\",cluster=\"$cluster\"} + bdb_shard_cpu_user_max{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "all threads max (masters)"
    },
    {
     "expr": "sum((delta(redis_process_main_thread_cpu_system_seconds_total{bdb=\"$bdb\",role=\"slave\", cluster=\"$cluster\"}[60s]) + delta(redis_process_main_thread_cpu_user_seconds_total{bdb=\"$bdb\",role=\"slave\", cluster=\"$cluster\"}[60s]))/60)",
     "legendFormat": "Slave main threads"
    },
    {
     "expr": "sum((delta(redis_process_cpu_system_seconds_total{bdb=\"$bdb\",role=\"slave\",cluster=\"$cluster\"}[60s]) + delta(redis_process_cpu_user_seconds_total{bdb=\"$bdb\",role=\"slave\",cluster=\"$cluster\"}[60s]))/60)",
     "legendFormat": "Slave all threads"
    }
   ]
  },
  {
   "title": "CPU usage by shards for bdb:$bdb",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(delta(redis_process_cpu_system_seconds_total{bdb=\"$bdb\",cluster=\"$cluster\"}[60s]) + delta(redis_process_cpu_user_seconds_total{bdb=\"$bdb\",cluster=\"$cluster\"}[60s]))/60*100 or redis_cpu_percent{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "shard: {{redis}} role: {{role}} node:{{node}}, slots:{{slots}}"
    }
   ]
  },
  {
   "title": "Sizes of shards for bdb:$bdb",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_used_memory{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "redis:{{redis}}, role:{{role}}, node:{{node}}, slots:{{slots}}"
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "# keys/shard",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_no_of_keys{bdb=\"$bdb\", cluster=\"$cluster\"} or redis_db0_keys{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "redis:{{redis}}, role: {{role}}, node:{{node}}, slots:{{slots}}"
    }
   ]
  },
  {
   "title": "#Keys for BDB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bdb_no_of_keys{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "num of keys"
    },
    {
     "expr": "sum(redis_db0_expires{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"})",
     "legendFormat": "num of volatile keys"
    },
    {
     "expr": "sum(max(redis_bigdb0_ram{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"} or redis_bigdb_ram{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster))",
     "legendFormat": "ram keys"
    },
    {
     "expr": "sum(max(redis_bigdb0_disk{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"} or redis_bigdb_disk{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster))",
     "legendFormat": "disk keys"
    },
    {
     "expr": "(sum(max(redis_bigdb0_disk{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"} or redis_bigdb_disk{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster)) + sum(max(redis_bigdb0_ram{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"} or redis_bigdb_ram{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster))) - sum(redis_db0_keys{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"})",
     "legendFormat": "overlapping keys"
    },
    {
     "expr": "sum(max(redis_bigdb0_dirty{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"} or redis_bigdb_dirty{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster))",
     "legendFormat": "dirty keys"
    },
    {
     "expr": "sum(max(redis_bigdb0_clean{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"} or redis_bigdb_clean{bdb=\"$bdb\", cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster))",
     "legendFormat": "clean keys"
    }
   ]
  },
  {
   "title": "Evicted objects for BDB:$bdb",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bdb_evicted_objects{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "BDB:$bdb"
    }
   ]
  },
  {
   "title": "Expired objects for BDB:$bdb",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bdb_expired_objects{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "BDB:$bdb"
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Shard AOF Rewrites / $aggregation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(redis_aof_rewrites{cluster=\"$cluster\", bdb=\"$bdb\"}[$aggregation]) !=0",
     "legendFormat": "Redis {{redis}} node {{node}}"
    }
   ]
  },
  {
   "title": "forks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_rdb_bgsave_in_progress{cluster=\"$cluster\", bdb=\"$bdb\"} !=0",
     "legendFormat": "BGSAVE {{redis}} node {{node}}"
    },
    {
     "expr": "redis_aof_rewrite_in_progress{cluster=\"$cluster\", bdb=\"$bdb\"} !=0",
     "legendFormat": "AOFRW {{redis}} node {{node}}"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bdb_read_hits{bdb=\"$bdb\",cluster=\"$cluster\"}/(bdb_read_hits{bdb=\"$bdb\",cluster=\"$cluster\"} + bdb_read_misses{bdb=\"$bdb\",cluster=\"$cluster\"})",
     "legendFormat": "{{bdb_name}}"
    }
   ]
  },
  {
   "title": "Read/Write Misses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 40 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "bdb_read_misses{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "Read Misses"
    },
    {
     "expr": "bdb_write_misses{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "Write Misses"
    },
    {
     "expr": "bdb_read_hits{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "Read Hits"
    },
    {
     "expr": "bdb_write_hits{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "Write Hits"
    }
   ]
  },
  {
   "title": "DB Hit Ratio (hits / requests)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(bdb_read_hits{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_write_hits{bdb=\"$bdb\", cluster=\"$cluster\"}) / (bdb_read_req{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_write_req{bdb=\"$bdb\", cluster=\"$cluster\"})",
     "legendFormat": "DB hit ratio"
    }
   ]
  },
  {
   "title": "Syncer lag",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "bdb_replicaof_syncer_local_ingress_lag_time{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "BDB $bdb  src_id {{src_id}}"
    },
    {
     "expr": "bdb_crdt_syncer_local_ingress_lag_time{bdb=\"$bdb\", cluster=\"$cluster\"}",
     "legendFormat": "BDB $bdb crdt src_id {{src_id}}"
    }
   ]
  },
  {
   "title": "BDB:$bdb total fragmentation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(redis_mem_fragmentation_ratio{bdb=\"$bdb\",cluster=\"$cluster\"}) / count(redis_mem_fragmentation_ratio{bdb=\"$bdb\",cluster=\"$cluster\"})",
     "legendFormat": "redis_mem_fragmentation_ratio"
    },
    {
     "expr": "sum(redis_allocator_active{bdb=\"$bdb\",cluster=\"$cluster\"}) / sum(redis_allocator_allocated{bdb=\"$bdb\",cluster=\"$cluster\"})",
     "legendFormat": "Shard allocator fragmentation"
    },
    {
     "expr": "sum(redis_allocator_resident{bdb=\"$bdb\",cluster=\"$cluster\"}) / sum(redis_allocator_active{bdb=\"$bdb\",cluster=\"$cluster\"})",
     "legendFormat": "shard allocator rss"
    }
   ]
  },
  {
   "title": "Shard RSS fragmentation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 46 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "redis_fragmentation{bdb=\"$bdb\", cluster=\"$cluster\"} or redis_mem_fragmentation_ratio{bdb=\"$bdb\", cluster=\"$cluster\"} ",
     "legendFormat": "Redis {{redis}} ({{role}})"
    }
   ]
  },
  {
   "title": "BDB sum redis active defrag running",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "redis_active_defrag_running{cluster=\"$cluster\",bdb=\"$bdb\"}",
     "legendFormat": "redis:{{redis}} role:{{role}}"
    }
   ]
  },
  {
   "title": "Delayed fsync - (events / $aggregation)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(redis_aof_delayed_fsync{bdb=\"$bdb\", cluster=\"$cluster\"}[$aggregation])",
     "legendFormat": "Redis {{redis}} ({{role}})"
    }
   ]
  },
  {
   "title": "Shard allocator fragmentation bytes (defraggable)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "redis_allocator_active{bdb=\"$bdb\",cluster=\"$cluster\"} - redis_allocator_allocated{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "redis:{{redis}} role:{{role}}"
    }
   ]
  },
  {
   "title": "Shard allocator fragmentation % (defraggable)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 52 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "redis_allocator_active{bdb=\"$bdb\",cluster=\"$cluster\"} / redis_allocator_allocated{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "redis:{{redis}} role:{{role}}"
    }
   ]
  },
  {
   "title": "ROF Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "BDB (ROF) used RAM for $bdb",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bdb_used_ram{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "bdb_used_ram"
      },
      {
       "expr": "bdb_ram_limit{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "limit (when low, near used)"
      }
     ]
    },
    {
     "title": "DB ram hit ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(bdb_big_fetch_ram{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_write_ram{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_del_ram{bdb=\"$bdb\", cluster=\"$cluster\"}) / (bdb_big_fetch_flash{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_write_flash{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_del_flash{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_fetch_ram{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_write_ram{bdb=\"$bdb\", cluster=\"$cluster\"} + bdb_big_del_ram{bdb=\"$bdb\", cluster=\"$cluster\"}) > 0",
       "legendFormat": "DB ram hit ratio"
      },
      {
       "expr": "bdb_big_fetch_ram{bdb=\"$bdb\", cluster=\"$cluster\"}  / (bdb_big_fetch_flash{bdb=\"$bdb\", cluster=\"$cluster\"}  + bdb_big_fetch_ram{bdb=\"$bdb\", cluster=\"$cluster\"} ) > 0",
       "legendFormat": "read hit ratio"
      },
      {
       "expr": "bdb_big_write_ram{bdb=\"$bdb\", cluster=\"$cluster\"}  / (bdb_big_write_flash{bdb=\"$bdb\", cluster=\"$cluster\"}  + bdb_big_write_ram{bdb=\"$bdb\", cluster=\"$cluster\"} ) > 0",
       "legendFormat": "write hit ratio"
      },
      {
       "expr": "bdb_big_del_ram{bdb=\"$bdb\", cluster=\"$cluster\"}  / (bdb_big_del_flash{bdb=\"$bdb\", cluster=\"$cluster\"}  + bdb_big_del_ram{bdb=\"$bdb\", cluster=\"$cluster\"} ) > 0",
       "legendFormat": "del hit ratio"
      }
     ]
    },
    {
     "title": "BDB RAM:Flash access ratio",
     "type": "graph",
     "description": "Positive is RAM, Negative is Flash",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "avg(delta(redis_big_io_ratio_redis{cluster=\"$cluster\",bdb=\"$bdb\",role=\"master\"}[1m]))/60",
       "legendFormat": "RAM Ops for Redis"
      },
      {
       "expr": "avg(delta(redis_big_io_ratio_flash{cluster=\"$cluster\",bdb=\"$bdb\",role=\"master\"}[1m]) * -1)/60",
       "legendFormat": "Flash Ops for Redis"
      },
      {
       "expr": "avg(delta(redis_big_user_io_ratio_redis{cluster=\"$cluster\",bdb=\"$bdb\",role=\"master\"}[1m]))/60",
       "legendFormat": "User RAM Ops for Redis"
      },
      {
       "expr": "avg(delta(redis_big_user_io_ratio_flash{cluster=\"$cluster\",bdb=\"$bdb\",role=\"master\"}[1m]) * -1)/60",
       "legendFormat": "User Flash Ops for Redis"
      }
     ]
    },
    {
     "title": "RAM:Flash access ratio",
     "type": "graph",
     "description": "Positive is RAM, Negative is Flash",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "delta(redis_big_io_ratio_redis{cluster=\"$cluster\",bdb=\"$bdb\"}[1m])/60",
       "legendFormat": "RAM Ops for Redis {{redis}}"
      },
      {
       "expr": "delta(redis_big_io_ratio_flash{cluster=\"$cluster\",bdb=\"$bdb\"}[1m]) / -60",
       "legendFormat": "Flash Ops for Redis {{redis}}"
      }
     ]
    },
    {
     "title": "Flash IO Banwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bdb_bigstore_io_read_bytes{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Reads"
      },
      {
       "expr": "bdb_bigstore_io_write_bytes{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Flash IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_bigstore_io_reads{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Reads"
      },
      {
       "expr": "bdb_bigstore_io_writes{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Writes"
      },
      {
       "expr": "bdb_bigstore_io_dels{bdb=\"$bdb\", cluster=\"$cluster\"}",
       "legendFormat": "Deletes"
      }
     ]
    },
    {
     "title": "BDB sum redis wait busy key / $aggregation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(redis_wait_busy_key{bdb=\"$bdb\",cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB sum redis blocking reads / $aggregation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(redis_blocking_reads{bdb=\"$bdb\",cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB used flash",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 83 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bdb_used_bigstore{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "used"
      },
      {
       "expr": "bdb_used_bigstore{bdb=\"$bdb\",cluster=\"$cluster\"} * bdb_disk_frag_ratio{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "actual"
      },
      {
       "expr": "bdb_disk_frag_ratio{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "frag ratio"
      }
     ]
    },
    {
     "title": "BDB postponed clients",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_big_postponed_clients{cluster=\"$cluster\",bdb=\"$bdb\"}",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB blocked clients",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_big_blocked_clients{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "Number of blocked clients"
      }
     ]
    },
    {
     "title": "BDB ram overhead",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "bdb_ram_overhead{cluster=\"$cluster\",bdb=\"$bdb\"}  / bdb_ram_limit{cluster=\"$cluster\",bdb=\"$bdb\"}",
       "legendFormat": "Total Ratio"
      },
      {
       "expr": "redis_ram_overhead{cluster=\"$cluster\",bdb=\"$bdb\"} / redis_max_ram{cluster=\"$cluster\",bdb=\"$bdb\"}",
       "legendFormat": "redis: {{redis}} role:{{role}}"
      }
     ]
    },
    {
     "title": "BDB sum redis blocking writes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 99 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redis_blocking_writes{bdb=\"$bdb\",cluster=\"$cluster\"}[1m]))",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB sum redis big inst avg read io queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 99 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redis_big_inst_avg_read_io_queue{bdb=\"$bdb\",cluster=\"$cluster\"})",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB sum redis big inst avg write io queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 99 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redis_big_inst_avg_write_io_queue{bdb=\"$bdb\",cluster=\"$cluster\"})",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB objects(values) in FLASH",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 107 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_bigstore_objs_flash{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "objects in flash (sum of all master shards)"
      },
      {
       "expr": "bdb_bigstore_objs_ram{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "objects in ram (sum of all master shards)"
      }
     ]
    },
    {
     "title": "BDB % values in RAM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 107 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "bdb_bigstore_objs_ram{bdb=\"$bdb\",cluster=\"$cluster\"} / bdb_no_of_keys{bdb=\"$bdb\",cluster=\"$cluster\"} ",
       "legendFormat": "BDB % values in RAM (masters)"
      },
      {
       "expr": "avg((max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster)) / on (redis,bdb,cluster) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"})",
       "legendFormat": "average master shard % values in RAM"
      },
      {
       "expr": "avg((max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (redis,bdb,cluster)) / on (redis,bdb,cluster) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"})",
       "legendFormat": "average slave shard % values in RAM"
      },
      {
       "expr": "topk(1, min((max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster)) / on (redis,bdb,cluster) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (redis) * -1) *-1",
       "legendFormat": "lowest master shard % values in RAM - redsi:{{redis}}"
      },
      {
       "expr": "topk(1, min((max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (redis,bdb,cluster)) / on (redis,bdb,cluster) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (redis) * -1) *-1",
       "legendFormat": "lowest slave shard % values in RAM - redsi:{{redis}}"
      }
     ]
    },
    {
     "title": "Shard objects(values) in RAM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 107 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (redis,bdb,cluster))",
       "legendFormat": "average number of values in ram per slave shard"
      },
      {
       "expr": "avg(max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster))",
       "legendFormat": "average number of values in ram per master shard"
      },
      {
       "expr": "topk(1, min(max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"}) by (redis,bdb,cluster) < on(cluster,bdb,redis) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"slave\"} ) by (bdb, redis) * -1) * -1",
       "legendFormat": "lowest number of values in ram per slave shard - redis:{{redis}}"
      },
      {
       "expr": "topk(1, min(max(redis_bigdb0_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"} or redis_bigdb_ram{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (redis,bdb,cluster) < on(cluster,bdb,redis) redis_db0_keys{bdb=\"$bdb\",cluster=\"$cluster\",role=\"master\"}) by (bdb, redis) * -1) * -1",
       "legendFormat": "lowest number of values in ram per master shard  - redis:{{redis}}"
      }
     ]
    },
    {
     "title": "BDB dirty RAM evictions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 115 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_big_ram_dirty_evictions{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "BDB clean RAM evictions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 115 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bdb_big_ram_clean_evictions{bdb=\"$bdb\",cluster=\"$cluster\"}",
       "legendFormat": "bdb:{{$bdb}}"
      }
     ]
    },
    {
     "title": "RocksDB",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 115 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(redis_rocks_comp_started{bdb=\"$bdb\", cluster=\"$cluster\"}[1m]))",
       "legendFormat": "compactions"
      },
      {
       "expr": "sum(delta(redis_rocks_flush_started{bdb=\"$bdb\", cluster=\"$cluster\"}[1m]))",
       "legendFormat": "flushes"
      },
      {
       "expr": "sum(delta(redis_rocks_flush_writes_slowdown{bdb=\"$bdb\", cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "slowdowns / $aggregation"
      },
      {
       "expr": "sum(delta(redis_rocks_flush_writes_stop{bdb=\"$bdb\", cluster=\"$cluster\"}[$aggregation]))",
       "legendFormat": "stalls / $aggregation"
      }
     ]
    }
   ]
  }
 ]
}