{
 "title": "Synchronization (Classic)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "crdt_guid", "query": { "query": "label_values(crdt_guid)" } },
   {
    "name": "aggregation",
    "label": "aggregation interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "query0" }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "instances",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "bdb_used_memory{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Average database latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "bdb_avg_latency{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "bdb_avg_latency - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_avg_write_latency{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "bdb_avg_write_latency - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_avg_read_latency{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "bdb_avg_read_latency - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_avg_other_latency{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "bdb_avg_other_latency - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "max_over_time(bdb_avg_latency_max{crdt_guid=\"$crdt_guid\"}[$aggregation])",
     "legendFormat": "bdb_avg_latency (max over $aggregation) - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "Average database listener latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "listener_acc_latency{crdt_guid=\"$crdt_guid\"} / listener_total_started_res{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Replica:{{crdt_replica_id}} - listener {{proxy}}  node {{node}}"
    }
   ]
  },
  {
   "title": "Database used memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bdb_used_memory{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "used_memory - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_memory_limit{crdt_guid=\"$crdt_guid\"} < bdb_used_memory{crdt_guid=\"$crdt_guid\"} * 1.5",
     "legendFormat": "limit (when low, near used) - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Database Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "bdb_conns{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Replica:{{crdt_replica_id}} - Total"
    },
    {
     "expr": "listener_conns{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Replica:{{crdt_replica_id}} - endpoint {{proxy}} node: {{node}}"
    }
   ]
  },
  {
   "title": "Requests[total,read,write,other] for database",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "bdb_total_req{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "total requests - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_other_req{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "other requests - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_read_req{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "read requests - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_write_req{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "write requests - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_total_req_max{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "total requests (max) - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "max_over_time(bdb_total_req_max{crdt_guid=\"$crdt_guid\"}[$aggregation])",
     "legendFormat": "total requests (max over $aggregation) - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "Database Ingress/Egress",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "Bps", "label": "Ingress" }
   ],
   "targets": [
    {
     "expr": "- bdb_egress_bytes{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "BDB Egress - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_ingress_bytes{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "BDB Ingress - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "sum by (crdt_replica_id) (rate(redis_total_net_input_bytes{crdt_guid=\"$crdt_guid\", role=\"master\"}[1m]))",
     "legendFormat": "Master shard Ingress - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "- (sum by (crdt_replica_id) (rate(redis_total_net_output_bytes{crdt_guid=\"$crdt_guid\", role=\"master\"}[1m]) - rate(redis_master_repl_offset{crdt_guid=\"$crdt_guid\", role=\"master\"}[1m])))",
     "legendFormat": "Master shard Egress - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "sum by (crdt_replica_id) (rate(redis_master_repl_offset{crdt_guid=\"$crdt_guid\", role=\"master\"}[1m]))",
     "legendFormat": "Master shard replication - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "sum by (crdt_replica_id) (rate(redis_repl_touch_bytes{crdt_guid=\"$crdt_guid\", role=\"master\"}[1m]))!=0",
     "legendFormat": "Master shard repl touch - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU utilization for database",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "bdb_main_thread_cpu_system{crdt_guid=\"$crdt_guid\"} + bdb_main_thread_cpu_user{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "main threads (masters) - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_shard_cpu_system{crdt_guid=\"$crdt_guid\"} + bdb_shard_cpu_user{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "all threads (masters) - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_fork_cpu_system{crdt_guid=\"$crdt_guid\"} + bdb_fork_cpu_user{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "all forks (masters) - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_main_thread_cpu_system_max{crdt_guid=\"$crdt_guid\"} + bdb_main_thread_cpu_user_max{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "main threads max (masters) - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_shard_cpu_system_max{crdt_guid=\"$crdt_guid\"} + bdb_shard_cpu_user_max{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "all threads max (masters) - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "sum by (crdt_replica_id) ((delta(redis_process_main_thread_cpu_system_seconds_total{crdt_guid=\"$crdt_guid\",role=\"slave\"}[60s]) + delta(redis_process_main_thread_cpu_user_seconds_total{crdt_guid=\"$crdt_guid\",role=\"slave\"}[60s]))/60)",
     "legendFormat": "Slave main threads - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "sum by (crdt_replica_id) ((delta(redis_process_cpu_system_seconds_total{crdt_guid=\"$crdt_guid\",role=\"slave\"}[60s]) + delta(redis_process_cpu_user_seconds_total{crdt_guid=\"$crdt_guid\",role=\"slave\"}[60s]))/60)",
     "legendFormat": "Slave all threads - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "CPU usage by shards for database",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(delta(redis_process_cpu_system_seconds_total{crdt_guid=\"$crdt_guid\"}[60s]) + delta(redis_process_cpu_user_seconds_total{crdt_guid=\"$crdt_guid\"}[60s]))/60*100 or redis_cpu_percent{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Replica:{{crdt_replica_id}} - shard: {{redis}} role: {{role}} node:{{node}}, slots:{{slots}}"
    }
   ]
  },
  {
   "title": "Sizes of shards for database",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_used_memory{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Replica:{{crdt_replica_id}} - redis:{{redis}}, role:{{role}}, node:{{node}}, slots:{{slots}}"
    },
    {
     "expr": "redis_maxmemory{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Replica:{{crdt_replica_id}} - maxmemory: redis:{{redis}}, role:{{role}}, node:{{node}}"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "# keys/shard",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_no_of_keys{crdt_guid=\"$crdt_guid\"} or redis_db0_keys{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Replica:{{crdt_replica_id}} - redis:{{redis}}, role: {{role}}, node:{{node}}, slots:{{slots}}"
    }
   ]
  },
  {
   "title": "#Keys for database",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Evicted objects for database",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bdb_evicted_objects{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Evicted BDB"
    },
    {
     "expr": "sum by (crdt_replica_id) (redis_keys_trimmed{crdt_guid=\"$crdt_guid\"})!=0",
     "legendFormat": "Reshard trimmed BDB - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "Expired objects for database",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bdb_expired_objects{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Replica:{{crdt_replica_id}}"
    }
   ]
  },
  { "title": "Partitioning/Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Shard AOF Rewrites / $aggregation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(redis_aof_rewrites{crdt_guid=\"$crdt_guid\"}[$aggregation]) !=0",
     "legendFormat": "Replica:{{crdt_replica_id}} - Redis {{redis}} node {{node}}"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_rdb_bgsave_in_progress{crdt_guid=\"$crdt_guid\"} !=0",
     "legendFormat": "BGSAVE Replica:{{crdt_replica_id}} - {{redis}} node {{node}}"
    },
    {
     "expr": "redis_aof_rewrite_in_progress{crdt_guid=\"$crdt_guid\"} !=0",
     "legendFormat": "AOFRW Replica:{{crdt_replica_id}} - {{redis}} node {{node}}"
    },
    {
     "expr": "redis_module_fork_in_progress{crdt_guid=\"$crdt_guid\"} !=0",
     "legendFormat": "Module fork Replica:{{crdt_replica_id}} - {{redis}} node {{node}}"
    }
   ]
  },
  {
   "title": "Read/Write Hits / Misses  + lazyfree + errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "bdb_read_misses{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Read Misses - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_write_misses{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Write Misses - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_read_hits{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Read Hits - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_write_hits{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Write Hits - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "delta(redis_total_error_replies{crdt_guid=\"$crdt_guid\"}[60s])/60  ",
     "legendFormat": "Error Replies - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "Shard RSS fragmentation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 43 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "redis_fragmentation{crdt_guid=\"$crdt_guid\"} or redis_mem_fragmentation_ratio{crdt_guid=\"$crdt_guid\"} ",
     "legendFormat": "Replica:{{crdt_replica_id}} - Redis {{redis}} ({{role}})"
    }
   ]
  },
  {
   "title": "Database Hit Ratio (hits / requests)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(bdb_read_hits{crdt_guid=\"$crdt_guid\"} + bdb_write_hits{crdt_guid=\"$crdt_guid\"}) / (bdb_read_req{crdt_guid=\"$crdt_guid\"} + bdb_write_req{crdt_guid=\"$crdt_guid\"}) > 0",
     "legendFormat": "DB hit ratio - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "Syncer lag",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "bdb_replicaof_syncer_local_ingress_lag_time{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Replica:{{crdt_replica_id}} src_id {{src_id}}"
    },
    {
     "expr": "bdb_crdt_syncer_local_ingress_lag_time{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Replica:{{crdt_replica_id}} crdt src_id {{src_id}}"
    }
   ]
  },
  {
   "title": "Database total fragmentation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (crdt_replica_id) (redis_mem_fragmentation_ratio{crdt_guid=\"$crdt_guid\"}) / count by (crdt_replica_id) (redis_mem_fragmentation_ratio{crdt_guid=\"$crdt_guid\"})",
     "legendFormat": "redis_mem_fragmentation_ratio - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "sum by (crdt_replica_id) (redis_allocator_active{crdt_guid=\"$crdt_guid\"}) / sum by (crdt_replica_id) (redis_allocator_allocated{crdt_guid=\"$crdt_guid\"})",
     "legendFormat": "Shard allocator fragmentation - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "sum by (crdt_replica_id) (redis_allocator_resident{crdt_guid=\"$crdt_guid\"}) / sum by (crdt_replica_id) (redis_allocator_active{crdt_guid=\"$crdt_guid\"})",
     "legendFormat": "shard allocator rss - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "Shard allocator fragmentation % (defraggable)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "redis_allocator_active{crdt_guid=\"$crdt_guid\"} / redis_allocator_allocated{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Replica:{{crdt_replica_id}} - redis:{{redis}} role:{{role}}"
    }
   ]
  },
  {
   "title": "Database sum redis active defrag running",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "redis_active_defrag_running{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Replica:{{crdt_replica_id}} - redis:{{redis}} role:{{role}}"
    }
   ]
  },
  {
   "title": "Delayed fsync - (events / $aggregation)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(redis_aof_delayed_fsync{crdt_guid=\"$crdt_guid\"}[$aggregation])",
     "legendFormat": "Replica:{{crdt_replica_id}} - Redis {{redis}} ({{role}})"
    }
   ]
  },
  {
   "title": "Shard allocator fragmentation bytes (defraggable)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_allocator_active{crdt_guid=\"$crdt_guid\"} - redis_allocator_allocated{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Replica:{{crdt_replica_id}} - redis:{{redis}} role:{{role}}"
    }
   ]
  },
  {
   "title": "Number of Tombstones",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_crdt_ts_key_headers{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Replica:{{crdt_replica_id}} - redis:{{redis}}, role: {{role}}, node:{{node}}, slots:{{slots}}"
    }
   ]
  },
  { "title": "CRDT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "bdb_crdt_syncer_status: [ in-sync: 0,   syncing: 1,   out-of-sync: 2 ]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "none", "label": "state" }
   ],
   "targets": [
    {
     "expr": "bdb_crdt_syncer_status{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "redis_crdt_peer_peer_state != 1.  [ initialized: 0, online: 1, wait_fullsync: 2, fullsync: 3, fullsync_ack: 4, closed: 5 ]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "none", "label": "status" }
   ],
   "targets": [
    {
     "expr": "redis_crdt_peer_peer_state{crdt_guid=\"$crdt_guid\"} != 1",
     "legendFormat": "Replica:{{crdt_replica_id}} - redis:{{redis}}"
    }
   ]
  },
  {
   "title": "redis_crdt_stale_replica , redis_crdt_oom_latch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "redis_crdt_stale_replica{crdt_guid=\"$crdt_guid\"} > 0",
     "legendFormat": "stale - Replica:{{crdt_replica_id}} - redis:{{redis}}"
    },
    {
     "expr": "redis_crdt_oom_latch{crdt_guid=\"$crdt_guid\"} > 0",
     "legendFormat": "oom - Replica:{{crdt_replica_id}} - redis:{{redis}}"
    }
   ]
  },
  {
   "title": "CRDT GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum by (crdt_replica_id) (delta(redis_crdt_gc_attempted{crdt_guid=\"$crdt_guid\"}[1m]))",
     "legendFormat": "crdt_gc_attempted - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "sum by (crdt_replica_id) (delta(redis_crdt_gc_collected{crdt_guid=\"$crdt_guid\"}[1m]))",
     "legendFormat": "crdt_gc_collected - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "sum by (crdt_replica_id) (redis_crdt_gc_pending{crdt_guid=\"$crdt_guid\"})",
     "legendFormat": "gc pending - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  { "title": "Syncer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "replica min/max ops lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "min by (crdt_replica_id) (redis_crdt_replica_min_ops_lag{crdt_guid=\"$crdt_guid\"})",
     "legendFormat": "min lag - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "max by (crdt_replica_id) (redis_crdt_replica_max_ops_lag{crdt_guid=\"$crdt_guid\"})",
     "legendFormat": "max lag - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "GC ops lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (crdt_replica_id) (bdb_crdt_syncer_pending_local_writes_max{crdt_guid=\"$crdt_guid\"})",
     "legendFormat": "bdb1 max local writes - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "min by (crdt_replica_id) (bdb_crdt_syncer_pending_local_writes_min{crdt_guid=\"$crdt_guid\"})",
     "legendFormat": "bdb1 min local writes - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "crdt_syncer_local_ingress_lag_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "bdb_crdt_syncer_local_ingress_lag_time{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "syncer_local_ingress_lag_time - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "bdb_crdt_syncer_ingress_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "bdb_crdt_syncer_ingress_bytes{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "bdb_crdt_syncer_ingress_bytes - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  { "title": "ROF Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "BDB (ROF) used RAM for",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bdb_used_ram{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "bdb_used_ram - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_ram_limit{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "limit (when low, near used) - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "DB ram hit ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 96 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(bdb_big_fetch_ram{crdt_guid=\"$crdt_guid\"} + bdb_big_write_ram{crdt_guid=\"$crdt_guid\"} + bdb_big_del_ram{crdt_guid=\"$crdt_guid\"}) / (bdb_big_fetch_flash{crdt_guid=\"$crdt_guid\"} + bdb_big_write_flash{crdt_guid=\"$crdt_guid\"} + bdb_big_del_flash{crdt_guid=\"$crdt_guid\"} + bdb_big_fetch_ram{crdt_guid=\"$crdt_guid\"} + bdb_big_write_ram{crdt_guid=\"$crdt_guid\"} + bdb_big_del_ram{crdt_guid=\"$crdt_guid\"}) > 0",
     "legendFormat": "DB ram hit ratio - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_big_fetch_ram{crdt_guid=\"$crdt_guid\"}  / (bdb_big_fetch_flash{crdt_guid=\"$crdt_guid\"}  + bdb_big_fetch_ram{crdt_guid=\"$crdt_guid\"} ) > 0",
     "legendFormat": "read hit ratio - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_big_write_ram{crdt_guid=\"$crdt_guid\"}  / (bdb_big_write_flash{crdt_guid=\"$crdt_guid\"}  + bdb_big_write_ram{crdt_guid=\"$crdt_guid\"} ) > 0",
     "legendFormat": "write hit ratio - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_big_del_ram{crdt_guid=\"$crdt_guid\"}  / (bdb_big_del_flash{crdt_guid=\"$crdt_guid\"}  + bdb_big_del_ram{crdt_guid=\"$crdt_guid\"} ) > 0",
     "legendFormat": "del hit ratio - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "BDB RAM:Flash access ratio",
   "type": "graph",
   "description": "Positive is RAM, Negative is Flash",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 96 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by (crdt_replica_id) (delta(redis_big_io_ratio_redis{crdt_guid=\"$crdt_guid\",role=\"master\"}[1m]))/60",
     "legendFormat": "RAM Ops for Redis - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "avg by (crdt_replica_id) (delta(redis_big_io_ratio_flash{crdt_guid=\"$crdt_guid\",role=\"master\"}[1m]) * -1)/60",
     "legendFormat": "Flash Ops for Redis - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "avg by (crdt_replica_id) (delta(redis_big_user_io_ratio_redis{crdt_guid=\"$crdt_guid\",role=\"master\"}[1m]))/60",
     "legendFormat": "User RAM Ops for Redis - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "avg by (crdt_replica_id) (delta(redis_big_user_io_ratio_flash{crdt_guid=\"$crdt_guid\",role=\"master\"}[1m]) * -1)/60",
     "legendFormat": "User Flash Ops for Redis - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "RAM:Flash access ratio",
   "type": "graph",
   "description": "Positive is RAM, Negative is Flash",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "delta(redis_big_io_ratio_redis{crdt_guid=\"$crdt_guid\"}[1m])/60",
     "legendFormat": "RAM Ops for Redis - Replica:{{crdt_replica_id}} - redis:{{redis}}"
    },
    {
     "expr": "delta(redis_big_io_ratio_flash{crdt_guid=\"$crdt_guid\"}[1m]) / -60",
     "legendFormat": "Flash Ops for Redis - Replica:{{crdt_replica_id}} - redis:{{redis}}"
    }
   ]
  },
  {
   "title": "Flash IO Banwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 104 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bdb_bigstore_io_read_bytes{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Reads - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_bigstore_io_write_bytes{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Writes - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "Flash IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bdb_bigstore_io_reads{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Reads - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_bigstore_io_writes{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Writes - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_bigstore_io_dels{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Deletes - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "BDB sum redis wait busy key / $aggregation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (crdt_replica_id) (delta(redis_wait_busy_key{crdt_guid=\"$crdt_guid\"}[$aggregation]))",
     "legendFormat": "Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "BDB sum redis blocking reads / $aggregation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (crdt_replica_id) (delta(redis_blocking_reads{crdt_guid=\"$crdt_guid\"}[$aggregation]))",
     "legendFormat": "Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "BDB used flash",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 112 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bdb_used_bigstore{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "used - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_used_bigstore{crdt_guid=\"$crdt_guid\"} * bdb_disk_frag_ratio{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "actual - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_disk_frag_ratio{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "frag ratio - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "BDB postponed clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bdb_big_postponed_clients{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "BDB blocked clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bdb_big_blocked_clients{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Number of blocked clients - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "BDB ram overhead",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 120 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(bdb_ram_overhead{crdt_guid=\"$crdt_guid\"} - bdb_mem_not_counted_for_evict{crdt_guid=\"$crdt_guid\"}) / bdb_ram_limit{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Total Ratio - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "(redis_ram_overhead{crdt_guid=\"$crdt_guid\"} - redis_mem_clients_slaves{crdt_guid=\"$crdt_guid\"} - redis_mem_aof_buffer{crdt_guid=\"$crdt_guid\"}) / redis_max_ram{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Replica:{{crdt_replica_id}} - redis: {{redis}} role:{{role}}"
    }
   ]
  },
  {
   "title": "BDB sum redis blocking writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (crdt_replica_id) (rate(redis_blocking_writes{crdt_guid=\"$crdt_guid\"}[1m]))",
     "legendFormat": "Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "BDB sum redis big inst avg read io queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (crdt_replica_id) (redis_big_inst_avg_read_io_queue{crdt_guid=\"$crdt_guid\"})",
     "legendFormat": "Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "BDB sum redis big inst avg write io queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (crdt_replica_id) (redis_big_inst_avg_write_io_queue{crdt_guid=\"$crdt_guid\"})",
     "legendFormat": "Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "BDB objects(values) in FLASH",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bdb_bigstore_objs_flash{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "objects in flash (sum of all master shards) - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "bdb_bigstore_objs_ram{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "objects in ram (sum of all master shards) - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "BDB % values in RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 136 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "bdb_bigstore_objs_ram{crdt_guid=\"$crdt_guid\"} / bdb_no_of_keys{crdt_guid=\"$crdt_guid\"} ",
     "legendFormat": "BDB % values in RAM (masters) - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "avg((max(redis_bigdb0_ram{crdt_guid=\"$crdt_guid\",role=\"master\"} or redis_bigdb_ram{crdt_guid=\"$crdt_guid\",role=\"master\"}) by (redis,bdb,crdt_replica_id)) / on (redis,bdb,crdt_replica_id) redis_db0_keys{crdt_guid=\"$crdt_guid\",role=\"master\"})",
     "legendFormat": "average master shard % values in RAM - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "avg((max(redis_bigdb0_ram{crdt_guid=\"$crdt_guid\",role=\"slave\"} or redis_bigdb_ram{crdt_guid=\"$crdt_guid\",role=\"slave\"}) by (redis,bdb,crdt_replica_id)) / on (redis,bdb,crdt_replica_id) redis_db0_keys{crdt_guid=\"$crdt_guid\",role=\"slave\"})",
     "legendFormat": "average slave shard % values in RAM - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "topk(1, min((max(redis_bigdb0_ram{crdt_guid=\"$crdt_guid\",role=\"master\"} or redis_bigdb_ram{crdt_guid=\"$crdt_guid\",role=\"master\"}) by (redis,bdb,crdt_replica_id)) / on (redis,bdb,cluster) redis_db0_keys{crdt_guid=\"$crdt_guid\",role=\"master\"}) by (redis) * -1) *-1",
     "legendFormat": "lowest master shard % values in RAM - redsi:{{redis}} - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "topk(1, min((max(redis_bigdb0_ram{crdt_guid=\"$crdt_guid\",role=\"slave\"} or redis_bigdb_ram{crdt_guid=\"$crdt_guid\",role=\"slave\"}) by (redis,bdb,crdt_replica_id)) / on (redis,bdb,cluster) redis_db0_keys{crdt_guid=\"$crdt_guid\",role=\"slave\"}) by (redis) * -1) *-1",
     "legendFormat": "lowest slave shard % values in RAM - redsi:{{redis}} - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "Shard objects(values) in RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(max(redis_bigdb0_ram{crdt_guid=\"$crdt_guid\",role=\"slave\"} or redis_bigdb_ram{crdt_guid=\"$crdt_guid\",role=\"slave\"}) by (redis,bdb,crdt_replica_id))",
     "legendFormat": "average number of values in ram per slave shard - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "avg(max(redis_bigdb0_ram{crdt_guid=\"$crdt_guid\",role=\"master\"} or redis_bigdb_ram{crdt_guid=\"$crdt_guid\",role=\"master\"}) by (redis,bdb,crdt_replica_id))",
     "legendFormat": "average number of values in ram per master shard - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "topk(1, min(max(redis_bigdb0_ram{crdt_guid=\"$crdt_guid\",role=\"slave\"} or redis_bigdb_ram{crdt_guid=\"$crdt_guid\",role=\"slave\"}) by (redis,bdb,crdt_replica_id) < on(crdt_replica_id,bdb,redis) redis_db0_keys{crdt_guid=\"$crdt_guid\",role=\"slave\"} ) by (bdb, redis,crdt_replica_id) * -1) * -1",
     "legendFormat": "lowest number of values in ram per slave shard - redis:{{redis}} - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "topk(1, min(max(redis_bigdb0_ram{crdt_guid=\"$crdt_guid\",role=\"master\"} or redis_bigdb_ram{crdt_guid=\"$crdt_guid\",role=\"master\"}) by (redis,bdb,crdt_replica_id) < on(crdt_replica_id,bdb,redis) redis_db0_keys{crdt_guid=\"$crdt_guid\",role=\"master\"}) by (bdb, redis,crdt_replica_id) * -1) * -1",
     "legendFormat": "lowest number of values in ram per master shard  - redis:{{redis}} - Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "BDB dirty RAM evictions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bdb_big_ram_dirty_evictions{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "BDB clean RAM evictions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bdb_big_ram_clean_evictions{crdt_guid=\"$crdt_guid\"}",
     "legendFormat": "Replica:{{crdt_replica_id}}"
    }
   ]
  },
  {
   "title": "RocksDB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (crdt_replica_id) (delta(redis_rocks_comp_started{crdt_guid=\"$crdt_guid\"}[1m]))",
     "legendFormat": "compactions - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "sum by (crdt_replica_id) (delta(redis_rocks_flush_started{crdt_guid=\"$crdt_guid\"}[1m]))",
     "legendFormat": "flushes - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "sum by (crdt_replica_id) (delta(redis_rocks_flush_writes_slowdown{crdt_guid=\"$crdt_guid\"}[$aggregation]))",
     "legendFormat": "slowdowns / $aggregation - Replica:{{crdt_replica_id}}"
    },
    {
     "expr": "sum by (crdt_replica_id) (delta(redis_rocks_flush_writes_stop{crdt_guid=\"$crdt_guid\"}[$aggregation]))",
     "legendFormat": "stalls / $aggregation - Replica:{{crdt_replica_id}}"
    }
   ]
  }
 ]
}