{
 "title": "Cluster Databases",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(bdb_up,cluster)" } },
   {
    "name": "bdb",
    "label": "bdb",
    "query": {
     "query": "bdb_conns{cluster=\"$cluster\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Shards: $bdb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "bdb" },
  {
   "title": "Main System/User CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "bdb_main_thread_cpu_system{bdb=\"$bdb\"}",
     "legendFormat": "system"
    },
    {
     "expr": "bdb_main_thread_cpu_user{bdb=\"$bdb\"}",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "bdb_used_memory{bdb=\"$bdb\"}",
     "legendFormat": "{{bdb_name}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "bdb_total_req{bdb=\"$bdb\"}",
     "legendFormat": "{{bdb_name}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "bdb_avg_latency{bdb=\"$bdb\"}",
     "legendFormat": "{{database}}"
    }
   ]
  }
 ]
}