{
 "title": "Cluster Node CPU",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(node_up,cluster)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_up{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(node_up{cluster=\"$cluster\",node=\"$node\"}, cnm_version)"
    }
   },
   {
    "name": "aggregation",
    "label": "interval aggregation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage on Node $node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "percents" }
   ],
   "targets": [
    {
     "expr": " node_cpu_user{cluster=\"$cluster\", node=\"$node\"} + node_cpu_system{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "user+system"
    },
    {
     "expr": "1- node_cpu_idle{cluster=\"$cluster\", node=\"$node\"} - node_cpu_system{cluster=\"$cluster\", node=\"$node\"} - node_cpu_user{cluster=\"$cluster\", node=\"$node\"} unless node_cpu_nice{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "other"
    },
    {
     "expr": "dmcproxy_process_cpu_usage_percent{cluster=\"$cluster\", node=\"$node\"}/100",
     "legendFormat": "dmcproxy (100% = 1 core)"
    },
    {
     "expr": "sum(redis_process_cpu_usage_percent{cluster=\"$cluster\", node=\"$node\"}/100)",
     "legendFormat": "shards (100% = 1 core)"
    }
   ]
  },
  {
   "title": "CPU Median Usage on Node $node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "percents" }
   ],
   "targets": [
    {
     "expr": " node_cpu_user_median{cluster=\"$cluster\", node=\"$node\"} + node_cpu_system_median{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "user+system"
    },
    {
     "expr": "1- node_cpu_idle_median{cluster=\"$cluster\", node=\"$node\"} - node_cpu_system_median{cluster=\"$cluster\", node=\"$node\"} - node_cpu_user_median{cluster=\"$cluster\", node=\"$node\"} unless node_cpu_nice_median{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "other"
    },
    {
     "expr": "dmcproxy_process_cpu_usage_percent{cluster=\"$cluster\", node=\"$node\"}/100",
     "legendFormat": "dmcproxy (100% = 1 core)"
    },
    {
     "expr": "sum(redis_process_cpu_usage_percent{cluster=\"$cluster\", node=\"$node\"}/100)",
     "legendFormat": "shards (100% = 1 core)"
    }
   ]
  },
  {
   "title": "CPU Max Usage on Node $node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "percents" }
   ],
   "targets": [
    {
     "expr": " node_cpu_user_max{cluster=\"$cluster\", node=\"$node\"} + node_cpu_system_max{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "user+system"
    },
    {
     "expr": "1- node_cpu_idle_max{cluster=\"$cluster\", node=\"$node\"} - node_cpu_system_max{cluster=\"$cluster\", node=\"$node\"} - node_cpu_user_max{cluster=\"$cluster\", node=\"$node\"} unless node_cpu_nice_max{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "other"
    },
    {
     "expr": "dmcproxy_process_cpu_usage_percent{cluster=\"$cluster\", node=\"$node\"}/100",
     "legendFormat": "dmcproxy (100% = 1 core)"
    },
    {
     "expr": "sum(redis_process_cpu_usage_percent{cluster=\"$cluster\", node=\"$node\"}/100)",
     "legendFormat": "shards (100% = 1 core)"
    }
   ]
  },
  {
   "title": "CPU Min Usage on Node $node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "percents" }
   ],
   "targets": [
    {
     "expr": " node_cpu_user_min{cluster=\"$cluster\", node=\"$node\"} + node_cpu_system_min{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "user+system"
    },
    {
     "expr": "1- node_cpu_idle_min{cluster=\"$cluster\", node=\"$node\"} - node_cpu_system_min{cluster=\"$cluster\", node=\"$node\"} - node_cpu_user_min{cluster=\"$cluster\", node=\"$node\"} unless node_cpu_nice_min{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "other"
    },
    {
     "expr": "dmcproxy_process_cpu_usage_percent{cluster=\"$cluster\", node=\"$node\"}/100",
     "legendFormat": "dmcproxy (100% = 1 core)"
    },
    {
     "expr": "sum(redis_process_cpu_usage_percent{cluster=\"$cluster\", node=\"$node\"}/100)",
     "legendFormat": "shards (100% = 1 core)"
    }
   ]
  }
 ]
}