{
 "title": "Cluster Node Latency",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(node_up,cluster)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_up{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(node_up{cluster=\"$cluster\",node=\"$node\"}, cnm_version)"
    }
   },
   {
    "name": "aggregation",
    "label": "interval aggregation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Latency on Node $node",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "node_avg_latency{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Listener Latency",
   "type": "graph",
   "description": "display the egress and ingress traffic on the node's NIC",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s", "label": "Egress bytes/sec " }
   ],
   "targets": [
    {
     "expr": "listener_acc_read_latency{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "listener read latency node {{node}}"
    },
    {
     "expr": "listener_acc_write_latency{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "listener write latency for node {{node}}"
    },
    {
     "expr": "listener_acc_other_latency{cluster=\"$cluster\", node=\"$node\"} ",
     "legendFormat": "listener other latency for node {{node}}"
    }
   ]
  },
  {
   "title": "Cache Hits/Misses",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(redis_keyspace_read_hits{node=\"$node\", cluster=\"$cluster\"}[1m])",
     "legendFormat": "read hits"
    },
    {
     "expr": "rate(redis_keyspace_read_misses{node=\"$node\", cluster=\"$cluster\"}[$aggregation])",
     "legendFormat": "read misses"
    },
    {
     "expr": "rate(redis_keyspace_write_hits{node=\"$node\", cluster=\"$cluster\"}[$aggregation])",
     "legendFormat": "write hits"
    },
    {
     "expr": "rate(redis_keyspace_write_misses{node=\"$node\", cluster=\"$cluster\"}[$aggregation])",
     "legendFormat": "write misses"
    }
   ]
  },
  {
   "title": "Expired/Evicted Keys",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "redis_evicted_keys{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "expired"
    },
    {
     "expr": "redis_expired_keys{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "evicted"
    }
   ]
  }
 ]
}