{
 "title": "Cluster Node Requests",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(node_up,cluster)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_up{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(node_up{cluster=\"$cluster\",node=\"$node\"}, cnm_version)"
    }
   },
   {
    "name": "aggregation",
    "label": "interval aggregation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Node Traffic",
   "type": "graph",
   "description": "display the egress and ingress traffic on the node's NIC",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Egress bytes/sec " }
   ],
   "targets": [
    {
     "expr": "node_ingress_bytes{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "Ingress for node {{node}}"
    },
    {
     "expr": "node_egress_bytes{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "egress for node {{node}}"
    }
   ]
  },
  {
   "title": "Input/Output",
   "type": "graph",
   "description": "display the egress and ingress traffic on the node's NIC",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Egress bytes/sec " }
   ],
   "targets": [
    {
     "expr": "redis_total_net_input_bytes{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "input for node {{node}}"
    },
    {
     "expr": "redis_total_net_output_bytes{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "output for node {{node}}"
    }
   ]
  },
  {
   "title": "Network Clients of Node $node",
   "type": "graph",
   "description": "display the egress and ingress traffic on the node's NIC",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Egress bytes/sec " }
   ],
   "targets": [
    {
     "expr": "redis_connected_clients{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "Connected clients"
    },
    {
     "expr": "redis_blocked_clients{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "Blocked clients "
    }
   ]
  },
  {
   "title": "Request/Response",
   "type": "graph",
   "description": "display the egress and ingress traffic on the node's NIC",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Egress bytes/sec " }
   ],
   "targets": [
    {
     "expr": "bdb_total_req{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "requests node {{node}}"
    },
    {
     "expr": "bdb_total_res{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "responses node {{node}}"
    }
   ]
  }
 ]
}