{
 "title": "Cluster Database CPU",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(node_up,cluster)" } },
   {
    "name": "version",
    "query": {
     "query": "label_values(node_up{cluster=\"$cluster\",node=\"$node\"}, cnm_version)"
    }
   },
   {
    "name": "bdb",
    "label": "database",
    "query": {
     "query": "bdb_conns{cluster=\"$cluster\"}"
    }
   },
   {
    "name": "aggregation",
    "label": "interval aggregation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Main Thread",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit", "label": "percents" }
   ],
   "targets": [
    {
     "expr": "bdb_main_thread_cpu_system{bdb=\"$bdb\"}",
     "legendFormat": "system"
    },
    {
     "expr": "bdb_main_thread_cpu_user{bdb=\"$bdb\"}",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Shard CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit", "label": "percents" }
   ],
   "targets": [
    {
     "expr": " bdb_shard_cpu_system{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "system"
    },
    {
     "expr": " bdb_shard_cpu_user{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Fork CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit", "label": "percents" }
   ],
   "targets": [
    {
     "expr": "bdb_fork_cpu_system{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "system"
    },
    {
     "expr": "bdb_fork_cpu_user{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Max Usages",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit", "label": "percents" }
   ],
   "targets": [
    {
     "expr": "bdb_main_thread_cpu_system_max{cluster=\"$cluster\", bdb=\"$bdb\"} + bdb_main_thread_cpu_user_max{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "main thread"
    },
    {
     "expr": "bdb_shard_cpu_system_max{cluster=\"$cluster\", bdb=\"$bdb\"} + bdb_shard_cpu_user_max{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "shard"
    },
    {
     "expr": "bdb_fork_cpu_system_max{cluster=\"$cluster\", bdb=\"$bdb\"} + bdb_fork_cpu_user_max{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "fork"
    }
   ]
  }
 ]
}