{
 "title": "Cluster Database Requests",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(node_up,cluster)" } },
   {
    "name": "version",
    "query": {
     "query": "label_values(node_up{cluster=\"$cluster\",node=\"$node\"}, cnm_version)"
    }
   },
   {
    "name": "bdb",
    "label": "database",
    "query": {
     "query": "bdb_conns{cluster=\"$cluster\"}"
    }
   },
   {
    "name": "aggregation",
    "label": "interval aggregation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops", "label": "percents" }
   ],
   "targets": [
    {
     "expr": "bdb_read_req{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "read"
    },
    {
     "expr": "bdb_write_req{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "write"
    },
    {
     "expr": "bdb_other_req{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops", "label": "percents" }
   ],
   "targets": [
    {
     "expr": "bdb_read_res{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "read"
    },
    {
     "expr": "bdb_write_res{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "write"
    },
    {
     "expr": "bdb_other_res{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "Hits",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops", "label": "percents" }
   ],
   "targets": [
    {
     "expr": " bdb_read_hits{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "read"
    },
    {
     "expr": " bdb_write_hits{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Misses",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops", "label": "percents" }
   ],
   "targets": [
    {
     "expr": " bdb_read_misses{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "read"
    },
    {
     "expr": " bdb_write_misses{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "write"
    }
   ]
  }
 ]
}