{
 "title": "Database Status - Extended Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_metrics_up,cluster)"
    }
   },
   { "name": "subscription", "query": { "query": "" } },
   {
    "name": "bdb",
    "label": "database",
    "query": {
     "query": "bdb_conns{cluster=\"$cluster\"}"
    }
   },
   {
    "name": "status",
    "query": {
     "query": "label_values(bdb_status{bdb=\"$bdb\", cluster=\"$cluster\"}, status)"
    }
   },
   {
    "name": "newStatus",
    "query": {
     "query": "label_values(bdb_up{bdb=\"$bdb\", cluster=\"$cluster\"}, status)"
    }
   },
   {
    "name": "aggregation",
    "label": "aggregation interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "databaseId", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "bdb_avg_read_latency{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "bdb_avg_write_latency{bdb=\"$bdb\",cluster=\"$cluster\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bdb_used_memory{cluster=\"$cluster\", bdb=\"$bdb\"}/bdb_memory_limit{cluster=\"$cluster\",bdb=\"$bdb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Operations",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bdb_total_req{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "bdb_read_req{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "read"
    },
    {
     "expr": "bdb_write_req{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "write"
    },
    {
     "expr": "bdb_other_req{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(bdb_conns{bdb=\"$bdb\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "System CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bdb_main_thread_cpu_system{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 } },
  {
   "title": "Modules",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "columns": [
      { "selector": "name", "text": "Name", "type": "string" },
      { "selector": "version", "text": "Version", "type": "string" }
     ],
     "global_query_id": "bdb-config",
     "json_options": {
      "columnar": false,
      "root_is_not_array": false
     },
     "parser": "backend",
     "root_selector": "modules",
     "source": "url",
     "type": "json",
     "url": "https://api.redislabs.com/v1/subscriptions/$subscription/databases/$bdb",
     "url_options": {
      "data": "",
      "headers": [
       { "key": "accept", "value": "application/json" },
       {
        "key": "x-api-key",
        "value": "Armjlu9edjsq139bw4vz628sm5z0wc1isj8pkr91px5pukazxn"
       },
       {
        "key": "x-api-secret-key",
        "value": "S5nfcb3bu7xecok4psfx32e8x2ffgi6su4borw6ai6bpbsbweb3"
       }
      ],
      "method": "GET"
     }
    }
   ]
  },
  {
   "title": "Key Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(bdb_no_of_keys{bdb=\"$bdb\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "User CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bdb_main_thread_cpu_user{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Expired Keys",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bdb_expired_objects{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "Expired Keys"
    }
   ]
  },
  {
   "title": "Total Misses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bdb_read_misses + bdb_write_misses{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Configuration",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "columns": [
      { "selector": "replication", "text": "1. Replication", "type": "string" },
      { "selector": "dataPersistence", "text": "2. Persistence", "type": "string" },
      { "selector": "backup.enableRemoteBackup", "text": "3. Backup", "type": "string" },
      { "selector": "dataEvictionPolicy", "text": "4. Eviction", "type": "string" },
      { "selector": "protocol", "text": "5. Protocol", "type": "string" }
     ],
     "global_query_id": "bdb-config",
     "json_options": {
      "columnar": false
     },
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "https://api.redislabs.com/v1/subscriptions/$subscription/databases/$bdb",
     "url_options": {
      "data": "",
      "headers": [
       { "key": "accept", "value": "application/json" },
       {
        "key": "x-api-key",
        "value": "Armjlu9edjsq139bw4vz628sm5z0wc1isj8pkr91px5pukazxn"
       },
       {
        "key": "x-api-secret-key",
        "value": "S5nfcb3bu7xecok4psfx32e8x2ffgi6su4borw6ai6bpbsbweb3"
       }
      ],
      "method": "GET",
      "params": []
     }
    }
   ]
  }
 ]
}