{
 "title": "Cluster Dashboard",
 "tags": [ "Operations Preview" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_metrics_up,cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_metrics_up{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "db",
    "label": "db",
    "query": {
     "query": "label_values(endpoint_client_connections{cluster=\"$cluster\"},db)"
    }
   },
   {
    "name": "shard",
    "label": "shard",
    "query": {
     "query": "label_values(redis_server_up{cluster=\"$cluster\", db=\"$db\"}, redis)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_metrics_up{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (node_metrics_up{cluster=\"$cluster\"} > 0)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum (node_metrics_up{cluster=\"$cluster\"} < 1)"
    }
   ]
  },
  {
   "title": "Cluster has quorum?",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(has_quorum{cluster=\"$cluster\"}) > 0 ",
     "legendFormat": "Quorum: {{sum(has_quorum{cluster=\"$cluster\"})}}"
    },
    {
     "expr": "sum(has_quorum{cluster=\"$cluster\"}) < 1",
     "legendFormat": "nodes not in  quorum: {{sum(has_quorum{cluster=\"$cluster\"})}}"
    }
   ]
  },
  {
   "title": "#Shards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_server_used_memory{cluster=\"$cluster\", role=\"master\"})",
     "legendFormat": "Primary"
    },
    {
     "expr": "count(redis_server_connected_slaves{cluster=\"$cluster\", role=\"slave\"})",
     "legendFormat": "Replica"
    }
   ]
  },
  {
   "title": "License ",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(license_shards_limit{cluster=\"$cluster\"}) - count(redis_server_used_memory{cluster=\"$cluster\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "count(redis_server_used_memory{cluster=\"$cluster\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "OS version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (extracted_os_version) (\n  label_replace(node_os_version{cluster=\"$cluster\"}, \"extracted_os_version\", \"$1\", \"id\", \"(.*)\")\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Enterprise Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_config{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "# Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_metrics_up{cluster=\"$cluster\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "# Databases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(db_config{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Grow Over Minute (Over 100MiB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (db) (rate(redis_server_used_memory{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Database: {{db}}"
    }
   ]
  },
  {
   "title": "Cluster Master",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(is_primary{cluster=\"$cluster\"} == 1, \"node_id\", \"$1\", \"node\", \"node-(\\\\d+)\")",
     "legendFormat": "Primary"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(redis_server_used_memory{cluster=\"$cluster\"})",
     "legendFormat": "Total Used"
    },
    {
     "expr": "sum(node_available_memory_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Total Available"
    },
    {
     "expr": "sum(node_provisional_memory_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Total Provisional"
    },
    {
     "expr": "sum(node_provisional_memory_no_overbooking_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Total Provisional (No Overbooking)"
    }
   ]
  },
  {
   "title": "Total Databases Count Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count (db_status{cluster=\"$cluster\"})",
     "legendFormat": "Total databases "
    }
   ]
  },
  {
   "title": "Top 10 Memory Per Database",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10,\n  sum by (db) (\n    (\n      redis_server_used_memory{cluster=\"$cluster\", role=\"master\"}\n      * on(db, cluster) group_left\n        db_replication_factor\n    )\n    or\n    (\n      redis_server_used_memory{cluster=\"$cluster\"}\n      unless on(db, cluster) db_replication_factor\n    )\n  )\n)",
     "legendFormat": "Database: {{db}}"
    }
   ]
  },
  {
   "title": "Memory Load Over Time ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(redis_server_used_memory{cluster=\"$cluster\"}) / sum(db_memory_limit_bytes{cluster=\"$cluster\"})) * 100",
     "legendFormat": "Memory Load % "
    }
   ]
  },
  {
   "title": "Active - Allocated (Defraggable)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_server_allocator_active{cluster=\"$cluster\"} - redis_server_allocator_allocated{cluster=\"$cluster\"}",
     "legendFormat": "Database: {{db}} Redis: {{redis}}"
    }
   ]
  },
  {
   "title": "Total Shards Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(redis_server_used_memory{cluster=\"$cluster\"})",
     "legendFormat": "Total shards memory"
    },
    {
     "expr": "sum(redis_server_used_ram{cluster=\"$cluster\"})",
     "legendFormat": "Total shards ram"
    }
   ]
  },
  {
   "title": "Available Memory per node",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_available_memory_bytes{cluster=\"$cluster\"}",
     "legendFormat": "Available memory: node {{node}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "CPU Usage for node $node",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 66 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(irate(node_cpu_seconds_total{mode=\"idle\", node=\"$node\", cluster=\"$cluster\"}[$__rate_interval])) by (node))",
     "legendFormat": "total CPU utilization"
    },
    {
     "expr": "avg by (node) (irate(node_cpu_seconds_total{mode=\"idle\", node=\"$node\", cluster=\"$cluster\"}[$__rate_interval]))*100",
     "legendFormat": "idle"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\",mode=\"iowait\"}[$__rate_interval])) by (node)*100",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(namedprocess_namegroup_cpu_seconds_total{mode=~\"system|user\", cluster=\"$cluster\", node=\"$node\"}*0.0001)",
     "legendFormat": "shards (100% = 1 core)"
    },
    {
     "expr": "avg(rate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\", groupname=\"dmcproxy\"}[$__rate_interval])) by (node) ",
     "legendFormat": "dmcproxy (100% = 1 core)"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\",mode=\"nice\"}[$__rate_interval])) by (node)*100",
     "legendFormat": "nice"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Node $node: Average Disk Usage by Mount as a %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(1 - \n  node_filesystem_avail_bytes{cluster=\"$cluster\", node=\"$node\", fstype!~\"overlay|tmpfs|efivarfs\", mountpoint!=\"/boot/efi\" } \n/\n  node_filesystem_size_bytes{cluster=\"$cluster\", node=\"$node\", fstype!~\"overlay|tmpfs|efivarfs\", mountpoint!=\"/boot/efi\"}\n)",
     "legendFormat": "Mount: {{mountpoint}}"
    }
   ]
  },
  { "title": "Databases traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Top 10 Read and Write Requests Latency (P99) ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "topk(10, histogram_quantile(0.99, sum(rate(endpoint_read_requests_latency_histogram_bucket{cluster=\"$cluster\"}[1m])) by (le, db)))",
     "legendFormat": "p99_read databases: {{db}}"
    },
    {
     "expr": "topk(10, histogram_quantile(0.99, sum(rate(endpoint_write_requests_latency_histogram_bucket{cluster=\"$cluster\"}[1m])) by (le, db)))",
     "legendFormat": "p99_write databases: {{db}}"
    }
   ]
  },
  {
   "title": "Top 10 Read and Write Requests Latency (P95) ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "topk(10, histogram_quantile(0.95, sum(rate(endpoint_write_requests_latency_histogram_bucket{cluster=\"$cluster\"}[1m])) by (le, db)))",
     "legendFormat": "p95_read databases: {{db}}"
    },
    {
     "expr": "topk(10, histogram_quantile(0.95, sum(rate(endpoint_write_requests_latency_histogram_bucket{cluster=\"$cluster\"}[1m])) by (le, db)))",
     "legendFormat": "p95_write databases: {{db}}"
    }
   ]
  },
  {
   "title": "Top 10 Used Connections By Database (All Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10, sum by(db) (endpoint_conns{cluster=\"$cluster\"}))",
     "legendFormat": "Connections by database: {{db}} "
    },
    {
     "expr": "topk(10, endpoint_client_connections{cluster=\"$cluster\"} - endpoint_client_disconnections{cluster=\"$cluster\"} - endpoint_proxy_disconnections{cluster=\"$cluster\"})",
     "legendFormat": "Active endpoint client connections for database: {{db}}"
    }
   ]
  },
  {
   "title": "Top 10 Active Listeners By Requests (Read/Write/Other)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(endpoint_read_requests{cluster=\"$cluster\"}[$__rate_interval]) + rate(endpoint_write_requests{cluster=\"$cluster\"}[$__rate_interval]) + rate(endpoint_other_requests{cluster=\"$cluster\"}[$__rate_interval])) by (db, proxy))",
     "legendFormat": "listener: {{proxy}} for database: {{db}}"
    }
   ]
  },
  {
   "title": "Total Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "- sum (rate(endpoint_egress{cluster=\"$cluster\"}[$__rate_interval])) by (db) ",
     "legendFormat": "Egress for database: {{db}}"
    },
    {
     "expr": "sum (rate(endpoint_ingress{cluster=\"$cluster\"}[$__rate_interval])) by (db)",
     "legendFormat": "Ingress for database: {{db}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "Used Mem By redis for Node $node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 117 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_server_used_memory{node=\"$node\", cluster=\"$cluster\"}",
     "legendFormat": "Database: {{db}} Redis: {{redis}}"
    }
   ]
  },
  { "title": "Certificate Expiration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "Certificate Expiration",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "targets": [
    {
     "expr": "max by(filename) (\n  max_over_time(node_cert_expires_in_seconds{cluster=\"$cluster\", filename=~\"api_cert.pem| cm_cert.pem| metrics_exporter_cert.pem| proxy_cert.pem| syncer_cert.pem| trusted_ca.pem\"}[5m])\n) / 86400",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}