{
 "title": "Database Dashboard",
 "tags": [ "Operations Preview" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_metrics_up,cluster)"
    }
   },
   {
    "name": "db",
    "label": "db",
    "query": {
     "query": "label_values(endpoint_client_connections{cluster=\"$cluster\"},db)"
    }
   },
   {
    "name": "status",
    "query": {
     "query": "label_values(redis_server_up{db=\"$db\", cluster=\"$cluster\"}, status)"
    }
   },
   {
    "name": "newStatus",
    "query": {
     "query": "label_values(redis_server_up{db=\"$db\", cluster=\"$cluster\"}, status)"
    }
   },
   {
    "name": "aggregation",
    "label": "aggregation interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "crdt_guid",
    "query": {
     "query": "label_values(redis_server_up{db=\"$db\",cluster=\"$cluster\"},crdt_guid)"
    }
   },
   {
    "name": "db_name",
    "query": {
     "query": "label_values(db_config{db=\"$db\",cluster=\"$cluster\"},db_name)"
    }
   },
   {
    "name": "role",
    "query": {
     "query": "label_values(redis_server_up{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}, role)"
    }
   },
   {
    "name": "redis",
    "query": {
     "query": "label_values(redis_server_up{cluster=\"$cluster\", db=\"$db\"}, redis)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db_config{cluster=\"$cluster\", db=\"$db\"}",
     "legendFormat": "{{db_name}}"
    }
   ]
  },
  {
   "title": "Redis Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db_config{cluster=\"$cluster\", db=\"$db\"}"
    }
   ]
  },
  {
   "title": "#Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (db)(endpoint_client_connections{cluster=\"$cluster\",db=\"$db\"} - endpoint_client_disconnections{cluster=\"$cluster\", db=\"$db\"} - endpoint_proxy_disconnections{cluster=\"$cluster\", db=\"$db\"})",
     "legendFormat": "current number of active connections"
    }
   ]
  },
  {
   "title": "#Keys",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(sum by (db) (redis_server_db_keys{role=\"master\", db=\"$db\", cluster=\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Primary Shard Mapping",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "topk(1, redis_server_up{cluster=\"$cluster\", role=\"master\", db=\"$db\"}) \nby (redis, slots, node, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(db_status{cluster=\"$cluster\", db=\"$db\"})",
     "legendFormat": "Database: {{db}} status"
    }
   ]
  },
  {
   "title": "CRDT GUID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (crdt_guid)(redis_server_crdt_clock{cluster=\"$cluster\", db=\"$db\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "#Endpoints",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(endpoint_read_requests{db=\"$db\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "#Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_server_used_memory{cluster=\"$cluster\", db=\"$db\"})"
    }
   ]
  },
  {
   "title": "Avg Database Requests Latency ",
   "type": "timeseries",
   "description": "Average latency for all endpoints",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(rate(endpoint_write_requests_latency_histogram_sum{cluster=\"$cluster\", db=~\"$db.*\"}[$__rate_interval]) + rate(endpoint_read_requests_latency_histogram_sum{cluster=\"$cluster\", db=~\"$db.*\"}[$__rate_interval]) + rate(endpoint_other_requests_latency_histogram_sum{cluster=\"$cluster\", db=~\"$db.*\"}[$__rate_interval])) by (proxy, node) / avg(rate(endpoint_write_requests_latency_histogram_count{cluster=\"$cluster\", db=~\"$db.*\"}[$__rate_interval]) + rate(endpoint_read_requests_latency_histogram_count{cluster=\"$cluster\", db=~\"$db.*\"}[$__rate_interval]) + rate(endpoint_other_requests_latency_histogram_count{cluster=\"$cluster\", db=~\"$db.*\"}[$__rate_interval])) by (proxy, node)",
     "legendFormat": "proxy: {{proxy}} , node {{node}} - sum requests latency"
    },
    {
     "expr": "rate(endpoint_write_requests_latency_histogram_sum{cluster=\"$cluster\", db=~\"$db.*\"}[$__rate_interval]) / rate(endpoint_write_requests_latency_histogram_count{cluster=\"$cluster\", db=~\"$db.*\"}[$__rate_interval])",
     "legendFormat": "proxy: {{proxy}} , node {{node}} - write requests latency"
    },
    {
     "expr": "rate(endpoint_read_requests_latency_histogram_sum{cluster=\"$cluster\", db=~\"$db.*\"}[$__rate_interval]) / rate(endpoint_read_requests_latency_histogram_count{cluster=\"$cluster\", db=~\"$db.*\"}[$__rate_interval])",
     "legendFormat": "proxy: {{proxy}} , node {{node}} - read requests latency"
    },
    {
     "expr": "rate(endpoint_other_requests_latency_histogram_sum{cluster=\"$cluster\", db=~\"$db.*\"}[$__rate_interval]) / rate(endpoint_other_requests_latency_histogram_count{cluster=\"$cluster\", db=~\"$db.*\"}[$__rate_interval])",
     "legendFormat": "proxy: {{proxy}} , node {{node}} - other requests latency"
    }
   ]
  },
  {
   "title": "Avg Endpoint Requests Latency ",
   "type": "timeseries",
   "description": "Average latency per endpoint",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(\n  (\n    rate(endpoint_write_requests_latency_histogram_sum{cluster=\"$cluster\", db=~\"$db.*\", proxy=~\".*\"}[$__rate_interval])\n    +\n    rate(endpoint_read_requests_latency_histogram_sum{cluster=\"$cluster\", db=~\"$db.*\", proxy=~\".*\"}[$__rate_interval])\n    +\n    rate(endpoint_other_requests_latency_histogram_sum{cluster=\"$cluster\", db=~\"$db.*\", proxy=~\".*\"}[$__rate_interval])\n  )\n  /\n  (\n    rate(endpoint_write_requests_latency_histogram_count{cluster=\"$cluster\", db=~\"$db.*\", proxy=~\".*\"}[$__rate_interval])\n    +\n    rate(endpoint_read_requests_latency_histogram_count{cluster=\"$cluster\", db=~\"$db.*\", proxy=~\".*\"}[$__rate_interval])\n    +\n    rate(endpoint_other_requests_latency_histogram_count{cluster=\"$cluster\", db=~\"$db.*\", proxy=~\".*\"}[$__rate_interval])\n  )\n) by (proxy, node, db)\n",
     "legendFormat": "listener {{proxy}}  node {{node}} - listener_acc_latency"
    },
    {
     "expr": "(\n  sum(irate(endpoint_write_requests_latency_histogram_sum{db=\"$db\", proxy=~\".*\"}[$__rate_interval])) by (node,proxy)\n  /\n  sum(irate(endpoint_write_requests_latency_histogram_count{db=\"$db\", proxy=~\".*\"}[$__rate_interval])) by (node,proxy)\n)\n",
     "legendFormat": "listener {{proxy}}  node {{node}} - listener_acc_write_latency"
    },
    {
     "expr": "(\n  sum(irate(endpoint_read_requests_latency_histogram_sum{db=\"$db\", proxy=~\".*\"}[$__rate_interval])) by (proxy,node)\n  /\n  sum(irate(endpoint_read_requests_latency_histogram_count{db=\"$db\", proxy=~\".*\"}[$__rate_interval])) by (proxy,node)\n)\n",
     "legendFormat": "listener {{proxy}}  node {{node}} - listener_acc_read_latency"
    },
    {
     "expr": "(\n  sum(irate(endpoint_other_requests_latency_histogram_sum{db=\"$db\", proxy=~\".*\"}[$__rate_interval])) by (proxy,node)\n  /\n  sum(irate(endpoint_other_requests_latency_histogram_count{db=\"$db\", proxy=~\".*\"}[$__rate_interval])) by (proxy,node)\n)\n",
     "legendFormat": "proxy {{proxy}} node {{node}} - listener_acc_other_latency"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "description": "Used Memory - For evictions master * 2\nSum Of shards - Total used memory slave + master",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (db) (\n(\nredis_server_used_memory{cluster=\"$cluster\", role=\"master\"}\n* on(db, cluster) group_left\ndb_replication_factor\n)\nor\n(\nredis_server_used_memory{cluster=\"$cluster\"}\nunless on(db, cluster) db_replication_factor\n)\n)",
     "legendFormat": "Used Memory (Logical)"
    },
    {
     "expr": "sum(redis_server_used_memory{cluster=\"$cluster\", db=\"$db\"})",
     "legendFormat": "Used Memory Sum Of Shards"
    },
    {
     "expr": "sum by (db) (redis_server_current_cow_size{cluster=\"$cluster\", db=\"$db\"}) > 0",
     "legendFormat": "Used Memory Copy On Write"
    },
    {
     "expr": "sum by (db) (namedprocess_namegroup_memory_bytes{cluster=\"$cluster\", db=\"$db\",memtype=\"resident\"})",
     "legendFormat": "Used Memory RSS"
    },
    {
     "expr": "sum by (db) (db_memory_limit_bytes{db=\"$db\", cluster=\"$cluster\"}) and (sum by (db) (\nredis_server_used_memory{cluster=\"$cluster\", role=\"master\"}) * 3 > sum by (db) (db_memory_limit_bytes{db=\"$db\", cluster=\"$cluster\"}))",
     "legendFormat": "limit (when low, near used)"
    }
   ]
  },
  {
   "title": "Requests[total,read,write,other] ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (db) (rate(endpoint_total_req{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]))",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum by (db) (rate(endpoint_other_requests{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]))",
     "legendFormat": "Other requests"
    },
    {
     "expr": "sum by (db) (rate(endpoint_read_requests{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]))",
     "legendFormat": "Read requests"
    },
    {
     "expr": "sum by (db) (rate(endpoint_write_requests{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]))",
     "legendFormat": "Write requests"
    },
    {
     "expr": "sum by (cluster, db) (\n            rate(endpoint_read_requests{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) +\n            rate(endpoint_write_requests{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) +\n            rate(endpoint_other_requests{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])\n        )",
     "legendFormat": "Total requests (max)"
    },
    { "expr": "$max_throuput_by_db", "legendFormat": "max throughput limit" }
   ]
  },
  {
   "title": "Real-Time Ops Per Second (Instantaneous)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "redis_server_instantaneous_ops_per_sec{db=\"$db\", cluster=\"$cluster\"}",
     "legendFormat": "node: {{node}},  redis: {{redis}}, role: {{role}},  slots: {{slots}} "
    }
   ]
  },
  {
   "title": "Endpoint Ingress/Egress",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "- sum by(db) (rate(endpoint_egress{db=\"$db\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Endpoint Egress"
    },
    {
     "expr": "sum by(db) (rate(endpoint_ingress{db=\"$db\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Endpoint Ingress"
    },
    {
     "expr": "sum(rate(redis_server_total_net_input_bytes{db=\"$db\", cluster=\"$cluster\", role=\"master\"}[$__rate_interval]))",
     "legendFormat": "Master shard Ingress"
    },
    {
     "expr": "- (sum(rate(redis_server_total_net_output_bytes{db=\"$db\", cluster=\"$cluster\", role=\"master\"}[1m]) - rate(redis_server_master_repl_offset{db=\"$db\", cluster=\"$cluster\", role=\"master\"}[1m])))",
     "legendFormat": "Master shard Egress"
    },
    {
     "expr": "sum(rate(redis_server_master_repl_offset{db=\"$db\", cluster=\"$cluster\", role=\"master\"}[1m]))",
     "legendFormat": "Master shard replication"
    },
    {
     "expr": "sum(rate(redis_server_repl_touch_bytes{db=\"$db\", cluster=\"$cluster\", role=\"master\"}[1m]))!=0",
     "legendFormat": "Master shard repl touch"
    }
   ]
  },
  {
   "title": "Connection Overview",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "conn" } },
   "targets": [
    {
     "expr": "sum(endpoint_client_connections{cluster=\"$cluster\", db=\"$db\"} - endpoint_client_disconnections{cluster=\"$cluster\", db=\"$db\"} )",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(endpoint_client_connections{cluster=\"$cluster\", db=\"$db\"} - endpoint_client_disconnections{cluster=\"$cluster\", db=\"$db\"} ) by (proxy, node)",
     "legendFormat": "endpoint {{proxy}} node: {{node}}"
    },
    {
     "expr": "rate(endpoint_client_connections{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])",
     "legendFormat": "connections rate per minute for db:$db - node: {{node}}"
    },
    {
     "expr": "rate(endpoint_client_disconnections{cluster=\"$cluster\", db=\"$db\"} [$__rate_interval])",
     "legendFormat": "disconnections rate per minute for db:$db - node: {{node}}"
    }
   ]
  },
  {
   "title": "CPU Usage Per  Shards",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\",db=\"$db\", mode=\"user\"}[60s])*100) by (groupname, redis, role, node)",
     "legendFormat": "user: redis: {{redis}} role: {{role}} node:{{node}}"
    },
    {
     "expr": "sum(rate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\",db=\"$db\", mode=\"system\"}[60s])*100) by (groupname, redis, role, node)",
     "legendFormat": "system: redis: {{redis}} role: {{role}} node:{{node}}"
    }
   ]
  },
  {
   "title": "Memory Utilization Per Shard",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_server_used_memory{cluster=\"$cluster\", db=\"$db\"}",
     "legendFormat": "Memory Usage redis: {{redis}} role: {{role}}"
    },
    {
     "expr": "redis_server_current_cow_size{cluster=\"$cluster\", db=\"$db\"} > 0",
     "legendFormat": "Memory Usage Copy On Write - redis: {{redis}} role: {{role}}"
    }
   ]
  },
  { "title": "Keyspace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Key Size Distribution (Bar Gauge)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (db) (redis_server_strings_sizes_under_128M{role=\"master\", db=\"$db\", cluster=\"$cluster\"})",
     "legendFormat": "Strings <128MB"
    },
    {
     "expr": "sum by (db) (redis_server_strings_sizes_under_128M_to_512M{role=\"master\", db=\"$db\", cluster=\"$cluster\"})",
     "legendFormat": "Strings 128–512MB"
    },
    {
     "expr": "sum by (db) (redis_server_strings_sizes_over_512M{role=\"master\", db=\"$db\", cluster=\"$cluster\"})",
     "legendFormat": "Strings >512MB"
    },
    {
     "expr": "sum by (db) (redis_server_hashes_items_under_1M{role=\"master\", db=\"$db\", cluster=\"$cluster\"})",
     "legendFormat": "Hashes <1M"
    },
    {
     "expr": "sum by (db) (redis_server_hashes_items_under_1M_to_8M{role=\"master\", db=\"$db\", cluster=\"$cluster\"})",
     "legendFormat": "Hashes 1M–8M"
    },
    {
     "expr": "sum by (db) (redis_server_hashes_items_over_8M{role=\"master\", db=\"$db\", cluster=\"$cluster\"})",
     "legendFormat": "Hashes >8M"
    },
    {
     "expr": "sum by (db) (redis_server_lists_items_under_1M{role=\"master\", db=\"$db\", cluster=\"$cluster\"})",
     "legendFormat": "Lists <1M"
    },
    {
     "expr": "sum by (db) (redis_server_lists_items_under_1M_to_8M{role=\"master\", db=\"$db\", cluster=\"$cluster\"})",
     "legendFormat": "Lists 1M–8M"
    },
    {
     "expr": "sum by (db) (redis_server_lists_items_over_8M{role=\"master\", db=\"$db\", cluster=\"$cluster\"})",
     "legendFormat": "Lists >8M"
    },
    {
     "expr": "sum by (db) (redis_server_sets_items_under_1M{role=\"master\", db=\"$db\", cluster=\"$cluster\"})",
     "legendFormat": "Sets <1M"
    },
    {
     "expr": "sum by (db) (redis_server_sets_items_under_1M_to_8M{role=\"master\", db=\"$db\", cluster=\"$cluster\"})",
     "legendFormat": "Sets 1M–8M"
    },
    {
     "expr": "sum by (db) (redis_server_sets_items_over_8M{role=\"master\", db=\"$db\", cluster=\"$cluster\"})",
     "legendFormat": "Sets >8M"
    },
    {
     "expr": "sum by (db) (redis_server_zsets_items_under_1M{role=\"master\", db=\"$db\", cluster=\"$cluster\"})",
     "legendFormat": "ZSets <1M"
    },
    {
     "expr": "sum by (db) (redis_server_zsets_items_under_1M_to_8M{role=\"master\", db=\"$db\", cluster=\"$cluster\"})",
     "legendFormat": "ZSets 1M–8M"
    },
    {
     "expr": "sum by (db) (redis_server_zsets_items_over_8M{role=\"master\", db=\"$db\", cluster=\"$cluster\"})",
     "legendFormat": "ZSets >8M"
    }
   ]
  },
  {
   "title": "#Keys Per Shard",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_server_db_keys{db=\"$db\", cluster=\"$cluster\", redis=~\"$redis\"}",
     "legendFormat": "redis:{{redis}}, role: {{role}}, node:{{node}}, slots:{{slots}}"
    }
   ]
  },
  {
   "title": "#Keys",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (db) (redis_server_db_keys{role=\"master\", db=\"$db\", cluster=\"$cluster\"})",
     "legendFormat": "num of keys"
    },
    {
     "expr": "sum(redis_server_db_expires{db=\"$db\", cluster=\"$cluster\",role=\"master\"})",
     "legendFormat": "num of volatile keys"
    },
    {
     "expr": "sum(max(redis_server_bigdb_ram{db=\"$db\", cluster=\"$cluster\",role=\"master\"}) by (redis,db,cluster))",
     "legendFormat": "ram keys"
    },
    {
     "expr": "sum(max(redis_server_bigdb_disk{db=\"$db\", cluster=\"$cluster\",role=\"master\"}) by (redis,db,cluster))",
     "legendFormat": "disk keys"
    },
    {
     "expr": "(sum(max(redis_server_bigdb_disk{db=\"$db\", cluster=\"$cluster\",role=\"master\"}) by (redis,db,cluster)) + sum(max(redis_server_bigdb_ram{db=\"$db\", cluster=\"$cluster\",role=\"master\"} ) by (redis,db,cluster))) - sum(redis_server_db_keys{db=\"$db\", cluster=\"$cluster\",role=\"master\"})",
     "legendFormat": "overlapping keys"
    },
    {
     "expr": "sum(max(redis_server_bigdb_dirty{db=\"$db\", cluster=\"$cluster\",role=\"master\"}) by (redis,db,cluster))",
     "legendFormat": "dirty keys"
    },
    {
     "expr": "sum(max(redis_server_bigdb_clean{db=\"$db\", cluster=\"$cluster\",role=\"master\"}) by (redis,db,cluster))",
     "legendFormat": "clean keys"
    }
   ]
  },
  {
   "title": "Expired Objects",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (db) (irate(redis_server_expired_keys{role=\"master\", db=\"$db\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Expired database:$db"
    }
   ]
  },
  {
   "title": "Evicted Objects",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (db) (irate(redis_server_evicted_keys{role=\"master\", db=\"$db\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Evicted database:$db"
    },
    {
     "expr": "sum(rate(redis_server_keys_trimmed{db=\"$db\", cluster=\"$cluster\"}[1m]))!=0",
     "legendFormat": "Reshard trimmed database:$db"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "p99.9 Latency (µs) Over Time [read, write, other requests]",
   "type": "timeseries",
   "description": "Monitoring p99.9 latency trends over time using histogram buckets.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(endpoint_read_requests_latency_histogram_bucket{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) ) by (le, db)) ",
     "legendFormat": "Read"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(endpoint_write_requests_latency_histogram_bucket{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) ) by (le, db)) ",
     "legendFormat": "Write"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(endpoint_other_requests_latency_histogram_bucket{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) ) by (le, db)) ",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "p99 Latency (µs) Over Time [read, write, other requests]",
   "type": "timeseries",
   "description": "Monitoring p99 latency trends over time using histogram buckets.",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(endpoint_read_requests_latency_histogram_bucket{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) ) by (le, db))",
     "legendFormat": "Read"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(endpoint_write_requests_latency_histogram_bucket{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) ) by (le, db))",
     "legendFormat": "Write"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(endpoint_other_requests_latency_histogram_bucket{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) ) by (le, db))",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "p50 Latency (µs) Over Time [read, write, other requests]",
   "type": "timeseries",
   "description": "Monitoring p50 latency trends over time using histogram buckets.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(endpoint_read_requests_latency_histogram_bucket{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) ) by (le, db))",
     "legendFormat": "Read"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(endpoint_write_requests_latency_histogram_bucket{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) ) by (le, db))",
     "legendFormat": "Write"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(endpoint_other_requests_latency_histogram_bucket{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) ) by (le, db))",
     "legendFormat": "Other"
    }
   ]
  },
  { "title": "Connectivity ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Connections Per (master) Shard",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_server_connected_clients{db=\"$db\", cluster=\"$cluster\", role=\"master\"}",
     "legendFormat": "Redis: {{redis}}"
    },
    {
     "expr": "redis_server_maxclients{db=\"$db\", cluster=\"$cluster\"} < redis_server_connected_clients{db=\"$db\", cluster=\"$cluster\"} * 1.5",
     "legendFormat": "Redis {{redis}} maxclients"
    },
    {
     "expr": "redis_server_pubsub_clients{db=\"$db\", cluster=\"$cluster\", role=\"master\"}",
     "legendFormat": "Redis: {{redis}} pubsub clients"
    },
    {
     "expr": "redis_server_blocked_clients{db=\"$db\", cluster=\"$cluster\", role=\"master\"}",
     "legendFormat": "Redis: {{Redis}} blocked clients"
    }
   ]
  },
  {
   "title": "Hit Ratio (hits / requests)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (db) (rate(redis_server_keyspace_read_hits{role=\"master\", db=\"$db\"}[$__rate_interval])) / (sum by (db)(rate(redis_server_keyspace_read_hits{role=\"master\", db=\"$db\"}[$__rate_interval]) + rate(redis_server_keyspace_read_misses{role=\"master\", db=\"$db\"}[$__rate_interval]))) ",
     "legendFormat": "READ {{label_name}}"
    },
    {
     "expr": "sum by (db) (rate(redis_server_keyspace_write_hits{role=\"master\", db=\"$db\"}[$__rate_interval])) / (sum by (db)(rate(redis_server_keyspace_write_hits{role=\"master\", db=\"$db\"}[$__rate_interval]) + rate(redis_server_keyspace_write_misses{role=\"master\", db=\"$db\"}[$__rate_interval]))) \n",
     "legendFormat": "WRITE {{label_name}}"
    }
   ]
  },
  {
   "title": "Read/Write Hits / Misses  + Lazyfree + Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (db) (irate(redis_server_keyspace_read_misses{role=\"master\", cluster=\"$cluster\", db=\"$db\"}[1m]))",
     "legendFormat": "Read Misses"
    },
    {
     "expr": "sum by (db) (irate(redis_server_keyspace_write_misses{role=\"master\", cluster=\"$cluster\", db=\"$db\"}[1m]))",
     "legendFormat": "Write Misses"
    },
    {
     "expr": "sum by (db) (irate(redis_server_keyspace_read_hits{role=\"master\", cluster=\"$cluster\", db=\"$db\"}[1m]))",
     "legendFormat": "Read Hits"
    },
    {
     "expr": "sum by (db) (irate(redis_server_keyspace_write_hits{role=\"master\", cluster=\"$cluster\", db=\"$db\"}[1m]))",
     "legendFormat": "Write Hits"
    },
    {
     "expr": "delta(redis_server_lazyfreed_objects{db=\"$db\", cluster=\"$cluster\"}[60s])/60",
     "legendFormat": "Lazy Free"
    },
    {
     "expr": "delta(redis_server_total_error_replies{db=\"$db\", cluster=\"$cluster\"}[60s])/60",
     "legendFormat": "Error Replies"
    }
   ]
  },
  {
   "title": "Blocked Clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (db) (redis_server_blocked_clients{db=\"$db\",cluster=\"$cluster\"})",
     "legendFormat": "Number of blocked clients"
    }
   ]
  },
  { "title": "Memory ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Shard RSS Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": " redis_server_mem_fragmentation_ratio{db=\"$db\", cluster=\"$cluster\"} ",
     "legendFormat": "Redis {{redis}} ({{role}})"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Replication Offset Difference (Primary vs. Replica)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (db,redis) (redis_server_master_repl_offset{cluster=\"$cluster\", db=\"$db\", role=\"master\"}) - max by (db,redis) (redis_server_slave_offset{cluster=\"$cluster\", db=\"$db\", role=\"master\"})",
     "legendFormat": "Redis: {{redis}}"
    }
   ]
  },
  { "title": "Persistency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "AOF To Replica/Primary Lag Monitoring ",
   "type": "timeseries",
   "description": "This panel show the number of times an AOF fsync caused delays in the main Redis thread (inducing latency); this can indicate that the disk is slow or overloaded\nAnd the current size of AOF buffer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "sum by (db)(redis_server_aof_delayed_fsync{db=\"$db\", cluster=\"$cluster\"})",
     "legendFormat": "avg number of times fsync has been delayed"
    },
    {
     "expr": "sum by (db)(redis_server_mem_aof_buffer{db=\"$db\", cluster=\"$cluster\"})",
     "legendFormat": "size of the AOF buffer over time"
    }
   ]
  },
  {
   "title": "Delayed Fsync - (Events / $aggregation) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(redis_server_aof_delayed_fsync{db=\"$db\", cluster=\"$cluster\"}[$aggregation])",
     "legendFormat": "Redis {{redis}} ({{role}})"
    }
   ]
  }
 ]
}