{
 "title": "Latency Dashboard",
 "tags": [
  "Operations Preview",
  "Customer view"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_metrics_up,cluster)"
    }
   },
   {
    "name": "db",
    "query": {
     "query": "label_values(db_status{cluster=\"$cluster\"}, db)"
    }
   },
   {
    "name": "status",
    "query": {
     "query": "label_values(redis_server_up{db=\"$db\", cluster=\"$cluster\"}, status)"
    }
   },
   {
    "name": "newStatus",
    "query": {
     "query": "label_values(redis_server_up{db=\"$db\", cluster=\"$cluster\"}, status)"
    }
   },
   {
    "name": "redis",
    "query": {
     "query": "label_values(redis_server_up{cluster=\"$cluster\", db=\"$db\"}, redis)"
    }
   },
   {
    "name": "role",
    "query": {
     "query": "label_values(redis_server_up{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}, role)"
    }
   },
   {
    "name": "slots",
    "query": {
     "query": "label_values(redis_server_up{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}, slots)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_metrics_up{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "aggregation",
    "label": "interval aggregation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Proxy Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(rate(endpoint_read_requests_latency_histogram_sum{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) + \r\nrate(endpoint_write_requests_latency_histogram_sum{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) + \r\nrate(endpoint_other_requests_latency_histogram_sum{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])\r\n) by (db) / avg(rate(endpoint_read_requests_latency_histogram_count{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) + \r\nrate(endpoint_write_requests_latency_histogram_count{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) + \r\nrate(endpoint_other_requests_latency_histogram_count{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])\r\n) by (db)",
     "legendFormat": "database avg latency"
    },
    {
     "expr": "rate(endpoint_write_requests_latency_histogram_sum{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) /  rate(endpoint_write_requests_latency_histogram_count{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])",
     "legendFormat": "database avg write latency"
    },
    {
     "expr": "rate(endpoint_read_requests_latency_histogram_sum{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) / rate(endpoint_read_requests_latency_histogram_count{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])",
     "legendFormat": "database avg read latency"
    },
    {
     "expr": "rate(endpoint_other_requests_latency_histogram_sum{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) / rate(endpoint_other_requests_latency_histogram_count{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])",
     "legendFormat": "database avg other latency"
    },
    {
     "expr": "max_over_time((\r\n  rate(endpoint_read_requests_latency_histogram_sum{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) + \r\n  rate(endpoint_write_requests_latency_histogram_sum{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) + \r\n  rate(endpoint_other_requests_latency_histogram_sum{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])\r\n)[$aggregation:]) / max_over_time((\r\n  rate(endpoint_read_requests_latency_histogram_count{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) + \r\n  rate(endpoint_write_requests_latency_histogram_count{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) + \r\n  rate(endpoint_other_requests_latency_histogram_count{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])\r\n)[$aggregation:])",
     "legendFormat": "database avg latency max"
    }
   ]
  },
  {
   "title": "Avg Proxy Latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(rate(endpoint_write_requests_latency_histogram_sum{cluster=\"$cluster\", db=~\"$db.*\"}[$__rate_interval])) by (proxy, node, db) / avg(rate(endpoint_write_requests_latency_histogram_count{cluster=\"$cluster\", db=~\"$db.*\"}[$__rate_interval])) by (proxy, node, db)",
     "legendFormat": "listener {{proxy}}  node {{node}} - listener_acc_write_latency"
    },
    {
     "expr": "avg(rate(endpoint_read_requests_latency_histogram_sum{cluster=\"$cluster\", db=~\"$db.*\"}[$__rate_interval])) by (proxy, node, db) / avg(rate(endpoint_read_requests_latency_histogram_count{cluster=\"$cluster\", db=~\"$db.*\"}[$__rate_interval]))  by (proxy, node, db)",
     "legendFormat": "listener {{proxy}}  node {{node}} - listener_acc_read_latency"
    },
    {
     "expr": "avg(rate(endpoint_other_requests_latency_histogram_sum{cluster=\"$cluster\", db=~\"$db.*\"}[$__rate_interval])) by (proxy, node, db) / avg(rate(endpoint_other_requests_latency_histogram_count{cluster=\"$cluster\", db=~\"$db.*\"}[$__rate_interval])) by (proxy, node, db)",
     "legendFormat": "listener {{proxy}}  node {{node}} - listener_acc_other_latency"
    }
   ]
  },
  {
   "title": "p95 Latencies for Read, Write, and Other Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(endpoint_read_requests_latency_histogram_bucket{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) ) by (le, db))",
     "legendFormat": "Read"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(endpoint_write_requests_latency_histogram_bucket{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) ) by (le, db))",
     "legendFormat": "Write"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(endpoint_other_requests_latency_histogram_bucket{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) ) by (le, db))",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "p99 Latencies for Read, Write, and Other Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(endpoint_read_requests_latency_histogram_bucket{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) ) by (le, db))",
     "legendFormat": "Read"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(endpoint_write_requests_latency_histogram_bucket{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) ) by (le, db))",
     "legendFormat": "Write"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(endpoint_other_requests_latency_histogram_bucket{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) ) by (le, db))",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "p99.9 Latencies for Read, Write, and Other Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(endpoint_read_requests_latency_histogram_bucket{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) ) by (le, db))",
     "legendFormat": "Read"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(endpoint_write_requests_latency_histogram_bucket{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) ) by (le, db))",
     "legendFormat": "Write"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(endpoint_other_requests_latency_histogram_bucket{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) ) by (le, db))",
     "legendFormat": "Other"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Total CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(label_replace(\r\n  avg(rate(namedprocess_namegroup_thread_cpu_seconds_total{cluster=\"$cluster\", mode=\"system\", groupname=~\".*redis-.*\", threadname=~\".*redis-server.*\"}[$__rate_interval])) by (groupname, mode),\r\n  \"shard_number\", \"$1\", \"groupname\", \".*redis-(\\\\d+)\"\r\n)\r\n* on (shard_number) group_left(db)\r\nlabel_replace(redis_server_up{cluster=\"$cluster\", db=\"$db\",role=\"master\"}, \"shard_number\", \"$1\", \"redis\", \"(.*)\")) by (db)",
     "legendFormat": "main threads (masters) system, databases: {{db}}"
    },
    {
     "expr": "avg(label_replace(\r\n  avg(rate(namedprocess_namegroup_thread_cpu_seconds_total{cluster=\"$cluster\", mode=\"user\", groupname=~\".*redis-.*\", threadname=~\".*redis-server.*\"}[$__rate_interval])) by (groupname, mode),\r\n  \"shard_number\", \"$1\", \"groupname\", \".*redis-(\\\\d+)\"\r\n)\r\n* on (shard_number) group_left(db)\r\nlabel_replace(redis_server_up{cluster=\"$cluster\", db=\"$db\",role=\"master\"}, \"shard_number\", \"$1\", \"redis\", \"(.*)\")) by (db)",
     "legendFormat": "main threads (masters) user, databases: {{db}}"
    },
    {
     "expr": "sum(irate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\", mode=~\"system|user\",db=\"$db\"}[1m])) by (db, mode)",
     "legendFormat": "all threads (masters), databases: {{db}}"
    },
    {
     "expr": "avg(label_replace(\r\n  avg(rate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\", mode=\"user\", groupname=~\".*redis-.*\"}[$__rate_interval])) by (groupname, mode),\r\n  \"shard_number\", \"$1\", \"groupname\", \".*redis-(\\\\d+)\"\r\n)\r\n* on (shard_number) group_left(db)\r\nlabel_replace(redis_server_current_fork_perc{cluster=\"$cluster\", db=\"$db\"}, \"shard_number\", \"$1\", \"redis\", \"(.*)\")) by (db)",
     "legendFormat": "all forks (masters) - user, databases: {{db}}"
    },
    {
     "expr": "avg(label_replace(\r\n  avg(rate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\", mode=\"system\", groupname=~\".*redis-.*\"}[$__rate_interval])) by (groupname, mode),\r\n  \"shard_number\", \"$1\", \"groupname\", \".*redis-(\\\\d+)\"\r\n)\r\n* on (shard_number) group_left(db)\r\nlabel_replace(redis_server_current_fork_perc{cluster=\"$cluster\", db=\"$db\"}, \"shard_number\", \"$1\", \"redis\", \"(.*)\")) by (db)",
     "legendFormat": "all forks (masters) - system, databases: {{db}}"
    },
    {
     "expr": "max(label_replace(\r\n  avg(rate(namedprocess_namegroup_thread_cpu_seconds_total{cluster=\"$cluster\", mode=\"user\", groupname=~\".*redis-.*\", threadname=~\".*redis-server.*\"}[$__rate_interval])) by (groupname, mode),\r\n  \"shard_number\", \"$1\", \"groupname\", \".*redis-(\\\\d+)\"\r\n)\r\n* on (shard_number) group_left(db)\r\nlabel_replace(redis_server_up{cluster=\"$cluster\", db=\"$db\",role=\"master\"}, \"shard_number\", \"$1\", \"redis\", \"(.*)\")) by (db)\r\n",
     "legendFormat": "main threads max (masters) - user"
    },
    {
     "expr": "max(label_replace(\r\n  avg(rate(namedprocess_namegroup_thread_cpu_seconds_total{cluster=\"$cluster\", mode=\"system\", groupname=~\".*redis-.*\", threadname=~\".*redis-server.*\"}[$__rate_interval])) by (groupname, mode),\r\n  \"shard_number\", \"$1\", \"groupname\", \".*redis-(\\\\d+)\"\r\n)\r\n* on (shard_number) group_left(db)\r\nlabel_replace(redis_server_up{cluster=\"$cluster\", db=\"$db\",role=\"master\"}, \"shard_number\", \"$1\", \"redis\", \"(.*)\")) by (db)",
     "legendFormat": "main threads max (masters) - system"
    },
    {
     "expr": "max(irate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\", mode=~\"system|user\",db=\"$db\"}[1m])) by (db, mode)",
     "legendFormat": "all threads max (masters) "
    },
    {
     "expr": "avg(irate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\", mode=\"system\",db=\"$db\", role=\"slave\"}[1m])) by (db, mode)",
     "legendFormat": "Slave main threads"
    }
   ]
  },
  {
   "title": "CPU Usage By Shards ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\", mode=\"user\",db=\"$db\"}[1m])) by (redis, role, mode, node)",
     "legendFormat": "shard: {{redis}}, role: {{role}}, node: {{node}},  mode: {{mode}}"
    },
    {
     "expr": "avg(irate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\", mode=\"system\",db=\"$db\"}[1m])) by (redis, role, mode, node)",
     "legendFormat": "shard: {{redis}}, role: {{role}}, node: {{node}},  mode: {{mode}}"
    }
   ]
  },
  {
   "title": "Proxy CPU Usage Total ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\",groupname=\"dmcproxy\", mode=~\"user|system\"}[$aggregation])) by (node)",
     "legendFormat": "CPU Total node {{node}}"
    }
   ]
  },
  { "title": "Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Avg OPS Per Second",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg(rate(endpoint_read_requests{cluster=\"$cluster\", db=\"$db\"}[1m]) + rate(endpoint_write_requests{cluster=\"$cluster\", db=\"$db\"}[1m]) + rate(endpoint_other_requests{cluster=\"$cluster\", db=\"$db\"}[1m]))"
    }
   ]
  },
  {
   "title": "OPS Per Second Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (rate(endpoint_write_requests{cluster=\"$cluster\",db=\"$db\"}[$__rate_interval]) + rate(endpoint_read_requests{cluster=\"$cluster\",db=\"$db\"}[$__rate_interval]) + rate(endpoint_other_requests{cluster=\"$cluster\",db=\"$db\"}[$__rate_interval])) ",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum(rate(endpoint_write_requests{cluster=\"$cluster\",db=\"$db\"}[$__rate_interval]))",
     "legendFormat": "Total Write"
    },
    {
     "expr": "sum(rate(endpoint_read_requests{cluster=\"$cluster\",db=\"$db\"}[$__rate_interval]))",
     "legendFormat": "Total Read"
    },
    {
     "expr": "sum(rate(endpoint_other_requests{cluster=\"$cluster\",db=\"$db\"}[$__rate_interval]))",
     "legendFormat": "Total Other"
    },
    {
     "expr": "sum(irate(endpoint_write_requests{cluster=\"$cluster\",db=\"$db\"}[1m])) by (proxy, node)",
     "legendFormat": "endpoint: {{proxy}} node: {{node}} write"
    },
    {
     "expr": "sum(irate(endpoint_read_requests{cluster=\"$cluster\",db=\"$db\"}[1m])) by (proxy, node)",
     "legendFormat": "endpoint: {{proxy}} node: {{node}} read"
    },
    {
     "expr": "sum(irate(endpoint_other_requests{cluster=\"$cluster\",db=\"$db\"}[1m])) by (proxy, node)",
     "legendFormat": "endpoint: {{proxy}} node: {{node}} other"
    }
   ]
  },
  {
   "title": "#Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(endpoint_client_connections{cluster=\"$cluster\", db=\"$db\"} - endpoint_client_disconnections{cluster=\"$cluster\", db=\"$db\"} - endpoint_proxy_disconnections{cluster=\"$cluster\", db=\"$db\"})"
    }
   ]
  },
  {
   "title": "Connection Overview",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "conn" } },
   "targets": [
    {
     "expr": "sum(endpoint_client_connections{cluster=\"$cluster\", db=\"$db\"} - endpoint_client_disconnections{cluster=\"$cluster\", db=\"$db\"} )",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(endpoint_client_connections{cluster=\"$cluster\", db=\"$db\"} - endpoint_client_disconnections{cluster=\"$cluster\", db=\"$db\"} ) by (proxy, node)",
     "legendFormat": "endpoint {{proxy}} node: {{node}}"
    },
    {
     "expr": "rate(endpoint_client_connections{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]) - rate(endpoint_client_disconnections{cluster=\"$cluster\", db=\"$db\"} [$__rate_interval])",
     "legendFormat": "connections per minute for db:$db - node: {{node}}"
    }
   ]
  },
  {
   "title": "Proxy CPU Usage User ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\",groupname=\"dmcproxy\", mode=\"user\"}[$aggregation])",
     "legendFormat": "CPU User node {{node}}"
    }
   ]
  },
  {
   "title": "Proxy CPU Usage System",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\",groupname=\"dmcproxy\", mode=\"system\"}[$aggregation])",
     "legendFormat": "CPU System node: {{node}}"
    }
   ]
  },
  { "title": "Ingress/Egress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Ingress/Egress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "- sum(rate(endpoint_egress{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]))",
     "legendFormat": "endpoint {{proxy}} node {{node}} egress"
    },
    {
     "expr": "sum(rate(endpoint_ingress{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval]))",
     "legendFormat": "endpoint {{proxy}} node {{node}} ingress"
    }
   ]
  },
  {
   "title": "Ingress/Egress By Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "- rate(endpoint_egress{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])",
     "legendFormat": "endpoint {{proxy}} node {{node}} egress"
    },
    {
     "expr": "rate(endpoint_ingress{cluster=\"$cluster\", db=\"$db\"}[$__rate_interval])",
     "legendFormat": "endpoint {{proxy}} node {{node}} ingress"
    }
   ]
  },
  {
   "title": "Ingress/Egress By Shards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(redis_server_total_net_input_bytes{db=\"$db\", cluster=\"$cluster\", role=\"master\"}[1m])",
     "legendFormat": "Master shard Ingress - shard {{ redis }}"
    },
    {
     "expr": " - (rate(redis_server_total_net_input_bytes{db=\"$db\", cluster=\"$cluster\", role=\"master\"}[1m]) - rate(redis_server_master_repl_offset{db=\"$db\", cluster=\"$cluster\", role=\"master\"}[1m]))",
     "legendFormat": "Master shard Egress - shard {{ redis }}"
    },
    {
     "expr": "rate(redis_server_master_repl_offset{db=\"$db\", cluster=\"$cluster\", role=\"master\"}[1m])",
     "legendFormat": "Master shard replication - shard {{ redis }}"
    },
    {
     "expr": "sum(rate(redis_server_repl_touch_bytes{db=\"$db\", cluster=\"$cluster\", role=\"master\"}[1m]))!=0",
     "legendFormat": "Master shard repl touch"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Top Databases By Latency In Cluster",
   "type": "timeseries",
   "description": "WIth this panel you can identify if your specific database latency is impacted by other database on your cluster",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "topk(10, avg(irate(endpoint_read_requests_latency_histogram_sum{cluster=\"$cluster\"}[1m]) + irate(endpoint_write_requests_latency_histogram_sum{cluster=\"$cluster\"}[1m]) + irate(endpoint_other_requests_latency_histogram_sum{cluster=\"$cluster\"}[1m])) by (db) / avg(irate(endpoint_read_requests_latency_histogram_count{cluster=\"$cluster\"}[1m]) + irate(endpoint_write_requests_latency_histogram_count{cluster=\"$cluster\"}[1m]) + irate(endpoint_other_requests_latency_histogram_count{cluster=\"$cluster\"}[1m])) by (db))",
     "legendFormat": "Latency for database: {{db}} "
    }
   ]
  },
  {
   "title": "Shards latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true
  }
 ]
}