{
 "title": "Test Node Dashboard - V2",
 "tags": [
  "Operations Preview",
  "Customer view"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_metrics_up,cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_config{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "aggregation",
    "label": "interval aggregation",
    "query": "10s, 30s, 1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_metrics_up{cluster=\"$cluster\", node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Enterprise Version ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_config{cluster=\"$cluster\", node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "is_primary{node=\"$node\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "# Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_server_used_memory{cluster=\"$cluster\", node=\"$node\", role=\"master\"})",
     "legendFormat": "Primary"
    },
    {
     "expr": "count(redis_server_used_memory{cluster=\"$cluster\", node=\"$node\", role=\"slave\"})",
     "legendFormat": "Replica"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-avg(rate(node_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\",mode=\"idle\"}[$__rate_interval])) by (node)"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_available_memory_bytes{cluster=\"$cluster\",node=\"$node\"} or node_available_memory_no_overbooking_bytes{cluster=\"$cluster\",node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Node IN Quorum?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "has_quorum{node=\"$node\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "OS version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_os_info{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "{{name}} {{version}}"
    }
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_dmi_info{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "{{system_vendor}} {{product_name}}"
    }
   ]
  },
  {
   "title": "# Databases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(redis_server_used_memory{cluster=\"$cluster\", node=\"$node\"}) by (db))"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage on node (100% = 1 core)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\",mode!=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Total Used"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\",mode=\"user\"}[$__rate_interval])) by (node) + sum(rate(node_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\",mode=\"system\"}[$__rate_interval])) by (node)",
     "legendFormat": "user+system"
    },
    {
     "expr": "sum(rate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\", groupname=~\"redis-.*\"}[$__rate_interval]))",
     "legendFormat": "shards system"
    },
    {
     "expr": "sum(rate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\", groupname=\"dmcproxy\"}[$__rate_interval]))",
     "legendFormat": "dmcproxy"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\",mode=\"nice\"}[$__rate_interval])) by (node)",
     "legendFormat": "nice"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\",mode=\"steal\"}[$__rate_interval])) by (node)",
     "legendFormat": "steal"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\",mode=\"softirq\"}[$__rate_interval])) by (node)",
     "legendFormat": "irqs"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\",mode=\"iowait\"}[$__rate_interval])) by (node)",
     "legendFormat": "iowait"
    },
    {
     "expr": "1 - sum(rate(node_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\",mode=\"idle\"}[$__rate_interval])) by (node) - sum(rate(node_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\",mode=\"system\"}[$__rate_interval])) by (node) - sum(rate(node_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\",mode=\"user\"}[$__rate_interval])) by (node) unless sum(rate(node_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\",mode=\"nice\"}[$__rate_interval])) by (node)",
     "legendFormat": "other"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\",mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Total Idle"
    }
   ]
  },
  {
   "title": "DMC Proxy CPU Usage on node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\",groupname=\"dmcproxy\", mode=\"user\"}[$aggregation])",
     "legendFormat": "CPU User"
    },
    {
     "expr": "rate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\", node=\"$node\",groupname=\"dmcproxy\", mode=\"system\"}[$aggregation])",
     "legendFormat": "CPU System"
    }
   ]
  },
  {
   "title": "DMC Proxy Mem Usage on node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{cluster=\"$cluster\", node=\"$node\",groupname=\"dmcproxy\", memtype=\"resident\"}",
     "legendFormat": "Resident memory"
    },
    {
     "expr": "namedprocess_namegroup_memory_bytes{cluster=\"$cluster\", node=\"$node\",groupname=\"dmcproxy\", memtype=\"virtual\"}",
     "legendFormat": "Virtual memory"
    },
    {
     "expr": "namedprocess_namegroup_memory_bytes{cluster=\"$cluster\", node=\"$node\",groupname=\"dmcproxy\", memtype=\"swapped\"}",
     "legendFormat": "Swapped memory"
    }
   ]
  },
  {
   "title": "DMC Proxy Workers Thread CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (threadname) (rate(namedprocess_namegroup_thread_cpu_seconds_total{cluster=\"$cluster\",groupname=\"dmcproxy\",node=\"$node\",threadname=~\"worker-.*\", exporter=\"process\"}[$aggregation])) ",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Redis-CCS Memory Usage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{cluster=\"$cluster\", node=\"$node\",groupname=\"ccs-redis\", memtype=\"resident\"}",
     "legendFormat": "Resident memory"
    },
    {
     "expr": "namedprocess_namegroup_memory_bytes{cluster=\"$cluster\", node=\"$node\",groupname=\"ccs-redis\", memtype=\"virtual\"}",
     "legendFormat": "Virtual memory"
    },
    {
     "expr": "namedprocess_namegroup_memory_bytes{cluster=\"$cluster\", node=\"$node\",groupname=\"ccs-redis\", memtype=\"swapped\"}",
     "legendFormat": "Swapped memory"
    }
   ]
  },
  {
   "title": "Redis-CCS CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(namedprocess_namegroup_cpu_seconds_total{node=\"$node\",cluster=\"$cluster\", mode=\"user\", groupname=~\"ccs-redis\"}[60s])*100) by (groupname)",
     "legendFormat": "{{groupname}} user"
    },
    {
     "expr": "sum(rate(namedprocess_namegroup_cpu_seconds_total{node=\"$node\",cluster=\"$cluster\", mode=\"system\", groupname=~\"ccs-redis\"}[60s])*100) by (groupname)",
     "legendFormat": "{{groupname}} system"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Ingress/Egress Traffic",
   "type": "timeseries",
   "description": "display the ingress/egress traffic on the node's NIC",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{cluster=\"$cluster\", node=\"$node\"}[$__rate_interval])",
     "legendFormat": "Ingress for device: {{device}}"
    },
    {
     "expr": "- rate(node_network_transmit_bytes_total{cluster=\"$cluster\", node=\"$node\"}[$__rate_interval])",
     "legendFormat": "Egress for device: {{device}}"
    }
   ]
  },
  {
   "title": "Top 5 Proxy Egress/Ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "- topk(5, rate(endpoint_egress{cluster=\"$cluster\", node=\"$node\"}[$__rate_interval]))",
     "legendFormat": "Egress listener proxy:{{proxy}} for database :{{db}}"
    },
    {
     "expr": "topk(5, rate(endpoint_ingress{cluster=\"$cluster\", node=\"$node\"}[$__rate_interval]))",
     "legendFormat": "Ingress listener proxy:{{proxy}} for database :{{db}}"
    }
   ]
  },
  {
   "title": "Avg Proxy Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(rate(endpoint_write_requests_latency_histogram_sum{cluster=\"$cluster\", node=\"$node\"}[$__rate_interval]) + rate(endpoint_read_requests_latency_histogram_sum{cluster=\"$cluster\", node=\"$node\"}[$__rate_interval]) + rate(endpoint_other_requests_latency_histogram_sum{cluster=\"$cluster\", node=\"$node\"}[$__rate_interval])) by (proxy, node) / avg(rate(endpoint_write_requests_latency_histogram_count{cluster=\"$cluster\", node=\"$node\"}[$__rate_interval]) + rate(endpoint_read_requests_latency_histogram_count{cluster=\"$cluster\", node=\"$node\"}[$__rate_interval]) + rate(endpoint_other_requests_latency_histogram_count{cluster=\"$cluster\", node=\"$node\"}[$__rate_interval])) by (proxy, node)",
     "legendFormat": "listener: {{proxy}}  database: {{db}}"
    }
   ]
  },
  {
   "title": "Top 10 Active Endpoint Connections",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10,endpoint_client_connections{cluster=\"$cluster\", node=\"$node\"} - endpoint_client_disconnections{cluster=\"$cluster\",node=\"$node\"} - endpoint_proxy_disconnections{cluster=\"$cluster\",node=\"$node\"})",
     "legendFormat": "active client connections - database:{{db}}"
    }
   ]
  },
  {
   "title": "Top 10 Active Proxy By Requests (read/write/other)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(endpoint_read_requests{cluster=\"$cluster\", node=\"$node\"}[$__rate_interval]) + rate(endpoint_write_requests{cluster=\"$cluster\", node=\"$node\"}[$__rate_interval]) + rate(endpoint_other_requests{cluster=\"$cluster\", node=\"$node\"}[$__rate_interval])) by (db, proxy))",
     "legendFormat": "listener: {{proxy}} for database: {{db}}"
    }
   ]
  },
  { "title": "Shards Utlization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Top 10 Shards By Used Ram ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, redis_server_used_ram{cluster=\"$cluster\", node=\"$node\"} or redis_server_used_memory{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "redis:{{redis}}, database:{{db}},  role:{{role}}"
    }
   ]
  },
  {
   "title": "CPU Usage Per Shard",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(namedprocess_namegroup_cpu_seconds_total{node=\"$node\",cluster=\"$cluster\", mode=\"user\", groupname=~\".*redis-.*\"}[60s])*100) by (groupname)",
     "legendFormat": "shard: {{groupname}} user"
    },
    {
     "expr": "sum(rate(namedprocess_namegroup_cpu_seconds_total{node=\"$node\",cluster=\"$cluster\", mode=\"system\", groupname=~\".*redis-.*\"}[60s])*100) by (groupname)",
     "legendFormat": "shard: {{groupname}} system"
    }
   ]
  },
  {
   "title": "Shards Size (Sort By Size)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_server_used_memory{cluster=\"$cluster\", node=\"$node\"}",
     "legendFormat": "redis:{{redis}}, database:{{db}},  role:{{role}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Total Shards Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(redis_server_used_memory{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "total shards memory"
    },
    {
     "expr": "sum(redis_server_used_ram{cluster=\"$cluster\", node=\"$node\"})",
     "legendFormat": "total shards ram"
    }
   ]
  },
  {
   "title": "Available Memory ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_available_memory_bytes{cluster=\"$cluster\",node=\"$node\"} or node_available_memory_no_overbooking_bytes{cluster=\"$cluster\",node=\"$node\"}",
     "legendFormat": "Available memory"
    }
   ]
  },
  {
   "title": "Fork Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_server_rdb_last_cow_size{node=\"$node\",cluster=\"$cluster\"} unless delta(redis_server_rdb_last_cow_size{node=\"$node\",cluster=\"$cluster\"}[$__rate_interval]) == 0",
     "legendFormat": "shard last RDB cow - redis: {{redis}}"
    },
    {
     "expr": "redis_server_aof_last_cow_size{node=\"$node\",cluster=\"$cluster\"} unless delta(redis_server_aof_last_cow_size{node=\"$node\",cluster=\"$cluster\"}[$__rate_interval]) == 0",
     "legendFormat": "shard last AOF cow - redis: {{redis}}"
    },
    {
     "expr": "redis_server_mem_aof_buffer{node=\"$node\",cluster=\"$cluster\"}",
     "legendFormat": "shard aofrw buffers - redis: {{redis}}"
    },
    {
     "expr": "redis_server_mem_clients_slaves{node=\"$node\",cluster=\"$cluster\"}",
     "legendFormat": "shard salve buffers - redis: {{redis}}"
    },
    {
     "expr": "redis_rdb_bgsave_in_progress{node=\"$node\",cluster=\"$cluster\"}",
     "legendFormat": "rdb_bgsave_in_progress"
    },
    {
     "expr": "redis_aof_rewrite_in_progress{node=\"$node\",cluster=\"$cluster\"}",
     "legendFormat": "aof_rewrite_in_progress"
    },
    {
     "expr": "redis_server_current_cow_size{node=\"$node\",cluster=\"$cluster\"}",
     "legendFormat": "Current CoW "
    },
    {
     "expr": "redis_server_current_cow_peak{node=\"$node\",cluster=\"$cluster\"}",
     "legendFormat": "Current CoW Peak"
    }
   ]
  },
  {
   "title": "Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(redis_server_allocator_active{node=\"$node\",cluster=\"$cluster\"} / redis_server_allocator_allocated{node=\"$node\",cluster=\"$cluster\"}) - 1",
     "legendFormat": "active / allocated (defraggable)"
    },
    {
     "expr": "avg(redis_server_allocator_resident{node=\"$node\",cluster=\"$cluster\"} / redis_server_allocator_active{node=\"$node\",cluster=\"$cluster\"}) - 1",
     "legendFormat": "resident / active (purgable)"
    },
    {
     "expr": "sum(redis_server_allocator_active{node=\"$node\",cluster=\"$cluster\"} - redis_server_allocator_allocated{node=\"$node\",cluster=\"$cluster\"})",
     "legendFormat": "active - allocated (defraggable)"
    },
    {
     "expr": "sum(redis_server_allocator_resident{node=\"$node\",cluster=\"$cluster\"} - redis_server_allocator_active{node=\"$node\",cluster=\"$cluster\"})",
     "legendFormat": "resident - active (purgable)"
    },
    {
     "expr": "avg(redis_server_active_defrag_running{node=\"$node\",cluster=\"$cluster\"})/100",
     "legendFormat": "active defrag running"
    },
    {
     "expr": "sum(namedprocess_namegroup_memory_bytes{cluster=\"$cluster\", node=\"$node\", memtype=\"resident\", groupname=\"redis-${redis}\"}) - sum(redis_server_allocator_resident{node=\"$node\",cluster=\"$cluster\"})",
     "legendFormat": "process rss - allocator rss"
    },
    {
     "expr": "sum(namedprocess_namegroup_memory_bytes{cluster=\"$cluster\", node=\"$node\", memtype=\"resident\", groupname=\"redis-${redis}\"}) / sum(redis_server_allocator_resident{node=\"$node\",cluster=\"$cluster\"})",
     "legendFormat": "process rss / allocator rss"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_server_rdb_bgsave_in_progress{cluster=\"$cluster\", node=\"$node\"} !=0",
     "legendFormat": "BGSAVE {{redis}} database{{db}}"
    },
    {
     "expr": "redis_server_aof_rewrite_in_progress{cluster=\"$cluster\", node=\"$node\"}!=0",
     "legendFormat": "AOFRW {{redis}} database {{db}}"
    },
    {
     "expr": "redis_server_module_fork_in_progress{cluster=\"$cluster\", node=\"$node\"}!=0",
     "legendFormat": "Module fork {{redis}} database {{db}}"
    }
   ]
  }
 ]
}