{
 "title": "Test Shard dashboard - V2",
 "tags": [ "Operations Preview" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_metrics_up,cluster)"
    }
   },
   {
    "name": "db",
    "label": "db Id",
    "query": {
     "query": "label_values(db_status{cluster=\"$cluster\"}, db)"
    }
   },
   {
    "name": "redis",
    "query": {
     "query": "label_values(redis_server_up{cluster=\"$cluster\", db=\"$db\"}, redis)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(redis_server_up{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"},node)"
    }
   },
   {
    "name": "role",
    "query": {
     "query": "label_values(redis_server_up{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"},role)"
    }
   },
   {
    "name": "slots",
    "query": {
     "query": "label_values(redis_server_up{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}, slots)"
    }
   },
   {
    "name": "aggregation",
    "label": "aggregation interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "status",
    "query": {
     "query": "label_values(db_status{db=\"$db\", cluster=\"$cluster\"}, status)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(redis_server_used_memory{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "#Keys",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (db) (redis_server_db_keys{cluster=\"$cluster\",db=\"$db\", redis=\"$redis\"})"
    }
   ]
  },
  {
   "title": "#Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(redis_server_connected_clients{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Node #",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "options": {
    "content": "<div style=\"text-align:center\"><b style=\"font-size: 20pt\">$node<b></div>"
   }
  },
  {
   "title": "Role",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "options": {
    "content": "<div style=\"text-align:center\"><b style=\"font-size: 20pt\">$role<b></div>"
   }
  },
  {
   "title": "Slots",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "options": {
    "content": "<div style=\"text-align:center\"><b style=\"font-size: 20pt\">$slots<b></div>"
   }
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_server_used_memory{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}",
     "legendFormat": "used_mem - role:{{role}}, node:{{node}}, slots:{{slots}}"
    },
    {
     "expr": "redis_server_used_ram{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}",
     "legendFormat": "used_ram - role:{{role}}, node:{{node}}, slots:{{slots}}"
    },
    {
     "expr": "redis_server_max_ram{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"} < redis_server_used_ram{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"} *.5",
     "legendFormat": "max_ram (when low, near used_ram)"
    },
    {
     "expr": "redis_server_max_process_mem{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"} < redis_server_max_ram{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"} * 1.5",
     "legendFormat": "max_process_mem (when low, near max_ram)"
    },
    {
     "expr": "redis_server_used_ram{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"} - redis_server_mem_aof_buffer{cluster=\"$cluster\",db=\"$db\", redis=\"$redis\"}  - redis_mem_clients_slaves{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}",
     "legendFormat": "used ram - slave/aof bufs"
    },
    {
     "expr": "redis_server_used_memory{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"} - redis_server_mem_aof_buffer{cluster=\"$cluster\", db=\"$db\", redis=\"$redis\"} - redis_server_mem_clients_slaves{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}",
     "legendFormat": "used memory - slave/aof bufs"
    },
    {
     "expr": "namedprocess_namegroup_memory_bytes{cluster=\"$cluster\", groupname=\"redis-${redis}\", memtype=\"resident\"}",
     "legendFormat": "Process RSS"
    },
    {
     "expr": "redis_server_maxmemory{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"} < redis_server_used_memory{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"} * 1.5 and redis_server_maxmemory{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"} > 0",
     "legendFormat": "maxmemory (when low, near maxmemory)"
    },
    {
     "expr": "redis_server_max_process_mem{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"} < redis_server_used_memory{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"} * 1.5",
     "legendFormat": "max_process_mem (when low. mear maxmemory)"
    },
    {
     "expr": "redis_server_current_cow_size{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"} > 0",
     "legendFormat": "Child CoW"
    }
   ]
  },
  {
   "title": "Ops Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_server_total_commands_processed{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}[1m])",
     "legendFormat": "commands / s"
    },
    {
     "expr": "rate(redis_server_keyspace_read_hits{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}[1m])",
     "legendFormat": "read hits /s"
    },
    {
     "expr": "rate(redis_server_keyspace_read_misses{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}[1m])",
     "legendFormat": "read misses /s"
    },
    {
     "expr": "rate(redis_server_keyspace_write_hits{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}[1m])",
     "legendFormat": "write hits /s"
    },
    {
     "expr": "rate(redis_server_keyspace_write_misses{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}[1m])",
     "legendFormat": "write misses / s"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(redis_server_total_net_input_bytes{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}[1m])",
     "legendFormat": "ingress"
    },
    {
     "expr": "- (rate(redis_server_total_net_output_bytes{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}[1m]) - rate(redis_server_master_repl_offset{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "egress"
    },
    {
     "expr": "rate(redis_server_master_repl_offset{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}[1m])",
     "legendFormat": "replication (offset)"
    },
    {
     "expr": "rate(redis_server_repl_touch_bytes{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}[1m])!=0",
     "legendFormat": "repl touch"
    },
    {
     "expr": "rate(redis_server_total_net_input_bytes{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}[1m])!=0",
     "legendFormat": "repl input"
    },
    {
     "expr": "rate(redis_server_repl_touch_bytes{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}[1m])!=0",
     "legendFormat": "repl output"
    }
   ]
  },
  {
   "title": "CPU Usage ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (irate(namedprocess_namegroup_thread_cpu_seconds_total{cluster=\"$cluster\", mode=~\"system|user\", groupname=\"redis-${redis}\"}[1m])) by (threadname)",
     "legendFormat": "{{threadname}}"
    },
    {
     "expr": "sum (irate(namedprocess_namegroup_cpu_seconds_total{cluster=\"$cluster\", mode=~\"system|user\", groupname=\"redis-${redis}\"}[1m])) by (groupname)",
     "legendFormat": " all threads cpu usage for redis: {{groupname}}"
    }
   ]
  },
  { "title": "Keyspace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "#Keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_server_db_keys{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}",
     "legendFormat": "keys"
    },
    {
     "expr": "redis_server_db_expires{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}",
     "legendFormat": "volatile"
    },
    {
     "expr": "max(redis_server_bigdb_ram{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}) by (redis,db,cluster)",
     "legendFormat": "ram"
    },
    {
     "expr": "max(redis_server_bigdb_disk{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}) by (redis,db,cluster)",
     "legendFormat": "disk"
    },
    {
     "expr": "sum(((max(redis_server_bigdb_ram{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}) by (redis,db,cluster)) + (max(redis_server_bigdb_disk{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"} or redis_server_bigdb_disk{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}) by (redis,db,cluster)))) - sum(redis_server_db_keys{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"})",
     "legendFormat": "overlapping"
    },
    {
     "expr": "max(redis_server_bigdb_clean{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}) by (redis,db,cluster)",
     "legendFormat": "clean"
    },
    {
     "expr": "max( redis_server_bigdb_dirty{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}) by (redis,db,cluster)",
     "legendFormat": "dirty"
    },
    {
     "expr": "redis_server_total_blocking_keys{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}!=0",
     "legendFormat": "total_blocking_keys"
    },
    {
     "expr": "redis_server_total_blocking_keys_on_nokey{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}!=0",
     "legendFormat": "total_blocking_keys_on_nokey"
    },
    {
     "expr": "redis_server_tracking_total_keys{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}!=0",
     "legendFormat": "tracking_total_keys"
    },
    {
     "expr": "redis_server_tracking_total_prefixes{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}!=0",
     "legendFormat": "total_blocking_keys"
    },
    {
     "expr": "redis_server_pubsub_patterns{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}!=0",
     "legendFormat": "pubsub_patterns"
    },
    {
     "expr": "redis_server_pubsub_channels{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}!=0",
     "legendFormat": "pubsub_channels"
    },
    {
     "expr": "redis_server_pubsubshard_channels{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}!=0",
     "legendFormat": "pubsubshard_channels"
    },
    {
     "expr": "max( redis_server_bigdb_meta{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}) by (redis,db,cluster)",
     "legendFormat": "meta"
    },
    {
     "expr": "redis_server_total_watched_keys{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}!=0",
     "legendFormat": "total_watched_keys"
    },
    {
     "expr": "redis_server_db_subexpiry{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}",
     "legendFormat": "subexpiry"
    }
   ]
  },
  {
   "title": "Expired / Evicted Objects Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_server_expired_keys{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}[1m])",
     "legendFormat": "shard:$redis - expired"
    },
    {
     "expr": "rate(redis_server_evicted_keys{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}[1m])",
     "legendFormat": "shard:$redis - evicted"
    },
    {
     "expr": "rate(redis_server_expired_subkeys{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}[1m])",
     "legendFormat": "shard:$redis - expired_subkeys"
    },
    {
     "expr": "rate(redis_server_big_disk_expired_subkeys_loaded{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}[1m])",
     "legendFormat": "shard:$redis - big_disk_expired_subkeys_loaded"
    },
    {
     "expr": "rate(redis_server_big_disk_expired_keys{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}[1m])",
     "legendFormat": "shard:$redis - big_disk_expired_keys"
    },
    {
     "expr": "rate(redis_server_big_disk_evicted_keys{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}[1m])",
     "legendFormat": "shard:$redis - big_disk_evicted_keys"
    },
    {
     "expr": "redis_server_big_ttl_histogram_expired{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}!=0",
     "legendFormat": "shard:$redis - big_ttl_histogram_expired"
    },
    {
     "expr": "rate(redis_server_keys_trimmed{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}[1m])!=0",
     "legendFormat": "shard:$redis - trimmed"
    },
    {
     "expr": "redis_server_db0_avg_ttl{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}",
     "legendFormat": "shard:$redis - avg_ttl"
    }
   ]
  },
  {
   "title": "Shard Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_server_connected_clients{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "redis_server_maxclients{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"} < redis_server_connected_clients{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"} * 1.5",
     "legendFormat": "max-clients (when low)"
    },
    {
     "expr": "delta(redis_server_total_connections_received{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}[1m])",
     "legendFormat": "conections / minute"
    },
    {
     "expr": "redis_server_blocked_clients{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}!=0",
     "legendFormat": "blocked_clients"
    },
    {
     "expr": "redis_server_tracking_clients{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}!=0",
     "legendFormat": "tracking_clients"
    },
    {
     "expr": "redis_server_pubsub_clients{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}!=0",
     "legendFormat": "pubsub_clients"
    },
    {
     "expr": "redis_server_watching_clients{db=\"$db\", redis=\"$redis\", cluster=\"$cluster\"}!=0",
     "legendFormat": "watching_clients"
    }
   ]
  },
  { "title": "Memory breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Read/Write Hits/Misses + Lazyfree + Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(redis_server_keyspace_read_hits{db=\"$db\", redis=\"$redis\",cluster=\"$cluster\"}[60s])",
     "legendFormat": "read hits"
    },
    {
     "expr": "rate(redis_server_keyspace_write_hits{db=\"$db\", redis=\"$redis\",cluster=\"$cluster\"}[60s])",
     "legendFormat": "write hits"
    },
    {
     "expr": "rate(redis_server_keyspace_read_misses{db=\"$db\", redis=\"$redis\",cluster=\"$cluster\"}[60s])",
     "legendFormat": "read misses"
    },
    {
     "expr": "rate(redis_server_keyspace_write_misses{db=\"$db\", redis=\"$redis\",cluster=\"$cluster\"}[60s])",
     "legendFormat": "write misses"
    },
    {
     "expr": "rate(redis_server_lazyfreed_objects{db=\"$db\", redis=\"$redis\",cluster=\"$cluster\"}[60s])!=0",
     "legendFormat": "lazyfreed objects"
    },
    {
     "expr": "rate(redis_server_total_error_replies{db=\"$db\", redis=\"$redis\",cluster=\"$cluster\"}[60s])!=0",
     "legendFormat": "total error replies"
    },
    {
     "expr": "rate(redis_server_prefetch_expired{db=\"$db\", redis=\"$redis\",cluster=\"$cluster\"}[60s])!=0",
     "legendFormat": "prefetch_expired"
    },
    {
     "expr": "rate(redis_server_prefetch_missing{db=\"$db\", redis=\"$redis\",cluster=\"$cluster\"}[60s])!=0",
     "legendFormat": "prefetch_missing"
    }
   ]
  },
  {
   "title": "Ram Allocator Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_server_allocator_active{db=\"$db\", redis=\"$redis\",cluster=\"$cluster\"}",
     "legendFormat": "active"
    },
    {
     "expr": " redis_server_allocator_allocated{db=\"$db\", redis=\"$redis\",cluster=\"$cluster\"}",
     "legendFormat": "allocated"
    },
    {
     "expr": "redis_server_allocator_resident{db=\"$db\", redis=\"$redis\",cluster=\"$cluster\"}",
     "legendFormat": "resident"
    },
    {
     "expr": "namedprocess_namegroup_memory_bytes{cluster=\"$cluster\", groupname=\"redis-${redis}\", memtype=\"resident\"}",
     "legendFormat": "process RSS"
    }
   ]
  },
  {
   "title": "Shard Ram Overheads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(redis_server_ram_overhead{cluster=\"$cluster\",db=\"$db\", redis=\"$redis\"} - redis_server_mem_clients_slaves{cluster=\"$cluster\",db=\"$db\", redis=\"$redis\"} )/ redis_server_max_ram{cluster=\"$cluster\",db=\"$db\", redis=\"$redis\"}",
     "legendFormat": "% ram overhead"
    },
    {
     "expr": "redis_server_ram_overhead{cluster=\"$cluster\",db=\"$db\", redis=\"$redis\"} ",
     "legendFormat": "total overhead"
    },
    {
     "expr": "redis_server_mem_clients_slaves{cluster=\"$cluster\",db=\"$db\", redis=\"$redis\"} ",
     "legendFormat": "slave buffers"
    },
    {
     "expr": "redis_server_mem_clients_normal{cluster=\"$cluster\",db=\"$db\", redis=\"$redis\"} ",
     "legendFormat": "client buffers"
    },
    {
     "expr": "redis_server_mem_aof_buffer{cluster=\"$cluster\",db=\"$db\", redis=\"$redis\"} > 0",
     "legendFormat": "aof buffer"
    },
    {
     "expr": "redis_server_mem_replication_backlog{cluster=\"$cluster\",db=\"$db\", redis=\"$redis\"} ",
     "legendFormat": "replication backlog"
    },
    {
     "expr": "redis_server_ram_keys_size{cluster=\"$cluster\",db=\"$db\", redis=\"$redis\"} > 0",
     "legendFormat": "ram_keys_size"
    },
    {
     "expr": "redis_server_keys_ram_overhead{cluster=\"$cluster\",db=\"$db\", redis=\"$redis\"} > 0",
     "legendFormat": "dictionaries"
    },
    {
     "expr": "redis_server_used_memory_scripts{cluster=\"$cluster\",db=\"$db\", redis=\"$redis\"} > 0",
     "legendFormat": "scripts"
    },
    {
     "expr": "redis_server_rocks_ram_used_total{cluster=\"$cluster\",db=\"$db\", redis=\"$redis\"} > 0",
     "legendFormat": "rocks_ram_used_total"
    },
    {
     "expr": "redis_server_rocks_ram_used_for_mem_tables{cluster=\"$cluster\",db=\"$db\", redis=\"$redis\"} > 0",
     "legendFormat": "rocks_ram_used_for_mem_tables"
    },
    {
     "expr": "redis_server_used_memory_vm_total{cluster=\"$cluster\",db=\"$db\", redis=\"$redis\"} > 0",
     "legendFormat": "Lua VM"
    },
    {
     "expr": "redis_server_mem_overhead_db_hashtable_rehashing{cluster=\"$cluster\",db=\"$db\", redis=\"$redis\"} > 0",
     "legendFormat": "dictionary rehashing"
    }
   ]
  },
  {
   "title": "Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "redis_server_mem_fragmentation_ratio{db=\"$db\", redis=\"$redis\",cluster=\"$cluster\"}",
     "legendFormat": "shard rss fragmentation (total)"
    },
    {
     "expr": "redis_server_allocator_active{db=\"$db\", redis=\"$redis\",cluster=\"$cluster\"} / redis_server_allocator_allocated{db=\"$db\", redis=\"$redis\",cluster=\"$cluster\"}",
     "legendFormat": "Shard allocator fragmentation (defraggable?)"
    },
    {
     "expr": "redis_server_allocator_resident{db=\"$db\", redis=\"$redis\",cluster=\"$cluster\"} / redis_server_allocator_active{db=\"$db\", redis=\"$redis\",cluster=\"$cluster\"}",
     "legendFormat": "allocator RSS / active (purgable?)"
    },
    {
     "expr": "sum(namedprocess_namegroup_memory_bytes{cluster=\"$cluster\", groupname=\"redis-${redis}\", memtype=\"resident\"}) / sum(redis_server_allocator_resident{db=\"$db\", redis=\"$redis\",cluster=\"$cluster\"})",
     "legendFormat": "process RSS / allocator resident (process overheads)"
    }
   ]
  }
 ]
}