== Configuring Prometheus

To configure Prometheus for alerting, open the `prometheus.yml` configuration file.

Uncomment the `Alertmanager` section of the file.
The following configuration starts Alertmanager and instructs it to listen on its default port of 9093.

[subs="+quotes"]
----
# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
----

The Rule file section of the config file instructs Alertmanager to read specific rules files.
If you pasted the 'alerts.yml' file into '/etc/prometheus' then the following configuration would be required.

[subs="+quotes"]
----
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'. With the release of Redis
v2 metrics we have re-organized the alerting configuration. Alerts are now organized by group, with latency rules found in
the latency-alerts.yml file, etc.

The following alert categories are available:
 * latency
 * connections
 * throughput
 * capacity
 * utilization
 * synchronization
 * nodes
 * shards

In order to use the alerts it is necessary to add each section's alerts file to the configuration. An example is given
below with the latency file added to the base Prometheus error_rules file.

rule_files:
  - "error_rules.yml"
  - "latency-alerts.yml"
----

Once this is done, restart Prometheus.

The built-in configuration, `error_rules.yml`, has a single alert: Critical Connection Exception.
If you open the Prometheus console, by default located at port 9090, and select the Alert tab,
you will see this alert, as well as the alerts in any other file you have included as a rules file.
