{
 "title": "Cluster Database Latency",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(node_up,cluster)" } },
   {
    "name": "version",
    "query": {
     "query": "label_values(node_up{cluster=\"$cluster\",node=\"$node\"}, cnm_version)"
    }
   },
   {
    "name": "bdb",
    "label": "database",
    "query": {
     "query": "bdb_conns{cluster=\"$cluster\"}"
    }
   },
   {
    "name": "aggregation",
    "label": "interval aggregation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Read Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s", "label": "percents" }
   ],
   "targets": [
    {
     "expr": "bdb_avg_read_latency{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "read"
    },
    {
     "expr": "bdb_avg_read_latency_max{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "read*"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s", "label": "percents" }
   ],
   "targets": [
    {
     "expr": "bdb_avg_write_latency{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "write"
    },
    {
     "expr": "bdb_avg_write_latency_max{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "write*"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "percents" }
   ],
   "targets": [
    {
     "expr": " bdb_conns{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "{{bdb_name}}"
    }
   ]
  },
  {
   "title": "Evicted/Expired",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "percents" }
   ],
   "targets": [
    {
     "expr": "bdb_evicted_objects{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "evicted"
    },
    {
     "expr": "bdb_expired_objects{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "expired"
    }
   ]
  }
 ]
}