{
 "title": "Cluster Database Memory",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(node_up,cluster)" } },
   {
    "name": "version",
    "query": {
     "query": "label_values(node_up{cluster=\"$cluster\",node=\"$node\"}, cnm_version)"
    }
   },
   {
    "name": "bdb",
    "label": "database",
    "query": {
     "query": "bdb_conns{cluster=\"$cluster\"}"
    }
   },
   {
    "name": "aggregation",
    "label": "interval aggregation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "bdb_used_memory", "legendFormat": "{{bdb_name}}" }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "bdb_used_memory{cluster=\"$cluster\", bdb=\"$bdb\"}/bdb_memory_limit{cluster=\"$cluster\", bdb=\"$bdb\"}",
     "legendFormat": "{{bdb_name}}"
    }
   ]
  },
  {
   "title": "Fragmentation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(avg(redis_mem_fragmentation_ratio{cluster=\"$cluster\", bdb=\"$bdb\"} * on(cluster) group_left(bdb_name) bdb_up{})/10)-1",
     "legendFormat": "fragmentation"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(redis_process_resident_memory_bytes{cluster=\"dashboard.local\", bdb=\"1\"} * on(cluster) group_left(bdb_name) bdb_up{})",
     "legendFormat": "resident"
    }
   ]
  }
 ]
}